export const runs = [
	{
		id: "GRATEFUL_8K_RUN",
		properties: {
			activeGoal: 8000.0,
			autodownload: false,
			goal: 8000.0,
			activityType: "DISTANCE",

			previousId: "GRATEFUL_8K_RUN_ENGB",
			previousIds: ["GRATEFUL_8K_RUN_ENGB", "GRATEFUL_8K_RUN"],
		},
		landing: {
			title: "Grateful 8K Run",
			subtitle: "8K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/09c98e80e3bee71dd753572ab1c221dc/grateful-8k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/09c98e80e3bee71dd753572ab1c221dc/grateful-8k-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Grateful 8K Run",
				subtitle: "8K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/09c98e80e3bee71dd753572ab1c221dc/grateful-8k-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Being grateful is a super-power! And this run is all about celebrating that super-power. Join Nike Running Global Head Coach Chris Bennett on this easy and inspiring 8K Run. Coach Bennett helps guide you through an exercise in gratefulness (as well as this almost 5 Mile Run.) You’ll end the 8K not only a better runner... but thankful for the run and so much more.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and motivational 8K run. That’s just under 5 miles. This is a distance-based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/grateful-8k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HALF_AND_HALF",
		properties: {
			activeGoal: 1620.0,
			autodownload: false,
			goal: 1680.0,
			activityType: "SPEED_DURATION",

			previousId: "HALF_AND_HALF_ENGB",
			previousIds: ["HALF_AND_HALF_ENGB", "HALF_AND_HALF"],
		},
		landing: {
			title: "Half & Half",
			subtitle: "29 Min • Treadmill Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/75607397dd96cfe3c3cb25901c3f31cd/half-half.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/75607397dd96cfe3c3cb25901c3f31cd/half-half.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Half & Half",
				subtitle: "29 Min • Treadmill Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/75607397dd96cfe3c3cb25901c3f31cd/half-half.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It's fartlek time! Jump on that treadmill and get ready to roll with NRC Washington D.C. Coach Chelsea Cox. Coach Cox will guide you on an easy warm up and then take you through 21 minutes of alternating periods of hard and easy running.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#4c5aff",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>6:00 Warm up<br>\n4:00 Easy <br>\n2:00 Hard <br>\n3:00 Easy <br>\n1:30 Hard <br>\n1:30 Easy <br>\n3:00 Hard<br>\n2:00 Easy <br>\n4:00 Hard <br>\n<br>\n29 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#4c5aff",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/half-half.png",
					titleColor: "#ffffff",
					backgroundColor: "#4c5aff",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "<p>Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently the Nike Run Club DC Head Coach.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#4c5aff",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HALF_MARATHON_RACE",
		properties: {
			activeGoal: 21100.0,
			autodownload: false,
			goal: 21100.0,
			activityType: "DISTANCE",

			previousId: "HALF_MARATHON_RACE_ENGB",
			previousIds: ["HALF_MARATHON_RACE_ENGB", "HALF_MARATHON_RACE"],
		},
		landing: {
			title: "Half Marathon Race",
			subtitle: "13 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/4d217d585d5cbf373aa0ac94df1f55f5/half-marathon-race.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/4d217d585d5cbf373aa0ac94df1f55f5/half-marathon-race.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "Half Marathon Race",
				subtitle: "13 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/4d217d585d5cbf373aa0ac94df1f55f5/half-marathon-race.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It’s time to take the line! Join Nike Running Global Head Coach Chris Bennett for this 13.1 mile/21.1K guided run that will coach you from the starting line of the Half Marathon to the finish line. Make sure your watch or phone is fully charged at the start because this run is all about getting the best version of you across that finish line.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A motivational and inspiring Half Marathon distance-based run. This run is meant to help an athlete during a race. This is a 13.1 mile/21.1K distance guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/half-marathon-race.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HALF_MARATHON",
		properties: {
			activeGoal: 21100.0,
			autodownload: false,
			goal: 21100.0,
			activityType: "DISTANCE",
		},
		landing: {
			title: "Half Marathon Run",
			subtitle: "13.1 Miles • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/e392a2bc5c35ed2505c4b7fcbbe0fc20/half-marathon-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/e392a2bc5c35ed2505c4b7fcbbe0fc20/half-marathon-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Half Marathon Run",
				subtitle: "13.1 Miles • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/e392a2bc5c35ed2505c4b7fcbbe0fc20/half-marathon-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join Nike Running Global Head Coach Chris Bennett for this great distance based audio guided run. Coach Bennett will be with you every stride to make sure you run a relaxed, confident and strong for the full half marathon distance.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed Half Marathon distance run. A Half Marathon is 13.1 miles or 21.1K. This is a distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/half-marathon-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes we all have the ability to become better versions of ourselves through the sport of running.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HIGHS_AND_LOWS_WITH_DINA",
		properties: {
			activeGoal: 1889.0,
			autodownload: false,
			goal: 1889.0,
			activityType: "DURATION",

			previousId: "HIGHS_AND_LOWS_WITH_DINA_ENGB",
			previousIds: ["HIGHS_AND_LOWS_WITH_DINA_ENGB"],
		},
		landing: {
			title: "Highs & Lows with Dina",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/a1415c6f-9e29-4e83-a8bd-fcf54dcd03df/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/a1415c6f-9e29-4e83-a8bd-fcf54dcd03df/image.png",
			backgroundColor: "#8DE3C9",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#8DE3C9",
			headerCard: {
				title: "Highs & Lows with Dina",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/a1415c6f-9e29-4e83-a8bd-fcf54dcd03df/image.png",
				backgroundColor: "#8DE3C9",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>In this Guided Run, you’ll learn about the highs and lows of running, and how to find and keep your motivation when you need it the most.  Coach Dora and sprinting champion Dina Asher-Smith are here to share their personal experiences and the wisdom they’ve gained over the years. You’ll start to see how to fully embrace the journey of running – the highs just as much as the lows.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>This an easy 30-minute run followed by one minute of post-run coaching and advice.<br>\n<br>\n  Total Experience: 31 Minutes</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Coach Dora is a Nike Running London Coach and a Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and, in doing so, inspires others to do the same.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HILL_HILLIER_HILLIEST",
		properties: {
			activeGoal: 705.0,
			autodownload: false,
			goal: 1515.0,
			activityType: "SPEED_DURATION",

			previousId: "HILL_HILLIER_HILLIEST_ENGB",
			previousIds: ["HILL_HILLIER_HILLIEST_ENGB", "HILL_HILLIER_HILLIEST"],
		},
		landing: {
			title: "Hill Hillier Hilliest",
			subtitle: "27 Min • Hill Workout",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5cd60f0df9240967568917e002745e8a/hill-hillier-hilliest.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5cd60f0df9240967568917e002745e8a/hill-hillier-hilliest.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Hill Hillier Hilliest",
				subtitle: "27 Min • Hill Workout",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5cd60f0df9240967568917e002745e8a/hill-hillier-hilliest.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Take your running higher! It's time to run some hills! This Speed Run includes a series of intervals meant to be done on a hill or incline. Hills are a great way to build strength and speed! In fact, hills are really just speed work in disguise.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up</p>\n<p>Workout:<br>\n1:00 10K pace<br>\n0:45 5K pace<br>\n0:30 Mile pace<br>\n<br>\nRepeat series 3 times.<br>\n<br>\nRecovery intervals will vary between 1 and 2 minutes in duration.<br>\n<br>\n27 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/hill-hillier-hilliest.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HONOR_THE_DREAM",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Honor The Dream",
			subtitle: "30 Min • Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/1cf9f361-5f40-4d48-9003-6d8fc7b0faa3/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/1cf9f361-5f40-4d48-9003-6d8fc7b0faa3/image.png",
			backgroundColor: "#D3373D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D3373D",
			headerCard: {
				title: "Honor The Dream",
				subtitle: "30 Min • Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/1cf9f361-5f40-4d48-9003-6d8fc7b0faa3/image.png",
				backgroundColor: "#D3373D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Sometimes you just need time and space to let your mind wonder and wander and dream. Take thirty minutes with a professional coach in your ear to do just that. Coach Diljeet Taylor, Nike Run Coach, will check in along the way to make sure you’re taking it easy on this recovery run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A relaxed 30 min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HOW_BAD_DO_YOU_WANT_IT",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "How Bad Do You Want It",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/ad6244b4-f70e-42ea-9390-8edbaf9e4872/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/ad6244b4-f70e-42ea-9390-8edbaf9e4872/image.png",
			backgroundColor: "#8E1C21",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#8E1C21",
			headerCard: {
				title: "How Bad Do You Want It",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/ad6244b4-f70e-42ea-9390-8edbaf9e4872/image.png",
				backgroundColor: "#8E1C21",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Who better than a championship coach to talk about setting goals and the steps (figuratively speaking) and strides (literally) that are taken to achieve them? Join Coach Taylor in this 25-minute recovery run that will help you get after what you want. And wanting something bad can be so, so good. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An easy and inspirational 25 min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HOW_FARTLEK_CAN_YOU_GO",
		properties: {
			activeGoal: 1410.0,
			autodownload: false,
			goal: 1470.0,
			activityType: "SPEED_DURATION",

			previousId: "HOW_FARTLEK_CAN_YOU_GO_ENGB",
			previousIds: ["HOW_FARTLEK_CAN_YOU_GO_ENGB", "HOW_FARTLEK_CAN_YOU_GO"],
		},
		landing: {
			title: "How Fartlek Can You Go?",
			subtitle: "26 Min • Fartlek",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/2f01d91e5d500deca6fa14a3453400ac/how-fartlek-can-you-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/2f01d91e5d500deca6fa14a3453400ac/how-fartlek-can-you-go.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "How Fartlek Can You Go?",
				subtitle: "26 Min • Fartlek",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/2f01d91e5d500deca6fa14a3453400ac/how-fartlek-can-you-go.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Get ready to take your speed somewhere new because this fartlek goes everywhere! You'll run your 10K, 5K, Mile and even run your Celebration Pace. That's the pace you run when you're at your best. After a 5 minute warm up, the fartlek portion is 18 minutes and 30 seconds.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: '<p>This workout begins with a 5 minute warm up and is followed by a continuous 18:30 fartlek that alternates between different paces.<br>\n<br>\nFartlek:<br>\n2 x 1:30 at 10K Pace<br>\n3 x 1:00 at 5K Pace<br>\n4 x 30 seconds at Mile Pace<br>\n5 x 15 seconds at Celebration Pace (Best Pace)<br>\n<br>\nEach interval of "hard" running is followed by recovery running done at an easy effort.<br>\n<br>\nDurations of the recovery are equal to the length of the preceding “hard” interval that was run.<br>\n<br>\n26 minute total experience.</p>',
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/how-fartlek-can-you-go.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "IN_CONTROL",
		properties: {
			activeGoal: 1320.0,
			autodownload: false,
			goal: 1650.0,
			activityType: "SPEED_DURATION",

			previousId: "IN_CONTROL_ENGB",
			previousIds: ["IN_CONTROL_ENGB", "IN_CONTROL"],
		},
		landing: {
			title: "In Control",
			subtitle: "28 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/25084098ab1ab852d2eb547168edcc8a/in-control.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/25084098ab1ab852d2eb547168edcc8a/in-control.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "In Control",
				subtitle: "28 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/25084098ab1ab852d2eb547168edcc8a/in-control.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>If you can control your effort, you can control your run. Join NRC LA Coach and Nike Trail Team member Sally McRae for this great Speed Run. Coach Sally will have you start fast and then work on your control as she guides you to easier and longer efforts.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>6:00 Warm up<br>\n1:00 Mile pace<br>\n3:00 5K pace<br>\n5:00 10K pace<br>\n7:00 Easy pace<br>\n<br>\nRecovery intervals will vary between 30 seconds to 2:30 in duration.<br>\n<br>\n28 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/in-control.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "<p>Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "I_NEED_A_WIN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",

			previousId: "I_NEED_A_WIN_ENGB",
			previousIds: ["I_NEED_A_WIN_ENGB", "I_NEED_A_WIN"],
		},
		landing: {
			title: "I Need A Win Run",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/82ab2aa9a382e29b3acd52180ceb5c99/i-need-a-win-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/82ab2aa9a382e29b3acd52180ceb5c99/i-need-a-win-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "I Need A Win Run",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/82ab2aa9a382e29b3acd52180ceb5c99/i-need-a-win-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Do you need a win? Do you need a success? Then you need to do this run! Join Nike Running Global Head Coach Chris Bennett for a 30 minute easy run full of motivation and inspiration. You'll end with a win... with a success... and a great run done.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/i-need-a-win-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "INSPIRED_RUN",
		properties: {
			activeGoal: 3232.0,
			autodownload: false,
			goal: 3232.0,
			activityType: "DISTANCE",

			previousId: "INSPIRED_RUN_ENGB",
			previousIds: ["INSPIRED_RUN_ENGB", "INSPIRED_RUN"],
		},
		landing: {
			title: "Inspired Run",
			subtitle: "3.23K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ef3bc18fa38bfb599d9ad25dcd8d6d6a/inspired-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ef3bc18fa38bfb599d9ad25dcd8d6d6a/inspired-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Inspired Run",
				subtitle: "3.23K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ef3bc18fa38bfb599d9ad25dcd8d6d6a/inspired-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It’s time to breathe new life into your running. Coach Cory is back with this relaxed and motivational and yes, inspiring 3.23K Run. That’s just over 2 miles of great running! So, join Coach Cory as he talks about all those people, places and things that inspire you to be more you. This run is a breath of fresh air… just what you need to keep your running fresh too.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 3.23K run. That’s just over than 2 miles. This is a distance-based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/inspired-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "Coach Cory",
					body: "Coach Cory-Wharton-Malcolm is the Nike Run Club UK Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "IN_THE_ZONE",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "SPEED_DURATION",

			previousId: "IN_THE_ZONE_ENGB",
			previousIds: ["IN_THE_ZONE_ENGB", "IN_THE_ZONE"],
		},
		landing: {
			title: "In The Zone",
			subtitle: "36 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ae6375111bbb027e50aebdd868514cce/in-the-zone.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ae6375111bbb027e50aebdd868514cce/in-the-zone.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "In The Zone",
				subtitle: "36 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ae6375111bbb027e50aebdd868514cce/in-the-zone.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join NRC Coach Sally McRae on this awesome and fun speed run that locks you in on your 5K pace. Some may call it a groove and others may call it a flow. No matter what you call it Coach Sally makes sure you're in the zone for this workout.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n4:00 5K pace<br>\n4:00 5K pace<br>\n4:00 5K pace<br>\n4:00 5K pace<br>\n4:00 5K pace<br>\n<br>\nRecovery intervals will vary between 2 minutes and 2 minutes and 30 seconds in duration.<br>\n<br>\nCoach Sally will be providing guidance and motivation throughout the run.<br>\n<br>\n36 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/in-the-zone.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ITS_OK_5K",
		properties: {
			activeGoal: 5000.0,
			autodownload: false,
			goal: 5000.0,
			activityType: "DISTANCE",

			previousId: "ITS_OK_5K_ENGB",
			previousIds: ["ITS_OK_5K_ENGB"],
		},
		landing: {
			title: "It's Ok 5K",
			subtitle: "5K • Easy Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/8d744e92-9362-4949-aaf0-2431b2b475fb/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/8d744e92-9362-4949-aaf0-2431b2b475fb/image.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "It's Ok 5K",
				subtitle: "5K • Easy Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/8d744e92-9362-4949-aaf0-2431b2b475fb/image.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It’s okay to want to run. It’s okay to need a day off. It’s okay to be tired. It’s okay to be excited. It’s okay to be happy. It’s okay to be sad. It’s okay to be okay. It’s okay to not be okay… as long as you don’t pretend that you’re okay when you’re not okay. Join Nike Running Global Head Coach Chris Bennett for this motivational and inspirational 5K easy run. Coach Bennett will guide you through a series of conversations on this distance based guided run that will help you guide yourself when things are okay and not okay. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A guided 5K (~3.1 mile) run. This is a distance based guided run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "JUST_ANOTHER_RUN",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",

			previousId: "JUST_ANOTHER_RUN_ENGB",
			previousIds: ["JUST_ANOTHER_RUN_ENGB", "JUST_ANOTHER_RUN"],
		},
		landing: {
			title: "Just Another Run",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/dc55c2dbd6dace2fd8c8f64c60c86213/just-another-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/dc55c2dbd6dace2fd8c8f64c60c86213/just-another-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Just Another Run",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/dc55c2dbd6dace2fd8c8f64c60c86213/just-another-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Epic runs. Fun runs. Beautiful runs. Magical runs. They all start as just another run. Join Coach Bennett on this easy 35 minute recovery run. It's just another and by the end you'll understand why that's all it takes to get better.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 35 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/just-another-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "JUST_A_RUN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",

			previousId: "JUST_A_RUN_ENGB",
			previousIds: ["JUST_A_RUN_ENGB", "JUST_A_RUN"],
		},
		landing: {
			title: "Just A Run",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c43ae06c7dd9ef034274635db9cf5a32/just-a-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c43ae06c7dd9ef034274635db9cf5a32/just-a-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Just A Run",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c43ae06c7dd9ef034274635db9cf5a32/just-a-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join Coach Bennett on this guided 30 minute recovery run. It’s not a speed run. It’s not a long run. It’s just a run. And that’s all you need to just get better.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute recovery run with 1 minute of post run guidance and cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Just A Run",
					url: "https://static.nike.com/ntc-prod/images/1e4815b65de2fb81e66a2f71c6e11f90/just-a-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/just-a-run/pl.0057de31735e4a99b136692c8576fa9d",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0VxuvWxVFoDdUcnFPTyfVC",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Coach Bennett has built an entire coaching philosophy on his belief in better. He's an NRC pioneer who helped build the Nike Run Club New York from the ground up.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "JUST_GO_WITH_MO",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",

			previousId: "JUST_GO_WITH_MO_ENGB",
			previousIds: ["JUST_GO_WITH_MO_ENGB", "JUST_GO_WITH_MO"],
		},
		landing: {
			title: "Just Go With Mo",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/9869fcbc5f4f1147da1e2d782816f34d/just-go-with-mo.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/9869fcbc5f4f1147da1e2d782816f34d/just-go-with-mo.png",
			backgroundColor: "#FDD500",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FDD500",
			headerCard: {
				title: "Just Go With Mo",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/9869fcbc5f4f1147da1e2d782816f34d/just-go-with-mo.png",
				backgroundColor: "#FDD500",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "What’s it take to become the most decorated athlete in British history? Sir Mo Farah, one of the world’s greatest runners of all time, sheds light on his humble upbringing, historical wins, and how he takes every day in stride.",
					titleColor: "#ffffff",
					backgroundColor: "#ECB807",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#ECB807",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/just-go-with-mo.png",
					titleColor: "#ffffff",
					backgroundColor: "#ECB807",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Mo Farah",
					body: "Sir Mo Farah is one of the world's greatest distance runners and a 4-time Olympic gold medalist. He won the 5K and 10K at both the 2012 London and 2016 Rio Olympic Games.",
					titleColor: "#ffffff",
					backgroundColor: "#ECB807",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "JUST_JOG_IT",
		properties: {
			activeGoal: 2152.0,
			autodownload: false,
			goal: 2152.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Just Jog It",
			subtitle: "31 Min • Easy Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/be742915-ffca-4ffd-a756-d01f432b5185/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/be742915-ffca-4ffd-a756-d01f432b5185/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Just Jog It",
				subtitle: "31 Min • Easy Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/be742915-ffca-4ffd-a756-d01f432b5185/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>If this is your first time running, your first steps back into running, or you simply need a restart, Just Jog It is the run you’ve been looking for. The goal will be to enjoy each and every step of the journey, not tire you out, so you’ll wanna get back after it tomorrow… and the day after that… and the day after that!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>31-minute easy run that starts with a 5-minute warm up and ends with a 5-minute cool down.</p>\n<p>&#8232;▪ 7 sets of 2 mins @ 4/10 effort with 1 minute of recovery @ 2/10 effort</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/image.png",
					titleColor: "#ffffff",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Frankie",
					body: "<p>Coach Frankie Ruiz is our Miami-based Nike Running Coach who infuses the magic and heritage of his hometown into each of his guided runs. Beyond coaching, he’s the co-founder of the Miami Marathon and a leader in the south Florida running community. On top of leading one of the strongest high school cross country programs in the country, Frankie also coaches Brickell Run Club, one of the largest weekly runs in the world. Over the course of his 20+ year coaching career, Frankie has helped tons of runners cross their first start and finish lines, and whether you’re new to the sport or not, he’s fired up to help you too.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "LADDER_UP_LADDER_DOWN",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1920.0,
			activityType: "SPEED_DURATION",

			previousId: "LADDER_UP_LADDER_DOWN_ENGB",
			previousIds: ["LADDER_UP_LADDER_DOWN_ENGB", "LADDER_UP_LADDER_DOWN"],
		},
		landing: {
			title: "Ladder Up\n Ladder Down",
			subtitle: "33 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/1618bcb2099e6eaaa3786ae0ff1d03c7/ladder-up-ladder-down.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/1618bcb2099e6eaaa3786ae0ff1d03c7/ladder-up-ladder-down.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Ladder Up\n Ladder Down",
				subtitle: "33 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/1618bcb2099e6eaaa3786ae0ff1d03c7/ladder-up-ladder-down.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This speed run is a classic ladder workout. You'll begin with repeatedly longer intervals at more relaxed paces and end the workout with shorter intervals at faster paces.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n0:30 Mile pace<br>\n1:00 Mile pace<br>\n1:30 5k pace<br>\n2:00 5k pace<br>\n2:30 10k pace<br>\n2:30 10k pace<br>\n2:00 5k pace<br>\n1:30 5k pace<br>\n1:00 Mile pace<br>\n0:30 Best pace<br>\n<br>\nRecovery intervals vary between 1:00 and 1:30 in duration.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Ladder Up Ladder Down",
					url: "https://static.nike.com/ntc-prod/images/23c76d95cdbab5af1725b032f6a3a81b/ladder-up-ladder-down.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/ladder-up-ladder-down/idpl.96d8f9899da74cd29ddc6027c5a9bc33",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/6X13ZAiYKdd6kTUPI7lkHG",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently the Nike Run Club DC Head Coach.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "LEAD_WITH_CHRIS_DERRICK",
		properties: {
			activeGoal: 2700.0,
			autodownload: false,
			goal: 2700.0,
			activityType: "DURATION",
			profiles: [],
			previousId: "LEAD_WITH_CHRIS_DERRICK_ENGB",
			previousIds: ["LEAD_WITH_CHRIS_DERRICK_ENGB", "LEAD_WITH_CHRIS_DERRICK"],
		},
		landing: {
			title: "Lead with Chris Derrick",
			subtitle: "45 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c90000065986ed2d5a5573d049ef78e3/lead-with-chris-derrick.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c90000065986ed2d5a5573d049ef78e3/lead-with-chris-derrick.png",
			backgroundColor: "#FF8F1C",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF8F1C",
			headerCard: {
				title: "Lead with Chris Derrick",
				subtitle: "45 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c90000065986ed2d5a5573d049ef78e3/lead-with-chris-derrick.png",
				backgroundColor: "#FF8F1C",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join Chris Derrick of the Bowerman Track Club on this 45 minute run. Derrick led his high school team to a Nike Cross Nationals (NXN) team title his senior year by winning the individual title. He shares the lessons he learned from that epic season.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 45 minute easy and relaxed run with 1 minute of post run cool down and guidance.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/lead-with-chris-derrick.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Chris Derrick",
					body: "Chris Derrick is a distance runner on the Bowerman Track Club. Derrick was a 14-time All American while at Stanford University. He is a 3-time US XC Champion with personal bests of 3:39 for 1500m, 13:08 for 5K, 27:31 for 10K and 2:12 in the Marathon.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "LITTLE_TREADMILL_RUN",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",

			previousId: "LITTLE_TREADMILL_RUN_ENGB",
			previousIds: ["LITTLE_TREADMILL_RUN_ENGB", "LITTLE_TREADMILL_RUN"],
		},
		landing: {
			title: "Little Treadmill Run",
			subtitle: "15 Min • Treadmill Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/31d67633ba33c1ff999dd02360eb3a83/little-treadmill-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/31d67633ba33c1ff999dd02360eb3a83/little-treadmill-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Little Treadmill Run",
				subtitle: "15 Min • Treadmill Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/31d67633ba33c1ff999dd02360eb3a83/little-treadmill-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join NRC LA Coach and Nike Trail Team member Sally McRae for this 15 minute recovery run that is specially made for the treadmill. Coach Sally guides you through the entire run and makes sure you end knowing how little runs can help you in big ways.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "15 minute easy run specially made for the treadmill with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/little-treadmill-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "LONG_STRONG_FAST",
		properties: {
			activeGoal: 4001.0,
			autodownload: false,
			goal: 4020.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Long & Strong & Fast",
			subtitle: "67 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/394b1b4fa95008439cbebabc26d5e1d5/long-strong-fast.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/394b1b4fa95008439cbebabc26d5e1d5/long-strong-fast.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "Long & Strong & Fast",
				subtitle: "67 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/394b1b4fa95008439cbebabc26d5e1d5/long-strong-fast.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This Speed Run is epic in just about every way. It’s long. It asks you to run strong. It asks you to run fast. And it ends with you at your best. Join Nike LA Coach Blue Benadum for Long & Strong & Fast. You’ll take on an 8:00 interval at your 10K pace followed by 4:00 at your 5K pace and ending with 2:00 at your Mile pace. That’s one set. Blue has you do three sets! We told you it was epic... and long!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n8:00 10K Pace<br>\n4:00 5K Pace<br>\n2:00 Mile Pace<br>\n<br>\nInterval series should be done 3 x’s<br>\n<br>\n3:00 recovery after 10K Pace<br>\n<br>\n2:00 recovery after 5K and Mile Pace intervals<br>\n<br>\n~68 minute experience</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/long-strong-fast.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Benadum",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their own greatest potential.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "LONG_RUN_WITH_JES",
		properties: {
			activeGoal: 3068.0,
			autodownload: false,
			goal: 3068.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Long Run With Jes",
			subtitle: "55 Min • Long Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/ad547b28-f142-4f25-a02b-6c718fd9eea9/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/ad547b28-f142-4f25-a02b-6c718fd9eea9/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Long Run With Jes",
				subtitle: "55 Min • Long Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/ad547b28-f142-4f25-a02b-6c718fd9eea9/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This run is all about putting in the work and collecting miles. This is where the speed and recovery and easy runs all come together. This is the run to bust out all of the tools in the toolkit – breath, form, controlled pace, speed, and of course fun.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>55 minutes of total running broken up by fun stories, encouragement and instruction from Coach Jes. Just like you were joining her for a Sunday effort.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About The Coach",
					body: "<p>With a dynamic brand of coaching that will keep you on your toes, Brooklyn-based Coach Jes Woods is here to help each runner find their own fun, sustainable running practice they’ll be excited to keep for the long run. You can get serious results without being too serious, and Coach Jes will show you how.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "LUNCH_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",

			previousId: "LUNCH_RUN_ENGB",
			previousIds: ["LUNCH_RUN_ENGB", "LUNCH_RUN"],
		},
		landing: {
			title: "Lunch Run",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ba470bb3119c78c8752def1eb4b79bae/lunch-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ba470bb3119c78c8752def1eb4b79bae/lunch-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Lunch Run",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ba470bb3119c78c8752def1eb4b79bae/lunch-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's one of our favorite meals of the day... eating up meters and miles of great running. We're talking about the Lunch Run! Join NRC Global Head Coach Chris Bennett for this easy 25 minute run. It goes perfect with any meal... but especially lunch.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 25 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/lunch-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MARATHON_RACE",
		properties: {
			activeGoal: 42000.0,
			autodownload: false,
			goal: 42000.0,
			activityType: "DISTANCE",

			previousId: "MARATHON_RACE_ENGB",
			previousIds: ["MARATHON_RACE_ENGB"],
		},
		landing: {
			title: "Marathon Race",
			subtitle: "26.2 Mile • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/10c2c887-775d-4870-9e90-10d0c981b447/marathon_race.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/10c2c887-775d-4870-9e90-10d0c981b447/marathon_race.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "Marathon Race",
				subtitle: "26.2 Mile • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/10c2c887-775d-4870-9e90-10d0c981b447/marathon_race.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>An epic challenge deserves an epic guided run.  Join Nike Running Global Head Coach Chris Bennett for this 26.2 mile/42.12K guided run that will coach you from the starting line of the Marathon all the way to the finish line. Make sure that you and your watch or phone are fully charged at the start because this run is all about getting the best version of you across that finish line. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A motivational and inspiring Marathon distance-based run. This run is meant to help an athlete during a race. This is a 26.2 mile/42.2K distance guided run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/marathon_race.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
