export const runs = [
	{
		id: "NOT_YOUR_TYPICAL_LONG_RUN",
		properties: {
			activeGoal: 3665.0,
			autodownload: false,
			goal: 3665.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Not Your Typical Long Run",
			subtitle: "50 Min • Long Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/0c97aeba-3d99-41fb-9163-84a8a71215eb/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/0c97aeba-3d99-41fb-9163-84a8a71215eb/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Not Your Typical Long Run",
				subtitle: "50 Min • Long Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/0c97aeba-3d99-41fb-9163-84a8a71215eb/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Not Your Typical Long Run is, well, not your typical long run. Coach Frankie sprinkled occasional striders—15 second bursts of pace pushes—what he calls into this long and steady run to add power and intentionality, resulting in you reaping maximum benefits.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>50-minute long run, which includes 5 strider sets, with a 5-minute warm up and 5 minutes of cool down.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Frankie",
					body: "<p>Coach Frankie Ruiz is our Miami-based Nike Running Coach who infuses the magic and heritage of his hometown into each of his guided runs. Beyond coaching, he’s the co-founder of the Miami Marathon and a leader in the south Florida running community. On top of leading one of the strongest high school cross country programs in the country, Frankie also coaches Brickell Run Club, one of the largest weekly runs in the world. Over the course of his 20+ year coaching career, Frankie has helped tons of runners cross their first start and finish lines, and whether you’re new to the sport or not, he’s fired up to help you too.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ONE_HARD_ONE_EASY",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1260.0,
			activityType: "SPEED_DURATION",
			
			previousId: "ONE_HARD_ONE_EASY_ENGB",
			previousIds: ["ONE_HARD_ONE_EASY_ENGB", "ONE_HARD_ONE_EASY"],
		},
		landing: {
			title: "One Hard. One Easy.",
			subtitle: "22 Min • Fartlek",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c79d97ab5dfb979c148f85ab0ec4d26f/one-hard-one-easy.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c79d97ab5dfb979c148f85ab0ec4d26f/one-hard-one-easy.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "One Hard. One Easy.",
				subtitle: "22 Min • Fartlek",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c79d97ab5dfb979c148f85ab0ec4d26f/one-hard-one-easy.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "You just can't beat a great fartlek. Join Coach Cory of Nike Running UK to work on your endurance and speed by playing with your running. You will alternate between one minute of hard and one minute of easy running.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "This speed workout begins with a 5 minute warmup, followed by a 15 minute fartlek that alternates between 1 minute of hard running and 1 minute of easy running. There is 1 minute of post run guidance and cool down.\n\n22 minute total experience.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/one-hard-one-easy.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ONE_HARD_TWO_EASY",
		properties: {
			activeGoal: 1560.0,
			autodownload: false,
			goal: 1620.0,
			activityType: "SPEED_DURATION",
			
			previousId: "ONE_HARD_TWO_EASY_ENGB",
			previousIds: ["ONE_HARD_TWO_EASY_ENGB", "ONE_HARD_TWO_EASY"],
		},
		landing: {
			title: "One Hard. Two Easy.",
			subtitle: "28 Min • Fartlek",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c4b708c6efd37d8bfbf7ec17cdab17c9/one-hard-two-easy.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c4b708c6efd37d8bfbf7ec17cdab17c9/one-hard-two-easy.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "One Hard. Two Easy.",
				subtitle: "28 Min • Fartlek",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c4b708c6efd37d8bfbf7ec17cdab17c9/one-hard-two-easy.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Time to fartlek! Don't worry. That just means it's time to play with your speed. Join Coach Blue Benadum of NRC Los Angeles for a fun workout that works on endurance and speed. You'll alternate between hard and easy running and have a great time doing it.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "This speed workout begins with a 5 minute guided warmup, then a 21 minute fartlek that alternates between 1 minute of hard running and 2 minutes of easy running. There is 1 minute of post run guidance and cool down.\n\n28 minute total experience.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/one-hard-two-easy.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Blue",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their own greatest potential.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ONE_HOUR_RUN",
		properties: {
			activeGoal: 3600.0,
			autodownload: false,
			goal: 3600.0,
			activityType: "DURATION",
			
			previousId: "ONE_HOUR_RUN_ENGB",
			previousIds: ["ONE_HOUR_RUN_ENGB", "ONE_HOUR_RUN"],
		},
		landing: {
			title: "One Hour Run",
			subtitle: "60 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7f7e72df9b6fda16f09a882bcd63e81d/one-hour-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7f7e72df9b6fda16f09a882bcd63e81d/one-hour-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "One Hour Run",
				subtitle: "60 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7f7e72df9b6fda16f09a882bcd63e81d/one-hour-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It’s a classic run… one hour. Invest sixty minutes of distance running with Nike Running Global Head Coach Chris Bennett and it’ll pay off. All you need to do is press start and we’ll make sure you fill up the hour with a better run. Now that sounds like an hour well spent.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable, easy and inspiring one hour guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/one-hour-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ONE_MILE_RUN",
		properties: {
			activeGoal: 1611.0,
			autodownload: false,
			goal: 1611.0,
			activityType: "DISTANCE",
			
			previousId: "ONE_MILE_RUN_ENGB",
			previousIds: ["ONE_MILE_RUN_ENGB", "ONE_MILE_RUN"],
		},
		landing: {
			title: "One Mile Run",
			subtitle: "1 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/1208b92c3581fa01dfc3d11b27921174/one-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/1208b92c3581fa01dfc3d11b27921174/one-mile-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "One Mile Run",
				subtitle: "1 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/1208b92c3581fa01dfc3d11b27921174/one-mile-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "One mile run starts with one press of the start button and one stride. One mile run ends with you one mile better. Join Coach Bennett, Nike Running's Global Head Coach for this relaxed and motivating distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed one mile long run. This is a distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/one-mile-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ONE_MINUTE_RUN",
		properties: {
			activeGoal: 60.0,
			autodownload: false,
			goal: 60.0,
			activityType: "DURATION",
			
			previousId: "ONE_MINUTE_RUN_ENGB",
			previousIds: ["ONE_MINUTE_RUN_ENGB", "ONE_MINUTE_RUN"],
		},
		landing: {
			title: "One Minute Run",
			subtitle: "1 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/2db10b20-b2b9-4c43-a2f1-0ad415bf833c/one-minute-run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/2db10b20-b2b9-4c43-a2f1-0ad415bf833c/one-minute-run.png",
			backgroundColor: "#4C5AFF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4C5AFF",
			headerCard: {
				title: "One Minute Run",
				subtitle: "1 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/2db10b20-b2b9-4c43-a2f1-0ad415bf833c/one-minute-run.png",
				backgroundColor: "#4C5AFF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Sometimes it not about minute... it’s about a minute. Join Nike Running Global Head Coach Chris Bennett for 60 seconds of running bliss. Make sure you enjoy the whole run because it will be over before you know it!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#4C5AFF",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A relaxed one-minute run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#4C5AFF",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60dae1b-7dbf-48a8-a31a-81056f3128f1/one-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#4C5AFF",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#4C5AFF",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ON_THE_MOVE",
		properties: {
			activeGoal: 660.0,
			autodownload: false,
			goal: 990.0,
			activityType: "SPEED_DURATION",
			
			previousId: "ON_THE_MOVE_ENGB",
			previousIds: ["ON_THE_MOVE_ENGB", "ON_THE_MOVE"],
		},
		landing: {
			title: "On The Move",
			subtitle: "17 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/68a00a73b3345abfaa46c7cf35aa3365/on-the-move.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/68a00a73b3345abfaa46c7cf35aa3365/on-the-move.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "On The Move",
				subtitle: "17 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/68a00a73b3345abfaa46c7cf35aa3365/on-the-move.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The perfect workout for anyone who is always on the move. Join NRC DC Head Coach Chelsea Cox for a speed run that starts fast and ends with you faster. You'll do a series of short intervals at different paces. This one will be over before you know it!",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n0:30 Mile pace<br>\n1:00 5K pace<br>\n0:30 Mile pace<br>\n2:00 10K pace<br>\n0:30 Mile pace<br>\n1:00 5K pace<br>\n0:30 Mile pace<br>\n<br>\nRecovery intervals will be 45 seconds in duration.<br>\n<br>\n17 minutes and 30 seconds total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/on-the-move.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently the Nike Run Club DC Head Coach.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "OUT_STRONG_BACK_FAST",
		properties: {
			activeGoal: 1680.0,
			autodownload: false,
			goal: 1740.0,
			activityType: "SPEED_DURATION",
			
			previousId: "OUT_STRONG_BACK_FAST_ENGB",
			previousIds: ["OUT_STRONG_BACK_FAST_ENGB", "OUT_STRONG_BACK_FAST"],
		},
		landing: {
			title: "Out Strong. Back Fast.",
			subtitle: "30 Min • Tempo Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/737c6ae5661076849a1914a413f51283/out-strong-back-fast.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/737c6ae5661076849a1914a413f51283/out-strong-back-fast.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Out Strong. Back Fast.",
				subtitle: "30 Min • Tempo Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/737c6ae5661076849a1914a413f51283/out-strong-back-fast.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's tempo time with NRC Dubai Coach Manal Rostom. After a 5 minute warm up, you'll head out 12 minutes running strong and controlled and then run the final 11 minutes progressively faster. Coach Rostom will guide you through the entire workout.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 5 minute warm up followed by a 23 minute progression Tempo Run and then 1 minute of post run guidance and cool down.\n\nThe goal is to run the first 12 minutes strong. And in the final 11 minutes, the goals is to run faster and cover the same distance as the first 12 minutes... in one minute less time.\n\nThis is one fun Tempo Run!\n\n30 minute total experience.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/out-strong-back-fast.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Manal",
					body: "Dubai Nike Run Club coach Manal Rostom has accomplished many firsts throughout her life by competing in major marathons and reaching the highest peaks of the world. She is breaking barriers for women’s sports globally and inspiring thousands to get active every day.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "POWER_PYRAMID",
		properties: {
			activeGoal: 1620.0,
			autodownload: false,
			goal: 2190.0,
			activityType: "SPEED_DURATION",
			
			previousId: "POWER_PYRAMID_ENGB",
			previousIds: ["POWER_PYRAMID_ENGB", "POWER_PYRAMID"],
		},
		landing: {
			title: "Power Pyramid",
			subtitle: "37 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a12bfc83ac4915425cb4c62aba8a30e2/power-pyramid.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a12bfc83ac4915425cb4c62aba8a30e2/power-pyramid.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Power Pyramid",
				subtitle: "37 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a12bfc83ac4915425cb4c62aba8a30e2/power-pyramid.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Yes, you can work on endurance and speed in the same workout! And the Power Pyramid Speed Run with Sally McRae proves it! You'll run shorter and faster intervals at your Mile pace, mid-range intervals at your 5K pace and even a longer interval at 10K pace.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n1:00 Mile pace<br>\n5:00 5K pace<br>\n10:00 10K pace<br>\n5:00 5K pace<br>\n1:00 Mile pace<br>\n<br>\nRecovery intervals will vary between 30 seconds and 3 minutes in duration.<br>\n<br>\n37 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/power-pyramid.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "PREGNANCY_AND_LONG_RUN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "PREGNANCY_AND_LONG_RUN_ENGB",
			previousIds: ["PREGNANCY_AND_LONG_RUN_ENGB"],
		},
		landing: {
			title: "Pregnancy and Long Runs",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/4b1cd4a8-b9d4-4c5a-a6d1-9efff42af72e/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/4b1cd4a8-b9d4-4c5a-a6d1-9efff42af72e/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Pregnancy and Long Runs",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/4b1cd4a8-b9d4-4c5a-a6d1-9efff42af72e/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>On this 30-minute easy run (or walk... you decide!) we’ve got one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy. Join Jane and Coach Bennett for this great conversation about running that longest run of your week... the Long Run... during the different stages of pregnancy.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable, educational and inspirational 30-minute easy run or walk.<br>\n<br>\nTotal Experience: 30 minutes</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Jane Wake is one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "PREGNANCY_&_SPEED_RUN",
		properties: {
			activeGoal: 2400.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "DURATION",
			
			previousId: "PREGNANCY_&_SPEED_RUN_ENGB",
			previousIds: ["PREGNANCY_&_SPEED_RUN_ENGB"],
		},
		landing: {
			title: "Pregnancy and Speed Runs",
			subtitle: "40 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/dea0a978-c1f8-4761-a444-105564359807/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/dea0a978-c1f8-4761-a444-105564359807/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Pregnancy and Speed Runs",
				subtitle: "40 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/dea0a978-c1f8-4761-a444-105564359807/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>On this 40-minute easy run (or walk… you decide!) we’ve got one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy. Join Jane and Coach Bennett for this great conversation about pregnancy and speed runs. Jane Wake helps navigate through the most common questions associated with pregnant runners and those fast and fun speed runs.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable, educational and inspirational 40-minute easy run or walk.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Jane Wake is one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "QUEER_AND_HERE_LAUF_EN",
		properties: {
			activeGoal: 1744.0,
			autodownload: false,
			goal: 1744.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Queer & Here (EN)",
			subtitle: "30 Min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/02cb1293-a29d-4ee5-9094-eb48881bfad4/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/02cb1293-a29d-4ee5-9094-eb48881bfad4/image.png",
			backgroundColor: "#FFCAE8",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FFCAE8",
			headerCard: {
				title: "Queer & Here (EN)",
				subtitle: "30 Min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/02cb1293-a29d-4ee5-9094-eb48881bfad4/image.png",
				backgroundColor: "#FFCAE8",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Run Details:",
					body: "<p>Join Huyen, Hany & Jarred from Berlin's Joy Run Collective for this 30-minute Easy Run. Learn more about how they manage as a community to feel visible in public, claim space and thus create Safe Spaces. This Special BeTrue Run is less about speed and more about building endurance while giving you food for thought for our journey towards an inclusive society.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Running Details:",
					body: "<p>Easy 30-minute run.</p>\n<p>This is a time-based audio guided run.</p>\n<p></p>\n<p><strong>Duration:</strong> 30 Minutes</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Queer & Here (EN)",
					url: "https://static.nike.com/a/images/w_960,c_limit/feb159d9-8b5f-4444-a231-d6cc5d75febb/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Joy Run Collective:",
					body: "<p>The mission of the Joy Run Collective is to motivate more FLINTA* - meaning women, lesbians, intersex, non-binary, trans* and agender people - to run. Here the focus is especially on People of Color FLINTA* with migration history or refugee background.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RECALIBRATE_AND_RESET",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Recalibrate & Reset",
			subtitle: "20 Min • Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/9e290980-8f91-42ca-acf8-1a5c04109c17/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/9e290980-8f91-42ca-acf8-1a5c04109c17/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Recalibrate & Reset",
				subtitle: "20 Min • Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/9e290980-8f91-42ca-acf8-1a5c04109c17/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>How do you approach recovery? Coach Sashah can teach us all a thing or two about recovery running. She believes that the presence of recovery is not necessarily the absence of movement. During this Guided Run, she’ll help you explore movement as a tool to release the physical or mental tension you may be holding while you cruise through 20 easy minutes of restoration.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>20 min easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/image.png",
					titleColor: "#ffffff",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sashah",
					body: "<p>For Coach Sashah Handal, it’s all about finding balance and treating our bodies with the kindness they deserve. The NYC-based Nike Running Coach focuses on building healthy fitness habits we can use day in and day out. Coach Sashah will help you find fitness goals that work for you and always make time to celebrate the little wins along the way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RECOVERY_RUN_WITH_HEADSPACE",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",
			
			previousId: "RECOVERY_RUN_WITH_HEADSPACE_ENGB",
			previousIds: [
				"RECOVERY_RUN_WITH_HEADSPACE_ENGB",
				"RECOVERY_RUN_WITH_HEADSPACE",
			],
		},
		landing: {
			title: "Recovery Run With Headspace",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/423537b25d8b990b2bc26dfe21d57b68/recovery-run-with-headspace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/423537b25d8b990b2bc26dfe21d57b68/recovery-run-with-headspace.png",
			backgroundColor: "#FED48C",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FED48C",
			headerCard: {
				title: "Recovery Run With Headspace",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/423537b25d8b990b2bc26dfe21d57b68/recovery-run-with-headspace.png",
				backgroundColor: "#FED48C",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "A recovery run is about more than physical recovery. Join Headspace co-founder Andy Puddicombe and Coach Bennett on this 35 minute run and you'll end the run fresher mentally and physically. Remember, great running is dependent on great recovery.",
					titleColor: "#ffffff",
					backgroundColor: "#514C55",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 35 minute recovery run with 1 minute of post run inspiration and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#514C55",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/recovery-run-with-headspace.png",
					titleColor: "#ffffff",
					backgroundColor: "#514C55",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#514C55",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RECOVERY_RUN_WITH_JES",
		properties: {
			activeGoal: 1692.0,
			autodownload: false,
			goal: 1692.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Recovery Run With Jes",
			subtitle: "30 Min • Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/883071c3-3955-4c85-aef7-ecc7781c4fcf/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/883071c3-3955-4c85-aef7-ecc7781c4fcf/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Recovery Run With Jes",
				subtitle: "30 Min • Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/883071c3-3955-4c85-aef7-ecc7781c4fcf/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This run is all about recovering from harder efforts. Getting the body moving, loosening up those muscles, and getting some more miles in. The goal is to leave this run feeling better than when we started.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>30 minutes of easy recovery running inclusive of ending with four strides. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/image.png",
					titleColor: "#ffffff",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About The Coach",
					body: "<p>With a dynamic brand of coaching that will keep you on your toes, Brooklyn-based Coach Jes Woods is here to help each runner find their own fun, sustainable running practice they’ll be excited to keep for the long run. You can get serious results without being too serious, and Coach Jes will show you how. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RHYTHM_AND_ROLL",
		properties: {
			activeGoal: 780.0,
			autodownload: false,
			goal: 1140.0,
			activityType: "SPEED_DURATION",
			
			previousId: "RHYTHM_AND_ROLL_ENGB",
			previousIds: ["RHYTHM_AND_ROLL_ENGB", "RHYTHM_AND_ROLL"],
		},
		landing: {
			title: "Rhythm and Roll",
			subtitle: "21 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/cc46ee054d15c59d59bf546153b0a710/rhythm-and-roll.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/cc46ee054d15c59d59bf546153b0a710/rhythm-and-roll.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Rhythm and Roll",
				subtitle: "21 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/cc46ee054d15c59d59bf546153b0a710/rhythm-and-roll.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This speed run may have short recovery and short intervals but it is long on awesome! Join Coach Cory Wharton-Malcolm for a workout that will have you singing your own praise by the end of it. It’s going to be fast, fun and all rhythm and roll.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n0:30 Mile pace<br>\n0:30 5K pace<br>\n0:30 5K pace<br>\n0:30 5K pace<br>\n0:30 5K pace<br>\n3:00 10K pace<br>\n0:30 5K pace<br>\n0:30 5K pace<br>\n0:30 5K pace<br>\n0:30 5K pace<br>\n0:30 Mile pace<br>\n<br>\nRecovery intervals will be 30 seconds.<br>\n<br>\nCoach Cory will be providing guidance and motivation throughout the run.<br>\n<br>\n21 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/bed2268e4d5136c68179ece05ff737be/rhythm-and-roll.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ROCK_N_ROLLER",
		properties: {
			activeGoal: 1440.0,
			autodownload: false,
			goal: 2010.0,
			activityType: "SPEED_DURATION",
			
			previousId: "ROCK_N_ROLLER_ENGB",
			previousIds: ["ROCK_N_ROLLER_ENGB", "ROCK_N_ROLLER"],
		},
		landing: {
			title: "Rock 'n' Roller",
			subtitle: "34 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/4873340e7be39939e77a8881f894235d/rock-n-roller.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/4873340e7be39939e77a8881f894235d/rock-n-roller.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Rock 'n' Roller",
				subtitle: "34 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/4873340e7be39939e77a8881f894235d/rock-n-roller.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It's time to rock 'n' roll! Take the stage with Coach Cox of Nike Running DC for this awesome speed run. You'll rock out endurance building intervals at your 10K and 5K pace and you'll roll through speed intervals at your Mile and Best pace.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>6:00 Warm up<br>\n5:00 10K pace<br>\n2:30 5K pace<br>\n1:00 Mile pace<br>\n0:30 Best pace<br>\n0:30 Best pace<br>\n1:00 Mile pace<br>\n2:30 5K pace<br>\n5:00 10K pace<br>\n<br>\nRecovery intervals will vary between 60 and 90 seconds in duration.<br>\n<br>\n34 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/rock-n-roller.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently the Nike Run Club DC Head Coach.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_TRAIN_CORE",
		properties: {
			activeGoal: 1268.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "SPEED_DURATION",
			
			previousId: "RUN_TRAIN_CORE_ENGB",
			previousIds: ["RUN_TRAIN_CORE_ENGB", "RUN_TRAIN_CORE"],
		},
		landing: {
			title: "Run & Train:\n Core",
			subtitle: "30 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ee86eb15c493523bc114afa3d64e12b7/run-train-core.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ee86eb15c493523bc114afa3d64e12b7/run-train-core.png",
			backgroundColor: "#B6626F",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#B6626F",
			headerCard: {
				title: "Run & Train:\n Core",
				subtitle: "30 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ee86eb15c493523bc114afa3d64e12b7/run-train-core.png",
				backgroundColor: "#B6626F",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "If you want to become a better runner... become a better athlete. Join NRC UK Coach Cory Wharton-Malcolm for this great workout. You'll warm up, run intervals and be guided through a series of different plank exercises that will strengthen your core.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>6:00 Warm up<br>\n5:00 10K pace<br>\n1:00 Plank<br>\n4:00 5k pace<br>\n1:00 Plank jumping jacks<br>\n3:00 Recovery pace<br>\n1:00 Plank shoulder taps<br>\n2:00 Mile pace<br>\n1:00 Plank knee to elbow<br>\n1:00 Best pace<br>\n<br>\nRecovery intervals will be 30 seconds in duration.<br>\n<br>\n30 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/run-train-core.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_TRAIN_LOWER_BODY",
		properties: {
			activeGoal: 1390.0,
			autodownload: false,
			goal: 1995.0,
			activityType: "SPEED_DURATION",
			
			previousId: "RUN_TRAIN_LOWER_BODY_ENGB",
			previousIds: ["RUN_TRAIN_LOWER_BODY_ENGB", "RUN_TRAIN_LOWER_BODY"],
		},
		landing: {
			title: "Run & Train:\n Lower Body",
			subtitle: "34 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5be58033fdd91471c9d9b29055c2b97a/run-train-lower-body.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5be58033fdd91471c9d9b29055c2b97a/run-train-lower-body.png",
			backgroundColor: "#D28D6C",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D28D6C",
			headerCard: {
				title: "Run & Train:\n Lower Body",
				subtitle: "34 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5be58033fdd91471c9d9b29055c2b97a/run-train-lower-body.png",
				backgroundColor: "#D28D6C",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "If you want to become a better runner... become a better athlete. Join NRC UK Coach Cory Wharton-Malcolm for this great workout. You'll warm up, run intervals and be guided through a series of lower body exercises.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n0:45 Backward lunges<br>\n4:00 Cut down run<br>\n0:45 Forward lunges<br>\n4:00 Recovery pace<br>\n0:45 Squats<br>\n3:00 Cut down run<br>\n0:45 Right leg stand<br>\n3:00 Recovery pace<br>\n0:45 Left leg stand<br>\n2:00 Cut down run<br>\n2:00 Recovery pace<br>\n<br>\nRecovery intervals will be 30 seconds in duration.<br>\n<br>\n34 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-train-lower-body.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_TRAIN_STRIDE_AHEAD",
		properties: {
			activeGoal: 1686.0,
			autodownload: false,
			goal: 1695.0,
			activityType: "SPEED_DURATION",
			profiles: [],
			previousId: "RUN_TRAIN_STRIDE_AHEAD_ENGB",
			previousIds: ["RUN_TRAIN_STRIDE_AHEAD_ENGB", "RUN_TRAIN_STRIDE_AHEAD"],
		},
		landing: {
			title: "Run & Train: Stride Ahead",
			subtitle: "29 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/e90889e7911039875f6e499d3681261f/run-train-stride-ahead.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/e90889e7911039875f6e499d3681261f/run-train-stride-ahead.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "Run & Train: Stride Ahead",
				subtitle: "29 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/e90889e7911039875f6e499d3681261f/run-train-stride-ahead.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "If you want to become a better runner… become a better athlete. Join NRC London Coach Dora for this great workout. You’ll warm up, run intervals and be guided through a series of exercises that will help strengthen your running.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>7:00 Warm Up<br>\n2:00 Recovery Run Pace<br>\n2:30 Hip Flexor<br>\n2:00 10K Pace<br>\n2:30 Hip Flexor<br>\n2:00 Recovery Run Pace<br>\n3:00 Hamstrings<br>\n1:30 5K Pace<br>\n3:40 Backward Lunges<br>\n1:00 Mile Pace<br>\n<br>\nTotal Experience 29:00</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/run-train-stride-ahead.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dora",
					body: "Coach Dora is a Nike Running London Coach and Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and in doing so inspires others to do the same.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_TRAIN_UPPER_BODY",
		properties: {
			activeGoal: 786.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "SPEED_DURATION",
			
			previousId: "RUN_TRAIN_UPPER_BODY_ENGB",
			previousIds: ["RUN_TRAIN_UPPER_BODY_ENGB", "RUN_TRAIN_UPPER_BODY"],
		},
		landing: {
			title: "Run & Train:\n Upper Body",
			subtitle: "20 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a4ce1c4e0b36e5ac76a239d66bf382d3/run-train-upper-body.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a4ce1c4e0b36e5ac76a239d66bf382d3/run-train-upper-body.png",
			backgroundColor: "#9E9C96",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#9E9C96",
			headerCard: {
				title: "Run & Train:\n Upper Body",
				subtitle: "20 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a4ce1c4e0b36e5ac76a239d66bf382d3/run-train-upper-body.png",
				backgroundColor: "#9E9C96",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "If you want to become a better runner... become a better athlete. Join NRC UK Coach Cory Wharton-Malcolm for this great workout. You'll warm up, run intervals and be guided through a series of upper body exercises.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n2:00 5K pace<br>\n1:00 Arm circles<br>\n2:00 5K pace<br>\n1:00 Wide grip push ups<br>\n2:00 5K pace<br>\n1:00 Dips<br>\n2:00 5K pace<br>\n<br>\nRecovery intervals will be 30 seconds in duration.<br>\n<br>\n21 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-train-upper-body.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_AND_WALK_ENGB",
		properties: {
			activeGoal: 1740.0,
			autodownload: false,
			goal: 1740.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Run & Walk",
			subtitle: "30 Min • Run & Walk",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/dbe8ac5a-8a51-435c-8a9d-3eac53d7bf7c/run-and-walk-engb.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/dbe8ac5a-8a51-435c-8a9d-3eac53d7bf7c/run-and-walk-engb.png",
			backgroundColor: "#ff0b46",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run & Walk",
				subtitle: "30 Min • Run & Walk",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/dbe8ac5a-8a51-435c-8a9d-3eac53d7bf7c/run-and-walk-engb.png",
				backgroundColor: "#ff0b46",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This run is perfect if you’re starting out, looking to get back into running or just want a chilled recovery session. Coach Dora will guide you through a series of simple three-minute runs and walks to get you warmed up and running right. She’ll also guide you through some mindfulness techniques to help you tune into your surroundings and make every run even more rewarding.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A relaxed series of 4 x 3-minute run intervals at easy pace, with 3-minute walks after each interval</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/run-and-walk-engb.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dora",
					body: "<p>Coach Dora is a Nike Running London Coach and Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and, in doing so, inspires others to do the same.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_FAST_REPEAT",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "SPEED_DURATION",
			
			previousId: "RUN_FAST_REPEAT_ENGB",
			previousIds: ["RUN_FAST_REPEAT_ENGB"],
		},
		landing: {
			title: "Run\n Fast.\n Repeat.",
			subtitle: "37 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c18ddec41ddf001e9b9d5d1e62f97528/run-fast-repeat.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c18ddec41ddf001e9b9d5d1e62f97528/run-fast-repeat.png",
			backgroundColor: "#D4FF2A",
			titleColor: "#111111",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D4FF2A",
			headerCard: {
				title: "Run\n Fast.\n Repeat.",
				subtitle: "37 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c18ddec41ddf001e9b9d5d1e62f97528/run-fast-repeat.png",
				backgroundColor: "#D4FF2A",
				titleColor: "#111111",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>If fast equals fun then this run is the funnest! Join NRC Washington D.C. Coach Chelsea Cox for an epic Speed Run. You'll do 20... yes, 20 x 30 second intervals and love every half-minute of it. Get faster and stronger every time you get back on the line.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "5:00      Warm up\n\nWorkout:\n0:30      Mile/5K pace\n\nRepeat 20 times. All intervals should be run at your Mile pace except for intervals #1 and #11, which should be run at your 5K pace.\n\nRecovery intervals will be 1 minute in duration.\n\n37 minute total experience.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/run-fast-repeat.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently the Nike Run Club DC Head Coach.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_FOR_LIFE",
		properties: {
			activeGoal: 2283.0,
			autodownload: false,
			goal: 2283.0,
			activityType: "DURATION",
			profiles: [],
			previousId: "RUN_FOR_LIFE_ENGB",
			previousIds: ["RUN_FOR_LIFE_ENGB", "RUN_FOR_LIFE"],
		},
		landing: {
			title: "Run For Life",
			subtitle: "38 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/6a04ada061e42a84d00e0ce051a9b3ff/run-for-life.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/6a04ada061e42a84d00e0ce051a9b3ff/run-for-life.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Run For Life",
				subtitle: "38 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/6a04ada061e42a84d00e0ce051a9b3ff/run-for-life.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's you and Nike chief storyteller, Nelson Farris on this 38 minute run. Celebrate the life and legacy of his great friend, the late, Geoff Hollister. You'll finish this run feeling inspired and passionate to own your life and your health.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 38 minute run with an epic story told by one of the best storytellers in Nike.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run For Life",
					url: "https://static.nike.com/ntc-prod/images/a35116470e19d935cc5c2424b73615b9/run-for-life.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-for-life/pl.ae029e10c37e4cb5b4b4738f39a7dea4",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/7wsAeCVW2zEYDpJOlmuAZp",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Nelson Farris",
					body: "Nelson Farris is one of Nike’s best storytellers and a close friend to many Nike legends. He believes everyone is an athlete if they have a body and he shares his passion for sports with all athletes.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_LONG_WITH_JOANIE",
		properties: {
			activeGoal: 4800.0,
			autodownload: false,
			goal: 4800.0,
			activityType: "DURATION",
			
			previousId: "RUN_LONG_WITH_JOANIE_ENGB",
			previousIds: ["RUN_LONG_WITH_JOANIE_ENGB", "RUN_LONG_WITH_JOANIE"],
		},
		landing: {
			title: "Run Long With Joanie",
			subtitle: "80 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/dc501c9b3e45c8e6ee7e93542ee286f4/run-long-with-joanie.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/dc501c9b3e45c8e6ee7e93542ee286f4/run-long-with-joanie.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Run Long With Joanie",
				subtitle: "80 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/dc501c9b3e45c8e6ee7e93542ee286f4/run-long-with-joanie.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's time to go long. So, go with the best! Join Olympic Gold Medalist and running legend Joan Benoit Samuelson on an inspiring 80 minute run. Joanie offers guidance and motivation throughout the entire run and is joined by Nike Running Global Head Coach Chris Bennett.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An 80 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/run-long-with-joanie.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Joan Benoit Samuelson",
					body: "Joan Benoit Samuelson won the first-ever Women's Olympic Marathon at the 1984 LA Games. She won Boston & Chicago Marathons & held the American Record for 18 years when she ran 2:21:21 in 1985. At the 2008 Olympic Trials, at age 50, JBS ran 2:49:08.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
