export const runs = [
	{
		id: "1000_SECOND_RUN",
		properties: {
			activeGoal: 1000.0,
			autodownload: false,
			goal: 1000.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "1000 Seconds Run",
			subtitle: "16 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/e30da9d2-d89d-4ff4-bddd-fe2f94a6086c/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/e30da9d2-d89d-4ff4-bddd-fe2f94a6086c/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "1000 Seconds Run",
				subtitle: "16 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/e30da9d2-d89d-4ff4-bddd-fe2f94a6086c/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>You can measure your run in minutes. You can measure your run in meters. You can measure your run in miles. And you can measure your run in seconds. But people rarely measure their runs in seconds. This guided run changes that. Join Coach Bennett on the 1000 Seconds Run. This duration based guided run makes sure you acknowledge and celebrate all those seconds that make up each and every one of your runs. By the end of this inspiring easy run you'll truly believe every second counts... because every second does count.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>1000 second duration based easy run. You didn't think we were going to do the math for you did you?</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "10K_HEAD_STARTS",
		properties: {
			activeGoal: 10000.0,
			autodownload: false,
			goal: 10000.0,
			activityType: "DISTANCE",
			
			previousId: "10K_HEAD_STARTS_ENGB",
			previousIds: ["10K_HEAD_STARTS_ENGB", "10K_HEAD_STARTS"],
		},
		landing: {
			title: "10K Head Starts",
			subtitle: "10K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/b55240cba48fd1be89b2bc890f2073f1/10k-head-starts.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/b55240cba48fd1be89b2bc890f2073f1/10k-head-starts.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "10K Head Starts",
				subtitle: "10K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/b55240cba48fd1be89b2bc890f2073f1/10k-head-starts.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Get ready for another great conversation… with yourself. And that means get ready for another great run! 10K Head Starts is a distance based guided run that initiates a series of conversations for you to take part in. Coach Bennett will check in over the course of the run with different statements and follow up with some thought starters for you to take with you on your run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and motivational 10K run. That’s just over 6.2 miles. This is a distance-based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/10k-head-starts.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "10K_RACE",
		properties: {
			activeGoal: 10000.0,
			autodownload: false,
			goal: 10000.0,
			activityType: "DISTANCE",
			
			previousId: "10K_RACE_ENGB",
			previousIds: ["10K_RACE_ENGB", "10K_RACE"],
		},
		landing: {
			title: "10K Race",
			subtitle: "10K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c9635d8dc3c0aaf14d8c6f502a354ac9/10k-race.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c9635d8dc3c0aaf14d8c6f502a354ac9/10k-race.png",
			backgroundColor: "#FF5500",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "10K Race",
				subtitle: "10K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c9635d8dc3c0aaf14d8c6f502a354ac9/10k-race.png",
				backgroundColor: "#FF5500",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Let’s race! Join Nike Running Global Head Coach Chris Bennett for this 10K/6.2 Mile guided run that will coach you from the starting line of the 10K to the finish line. Make sure your watch or phone is fully charged at the start because this run is all about getting the best version of you across that finish line.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A motivational and inspiring 10K distance-based run. This run is meant to help an athlete during a race.\n\nThis is a 10K/6.2 Mile distance guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/10k-race.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "10K_RUN",
		properties: {
			activeGoal: 10000.0,
			autodownload: false,
			goal: 10000.0,
			activityType: "DISTANCE",
			
			previousId: "10K_RUN_ENGB",
			previousIds: ["10K_RUN_ENGB", "10K_RUN"],
		},
		landing: {
			title: "10K Run",
			subtitle: "10K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/507dcfc4b0c2ee3cdd5953a7f6fcfdde/10k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/507dcfc4b0c2ee3cdd5953a7f6fcfdde/10k-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "10K Run",
				subtitle: "10K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/507dcfc4b0c2ee3cdd5953a7f6fcfdde/10k-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's 10K time! Join Nike Running Head Coach Chris Bennett on this distance based guided run. You'll start the 10K better and end 10K better. That means you'll run all 10,000 meters better! Sounds like a great run, right? It is.",
					titleColor: "#FFFFFF",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and fun 10K run. This is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/10k-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "10K_TEMPO_RUN",
		properties: {
			activeGoal: 12002.0,
			autodownload: false,
			goal: 12002.0,
			activityType: "DISTANCE",
			
			previousId: "10K_TEMPO_RUN_ENGB",
			previousIds: ["10K_TEMPO_RUN_ENGB"],
		},
		landing: {
			title: "10K Tempo Run",
			subtitle: "12K • Tempo Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/0ab8926b-48b7-4c67-a688-6ee0cc354fdb/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/0ab8926b-48b7-4c67-a688-6ee0cc354fdb/image.png",
			backgroundColor: "#D4FF2A",
			titleColor: "#111111",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D4FF2A",
			headerCard: {
				title: "10K Tempo Run",
				subtitle: "12K • Tempo Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/0ab8926b-48b7-4c67-a688-6ee0cc354fdb/image.png",
				backgroundColor: "#D4FF2A",
				titleColor: "#111111",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The Tempo Run a foundational piece of every runners training. Join Coach Bennett on this 10K Tempo Run. You’ll warm up 1K and then roll right into a distance based guided Tempo Run. Once the 10K Tempo Run is done you’ll be guided through a 1K guided cool down for a total experience of 12K. Learning how to get comfortable with being uncomfortable is one of the goals of the run. Another goal is to have fun while you do it!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>1000m/~.625 Miles Warm Up<br>\n10000m/~6.2 Miles Tempo Run<br>\n1000m/~.625 Miles Cool Down<br>\n<br>\n12000m/~7.5 miles Total Distance<br>\n<br>\nThis is a distance based guided Speed Run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "10_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "10 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f578a4a390a1788155de0273ded0d021/10-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f578a4a390a1788155de0273ded0d021/10-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "10 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f578a4a390a1788155de0273ded0d021/10-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 10 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/10-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "11_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "11 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/3191dc3bae091d7a9580889883d31504/11-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/3191dc3bae091d7a9580889883d31504/11-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "11 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/3191dc3bae091d7a9580889883d31504/11-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 11 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/11-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "12K_TEMPO_RUN",
		properties: {
			activeGoal: 14002.0,
			autodownload: false,
			goal: 14002.0,
			activityType: "DISTANCE",
			
			previousId: "12K_TEMPO_RUN_ENGB",
			previousIds: ["12K_TEMPO_RUN_ENGB"],
		},
		landing: {
			title: "12K Tempo Run",
			subtitle: "12K • Tempo Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/e2b7b770-fe4a-49c1-807f-610b3a8dc3d1/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/e2b7b770-fe4a-49c1-807f-610b3a8dc3d1/image.png",
			backgroundColor: "#D4FF2A",
			titleColor: "#111111",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D4FF2A",
			headerCard: {
				title: "12K Tempo Run",
				subtitle: "12K • Tempo Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/e2b7b770-fe4a-49c1-807f-610b3a8dc3d1/image.png",
				backgroundColor: "#D4FF2A",
				titleColor: "#111111",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The Tempo Run is one of the best ways for a runner to develop strength and endurance. Join Coach Bennett on this 12K Tempo Run. You’ll warm up 1.5K and then roll right into a distance based guided Tempo Run. Once the 12K Tempo Run is done you’ll be guided through a 500-meter guided cool down for a total running experience of 14K. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>1500m/~.93 Miles Warm Up<br>\n12000m/~6.2 Miles Tempo Run<br>\n500m/~.31 Miles Cool Down<br>\n<br>\n14000m/~8.7 miles Total Distance<br>\nThis is a distance based guided Speed Run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "12_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "12 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/13d1d5dd20c1b2cf9f0fcecea4469e83/12-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/13d1d5dd20c1b2cf9f0fcecea4469e83/12-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "12 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/13d1d5dd20c1b2cf9f0fcecea4469e83/12-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 12 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/12-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "131K_DRESS_REHEARSAL",
		properties: {
			activeGoal: 13103.0,
			autodownload: false,
			goal: 13103.0,
			activityType: "DISTANCE",
			
			previousId: "131K_DRESS_REHEARSAL_ENGB",
			previousIds: ["131K_DRESS_REHEARSAL_ENGB", "131K_DRESS_REHEARSAL"],
		},
		landing: {
			title: "13.1K Dress Rehearsal",
			subtitle: "13.1K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ab6081a5275b569e8636287a88de912c/13-1k-dress-rehearsal.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ab6081a5275b569e8636287a88de912c/13-1k-dress-rehearsal.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "13.1K Dress Rehearsal",
				subtitle: "13.1K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ab6081a5275b569e8636287a88de912c/13-1k-dress-rehearsal.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The best way to get ready for race day is to practice race day! Join Coach Bennett for this 13.1K distance based guided run. Coach Bennett will take you through a simulated Half Marathon Race. During this 13.1k run, Coach will push you physically. Practice won’t make you or the race perfect... but practice sure can make you and your race better.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A fun and focused 13.1K (8.14 miles) run. This is a distance based guided run and is meant to simulate the mental side of a Half Marathon Race while running with your typical Long Run or Recovery Run effort.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/13-1k-dress-rehearsal.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "13_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "13 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/916cd5162ba113faca3fb1061c289a9f/13-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/916cd5162ba113faca3fb1061c289a9f/13-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "13 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/916cd5162ba113faca3fb1061c289a9f/13-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 13 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/13-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "14_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "14 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/9e0d08f2d097d90f70f7c2bde8a50a13/14-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/9e0d08f2d097d90f70f7c2bde8a50a13/14-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "14 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/9e0d08f2d097d90f70f7c2bde8a50a13/14-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 14 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/14-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "15K_RUN",
		properties: {
			activeGoal: 15000.0,
			autodownload: false,
			goal: 15000.0,
			activityType: "DISTANCE",
			
			previousId: "15K_RUN_ENGB",
			previousIds: ["15K_RUN_ENGB", "15K_RUN"],
		},
		landing: {
			title: "15K Run",
			subtitle: "15K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/27cccb520fa6220d66681427ff05b896/15k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/27cccb520fa6220d66681427ff05b896/15k-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "15K Run",
				subtitle: "15K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/27cccb520fa6220d66681427ff05b896/15k-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "15K is just about the perfect distance to work on your strength and endurance! Join Nike Running Global Head Coach Chris Bennett on this awesome distance based guided run. You'll learn how to run with a patient purpose and a relaxed focus.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and comfortable 15K run. This is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/15k-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "15_MINUTE_HEAD_STARTS",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
			previousId: "15_MINUTE_HEAD_STARTS_ENGB",
			previousIds: ["15_MINUTE_HEAD_STARTS_ENGB", "15_MINUTE_HEAD_STARTS"],
		},
		landing: {
			title: "15 Minute Head Starts",
			subtitle: "15 Min • Recovery Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f7bd2ca7bd9ad67fe56eef7a28815729/15-minute-head-starts.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f7bd2ca7bd9ad67fe56eef7a28815729/15-minute-head-starts.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "15 Minute Head Starts",
				subtitle: "15 Min • Recovery Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f7bd2ca7bd9ad67fe56eef7a28815729/15-minute-head-starts.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join Coach Bennett, the Nike Running Global Head Coach, for another run in the Head Starts Series. Coach will give you a thought starter every 90 seconds to run with and discuss... with yourself. You’ll end the run having done a great physical and mental workout.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and comfortable 15-minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/15-minute-head-starts.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "1K_RUN",
		properties: {
			activeGoal: 1002.0,
			autodownload: false,
			goal: 1002.0,
			activityType: "DISTANCE",
			profiles: [],
			previousId: "1K_RUN_ENGB",
			previousIds: ["1K_RUN_ENGB", "1K_RUN"],
		},
		landing: {
			title: "1K Run",
			subtitle: "1K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/cbecc01a8d93102268d2109942dd83d5/1k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/cbecc01a8d93102268d2109942dd83d5/1k-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "1K Run",
				subtitle: "1K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/cbecc01a8d93102268d2109942dd83d5/1k-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Every run counts. Every run can be a great run. Every run can end with you starting the rest of your day stronger. Every run is an excuse to celebrate. Every run can lead to another run. Join Nike Running Global Head Coach Bennett for this 1K run and you’ll also end with one thousand meters better.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and relaxed 1K run. This is a distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/1k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MILE_RACE",
		properties: {
			activeGoal: 1611.0,
			autodownload: false,
			goal: 1611.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "1 Mile Race",
			subtitle: "1 Mile • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/cc350c5c-7a28-4f1d-a888-96fe7c99dbc3/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/cc350c5c-7a28-4f1d-a888-96fe7c99dbc3/image.png",
			backgroundColor: "#C6CAD5",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#C6CAD5",
			headerCard: {
				title: "1 Mile Race",
				subtitle: "1 Mile • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/cc350c5c-7a28-4f1d-a888-96fe7c99dbc3/image.png",
				backgroundColor: "#C6CAD5",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It’s a straight classic. The Mile. One thousand six hundred and nine meters. And the best part about racing the Mile? Once you finish the race, you’re a Sub something miler! Join Nike Running Global Head Coach Chris Bennett for this 1 mile/1.6K guided run that will coach you from the starting line all the way to the finish line. And remember, the best milers believe in themselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A motivational and inspiring Mile distance-based run. This run is meant to help an athlete during a race. This is a 1 mile/1.6K distance guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "1ST_TRIMESTER",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",
			
			previousId: "1ST_TRIMESTER_ENGB",
			previousIds: ["1ST_TRIMESTER_ENGB", "1ST_TRIMESTER"],
		},
		landing: {
			title: "1st Trimester Running",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f1960abde911ce11a368e4fd4e82c8c5/1st-trimester-running.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f1960abde911ce11a368e4fd4e82c8c5/1st-trimester-running.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "1st Trimester Running",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f1960abde911ce11a368e4fd4e82c8c5/1st-trimester-running.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "On this 35-minute easy run (or walk… you decide!) we’ve got one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy. Join Jane and Coach Bennett for this great conversation about running, movement and exercise during the 1st Trimester of pregnancy.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable, educational and inspirational 35-minute easy run or walk with one minute of post run motivation.\n\nTotal Experience: 35 Minutes\n\nThis information should be used as a guide only and is not a substitute for advice from a medical professional. Always consult a medical professional before engaging in a new exercise program and use your judgment for what feels right for you. If you feel faint, experience shortness of breath, dizziness, or related sensations while exercising, stop immediately and seek medical attention as necessary.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/1st-trimester-running.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Jane Wake",
					body: "Jane Wake is one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "1_WEEK_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
			previousId: "1_WEEK_TO_GO_ENGB",
			previousIds: ["1_WEEK_TO_GO_ENGB", "1_WEEK_TO_GO"],
		},
		landing: {
			title: "1 Week To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/cb80d8f40470517fcc184bfc63d1b388/1-week-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/cb80d8f40470517fcc184bfc63d1b388/1-week-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "1 Week To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/cb80d8f40470517fcc184bfc63d1b388/1-week-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 1 week to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/1-week-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "20K_RUN",
		properties: {
			activeGoal: 20004.0,
			autodownload: false,
			goal: 20004.0,
			activityType: "DISTANCE",
			
			previousId: "20K_RUN_ENGB",
			previousIds: ["20K_RUN_ENGB"],
		},
		landing: {
			title: "20K Run",
			subtitle: "20K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/9fdbea8194ad8f376e0666c4e2529e3a/20k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/9fdbea8194ad8f376e0666c4e2529e3a/20k-run.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "20K Run",
				subtitle: "20K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/9fdbea8194ad8f376e0666c4e2529e3a/20k-run.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The 20K Run (almost 12.5 miles) is an excellent opportunity for you to work on building endurance and confidence in your running… and in you. Join Nike Running Global Head Coach Chris Bennett on this relaxed 20K distance based guided run. You’ll end this run wondering why it took you so long… to run long… like this.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy 20K (close to 12.5 mile) run. This is a distance based guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/20k-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "25K_RUN",
		properties: {
			activeGoal: 25003.0,
			autodownload: false,
			goal: 25003.0,
			activityType: "DISTANCE",
			
			previousId: "25K_RUN_ENGB",
			previousIds: ["25K_RUN_ENGB"],
		},
		landing: {
			title: "25K Run",
			subtitle: "15.5 Mile • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/03cff0e0-2813-4142-8ba6-205037d83c01/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/03cff0e0-2813-4142-8ba6-205037d83c01/image.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "25K Run",
				subtitle: "15.5 Mile • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/03cff0e0-2813-4142-8ba6-205037d83c01/image.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Running long can be an excellent opportunity to work on so many different things. And that’s the inspiration for the 25K Run (just over 15.5 miles). Join Nike Running Global Head Coach Chris Bennett on this distance based guided run. You’ll be motivated, inspired and guided through this long run to strengthen both strengths and weakness… but more importantly acknowledge and support the athlete you are now. Get ready to have a great run… and celebrate the great runner you already are. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A guided 25K (~15.5 mile) run. This is a distance based guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "26.2K_DRESS_REHEARSAL",
		properties: {
			activeGoal: 26202.0,
			autodownload: false,
			goal: 26202.0,
			activityType: "DISTANCE",
			
			previousId: "26.2K_DRESS_REHEARSAL",
			previousIds: ["26.2K_DRESS_REHEARSAL"],
		},
		landing: {
			title: "26.2K DRESS REHEARSAL RUN",
			subtitle: "16.3 Mile • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/d852dbc2-c4f8-4e65-8d96-efd0d12867d9/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/d852dbc2-c4f8-4e65-8d96-efd0d12867d9/image.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "26.2K DRESS REHEARSAL RUN",
				subtitle: "16.3 Mile • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/d852dbc2-c4f8-4e65-8d96-efd0d12867d9/image.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The best way to get ready for race day is to practice race day! Join Coach Bennett for this 26.2K distance based guided run. Coach Bennett will take you through a simulated Marathon Race. During this 26.2K run Coach has you physically do a Long Run but mentally run through the race as well as the week before the race... the night before the race... and the morning of the race. Practice won’t make you or the race perfect but practice sure can make you and your race better.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A fun and focused 26.2K (~16.3 miles) run. This is a distance based guided run and is meant to simulate the mental side of a Marathon Race while running with your typical Long Run or Recovery Run effort.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "2K_RUN_EN",
		properties: {
			activeGoal: 2000.0,
			autodownload: false,
			goal: 2000.0,
			activityType: "DISTANCE",
			
			previousId: "2K_RUN_ENGB",
			previousIds: ["2K_RUN_ENGB", "2K_RUN_EN"],
		},
		landing: {
			title: "2K RUN",
			subtitle: "2K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/951acabc6ca8bb6578fe13f455682a5c/2k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/951acabc6ca8bb6578fe13f455682a5c/2k-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "2K RUN",
				subtitle: "2K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/951acabc6ca8bb6578fe13f455682a5c/2k-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The 2K Run (just less than 1.25 miles) is your chance to run two thousand meters with Coach Flanagan! Coach Flanagan is a Bowerman Track Club coach but you may also know her as Shalane Flanagan... multi-time American Record Holder, Olympic medalist and the winner of that marathon they have in New York City. Coach Flanagan will be with you every stride, so you know you’ll end this 2K run a better and wiser runner.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy 2K Run. That’s just less than 1.25 miles. This is a distance-based Audio Guided Run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/2k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Shalane Flanagan",
					body: "Shalane Flanagan is a coach with the Bowerman Track Club. Coach Flanagan was also one of the greatest distance runners of her generation. She is an Olympic Silver medalist in the 10K as well as a winner of the NYC Marathon. Coach Flanagan still holds numerous American Records. She’s now coaching one of the most successful groups of distance runners in the world with the Bowerman Track Club (BTC).",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "2ND_TRIMESTER_RUNNING",
		properties: {
			activeGoal: 2400.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "DURATION",
			
			previousId: "2ND_TRIMESTER_RUNNING_ENGB",
			previousIds: ["2ND_TRIMESTER_RUNNING_ENGB", "2ND_TRIMESTER_RUNNING"],
		},
		landing: {
			title: "2nd Trimester Running",
			subtitle: "40 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/8821b5ef05d42504f280b0d9327d865c/2nd-trimester-running.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/8821b5ef05d42504f280b0d9327d865c/2nd-trimester-running.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "2nd Trimester Running",
				subtitle: "40 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/8821b5ef05d42504f280b0d9327d865c/2nd-trimester-running.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "On this 40-minute easy run (or walk… you decide!) we’ve got one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy. Join Jane and Coach Bennett for this great conversation about running, movement and exercise during the 2nd Trimester of pregnancy.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable, educational and inspirational 40-minute easy run or walk.\n\nTotal Experience: 40 Minutes\n\nThis information should be used as a guide only and is not a substitute for advice from a medical professional. Always consult a medical professional before engaging in a new exercise program and use your judgment for what feels right for you. If you feel faint, experience shortness of breath, dizziness, or related sensations while exercising, stop immediately and seek medical attention as necessary.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/2nd-trimester-running.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Jane Wake",
					body: "Jane Wake is one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "2_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "2 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7ca06762d225e5ed1e0810a3b8e698bb/2-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7ca06762d225e5ed1e0810a3b8e698bb/2-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "2 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7ca06762d225e5ed1e0810a3b8e698bb/2-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 2 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/2-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "3_2_1_GO",
		properties: {
			activeGoal: 690.0,
			autodownload: false,
			goal: 930.0,
			activityType: "SPEED_DURATION",
			
			previousId: "3_2_1_GO_ENGB",
			previousIds: ["3_2_1_GO_ENGB"],
		},
		landing: {
			title: "3,2,1 Go!",
			subtitle: "17 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/b1b88a6ae4612bffdfefbf45f1d10682/3-2-1-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/b1b88a6ae4612bffdfefbf45f1d10682/3-2-1-go.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "3,2,1 Go!",
				subtitle: "17 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/b1b88a6ae4612bffdfefbf45f1d10682/3-2-1-go.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "You and time itself will fly by during this Speed Run. Coach Becs Gentry of Nike London will be your guide as you roll through 4 running intervals. The pace will get faster, the durations will get shorter and you will end better. Are you ready? 3,2,1 and go!",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n3:00 10k Pace<br>\n2:00 5k Pace<br>\n1:00 Mile Pace<br>\n0:30 Best Pace<br>\n<br>\n1 minute guided recovery between all intervals.<br>\n<br>\nCoach Becs will be providing guidance and motivation throughout the run.<br>\n<br>\n17 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "3, 2, 1 Go!",
					url: "https://static.nike.com/ntc-prod/images/85d678dac654982ee57f241107dc4137/3-2-1-go.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/3-2-1-go/pl.748cd68113e44348a2eef0748feeb2cd",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/6bm1UKwZIWZpuaTQM3rw7P",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Becs",
					body: "Coach Becs Gentry is an NRC London Coach. Gentry has been a competitive runner for years as well. Gentry knows that the best way to run your best is to enjoy the run. Coach Becs infuses her coaching with passion and joy and the result is your best run yet.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
