export const runs = [
	{
		id: "CYCLE_RUN_1_AND_2",
		properties: {
			activeGoal: 3600.0,
			autodownload: false,
			goal: 3600.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Menstrual Cycle Run Part 1 & 2",
			subtitle: "60 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7065f9522d023af299925f8fb054e957/cycle-run-part-1-2.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7065f9522d023af299925f8fb054e957/cycle-run-part-1-2.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Menstrual Cycle Run Part 1 & 2",
				subtitle: "60 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7065f9522d023af299925f8fb054e957/cycle-run-part-1-2.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "On this 60-minute easy run we’ve got Nike Running New Zealand Coach Lydia O’Donnell and Dr. Stacy Sims engaging in a conversation on the menstrual cycle and its effect on the athlete and their training. Dr. Sims is one of the world’s leading experts in women's health and performance and specializes and focuses on sex differences with environmental and nutritional considerations for recovery and performance. Come along on a run that ends with you not only a better runner but a more intelligent one too.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable, educational and inspirational 60-minute easy run with one minute of post run motivation.\n\nTotal Experience: 60 Minutes",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/cycle-run-part-1-2.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Dr. Stacy Sims",
					body: "Dr. Stacy Sims is one of the world’s leading experts in women's health and performance and specializes and focuses on sex differences with environmental and nutritional considerations for recovery and performance. Dr. Sims wrote the book Roar, which dives into women’s physiology and discusses how we should train and eat for our bodies.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "CYCLE_RUN_PT_1",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Menstrual Cycle Run PT. 1",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/d05cb624e67b162d0bfcce253922bb08/cycle-run-part-1.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/d05cb624e67b162d0bfcce253922bb08/cycle-run-part-1.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Menstrual Cycle Run PT. 1",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/d05cb624e67b162d0bfcce253922bb08/cycle-run-part-1.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This is Part 1 of 2. On this 30-minute easy run we’ve got Nike Running New Zealand Coach Lydia O’Donnell and Dr. Stacy Sims engaging in a conversation on the menstrual cycle and its effect on the athlete and their training. Dr. Sims is one of the world’s leading experts in women's health and performance and specializes and focuses on sex differences with environmental and nutritional considerations for recovery and performance. Come along on a run that ends with you not only a better runner but a more intelligent one too. Be sure to check out Part 2 after you finish this run!",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "This is Part 1 of 2. A comfortable, educational and inspirational 30-minute easy run with one minute of post run motivation.\n\nTotal Experience: 30 Minutes",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run | Distance Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/cycle-run-part-1.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Dr. Stacy Sims",
					body: "Dr. Stacy Sims is one of the world’s leading experts in women's health and performance and specializes and focuses on sex differences with environmental and nutritional considerations for recovery and performance. Dr. Sims wrote the book Roar, which dives into women’s physiology and discusses how we should train and eat for our bodies.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "CYCLE_RUN_PART_2",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Menstrual Cycle Run PT. 2",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/becf64a5c2278a80d9b254ee857f92aa/cycle-run-part-2.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/becf64a5c2278a80d9b254ee857f92aa/cycle-run-part-2.png",
			backgroundColor: "#002AFF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Menstrual Cycle Run PT. 2",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/becf64a5c2278a80d9b254ee857f92aa/cycle-run-part-2.png",
				backgroundColor: "#002AFF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This is Part 2 of 2. On this 30-minute easy run we’ve got Nike Running New Zealand Coach Lydia O’Donnell and Dr. Stacy Sims engaging in a conversation on the menstrual cycle and its effect on the athlete and their training. Dr. Sims is one of the world leading experts in women's health and performance and specializes and focuses on sex differences with environmental and nutritional considerations for recovery and performance. Come along on a run that ends with you not only a better runner but a more intelligent one too.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "This is Part 2 of 2. A comfortable, educational and inspirational 30-minute easy run with one minute of post run motivation.\n\nTotal Experience: 30 Minutes",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/cycle-run-part-2.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Dr. Stacy Sims",
					body: "Dr. Stacy Sims is one of the world’s leading experts in women's health and performance and specializes and focuses on sex differences with environmental and nutritional considerations for recovery and performance. Dr. Sims wrote the book Roar, which dives into women’s physiology and discusses how we should train and eat for our bodies.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MIAMI_MILE_REPS",
		properties: {
			activeGoal: 8046.0,
			autodownload: false,
			goal: 8046.0,
			activityType: "DISTANCE",
		},
		landing: {
			title: "Miami Mile Reps",
			subtitle: "5 Miles • Interval Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/f07ff3b8-da47-4b43-bfe4-7163f1bcaf4f/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/f07ff3b8-da47-4b43-bfe4-7163f1bcaf4f/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Miami Mile Reps",
				subtitle: "5 Miles • Interval Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/f07ff3b8-da47-4b43-bfe4-7163f1bcaf4f/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This guided interval run is for you if you’re looking to crush your first mile rep workout or you are a long-time runner who wants some extra push. Miami Mile Reps is Coach Frankie’s adaptation of the classic, tried-and-true mile repeats workout. If you're looking to level up your running, you chose the right workout.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5 mile interval run with a mile-long warm up and a half-mile cool down.<br>\n<br>\n● 3 x 1 mile intervals. First rep at tempo pace or 7/10 effort, second rep at 5K pace or 8/10 effort, and final rep rep at mile pace or 9/10 effort</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Frankie",
					body: "<p>Coach Frankie Ruiz is our Miami-based Nike Running Coach who infuses the magic and heritage of his hometown into each of his guided runs. Beyond coaching, he’s the co-founder of the Miami Marathon and a leader in the south Florida running community. On top of leading one of the strongest high school cross country programs in the country, Frankie also coaches Brickell Run Club, one of the largest weekly runs in the world. Over the course of his 20+ year coaching career, Frankie has helped tons of runners cross their first start and finish lines, and whether you’re new to the sport or not, he’s fired up to help you too.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MINDFUL_METERS_WITH_HS",
		properties: {
			activeGoal: 3600.0,
			autodownload: false,
			goal: 3600.0,
			activityType: "DURATION",

			previousId: "MINDFUL_METERS_WITH_HS_ENGB",
			previousIds: ["MINDFUL_METERS_WITH_HS_ENGB", "MINDFUL_METERS_WITH_HS"],
		},
		landing: {
			title: "Mindful Meters",
			subtitle: "60 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/95974d9c250eb06cb97bdcebfd765d3e/mindful-meters.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/95974d9c250eb06cb97bdcebfd765d3e/mindful-meters.png",
			backgroundColor: "#FB7C85",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FB7C85",
			headerCard: {
				title: "Mindful Meters",
				subtitle: "60 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/95974d9c250eb06cb97bdcebfd765d3e/mindful-meters.png",
				backgroundColor: "#FB7C85",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Be in the moment now and you can go anywhere in the future. Olympian English Gardner has experienced ups and downs in her career but she's always moving forward. English joins Andy Puddicombe of Headspace and Coach Bennett on this 60 minute run.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 60 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/mindful-meters.png",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe and English Gardner",
					body: "Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world. \n\nEnglish Gardner is one of the best sprinters in the world. She was a member of the US gold medal 4x100 relay team in the 2016 Olympics.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MINDFUL_MILES",
		properties: {
			activeGoal: 3000.0,
			autodownload: false,
			goal: 3000.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Mindful Miles",
			subtitle: "50 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7885660db723c9aeb68b25363f63e5c5/mindful-miles.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7885660db723c9aeb68b25363f63e5c5/mindful-miles.png",
			backgroundColor: "#FED48C",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FED48C",
			headerCard: {
				title: "Mindful Miles",
				subtitle: "50 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7885660db723c9aeb68b25363f63e5c5/mindful-miles.png",
				backgroundColor: "#FED48C",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Focus your mind, focus your performance. 2016 Olympian Colleen Quigley and Headspace co-founder Andy Puddicombe join Nike Head Coach Chris Bennett for this 50-minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 50 minute recovery run with inspiration from Colleen and Andy.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Mindful Miles",
					url: "https://static.nike.com/ntc-prod/images/a9c8b4d75ab0dbfe3497102b73871b3b/mindful-miles.png",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/mindful-miles/pl.2563c65781a245f5ab4253f5b3c5c847",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/2p7jfepFtOz9B2mo6fzhAF",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe and Colleen Quigley",
					body: "Andy Puddicombe is a former Buddhist monk and co-founder of Headspace, an app that teaches mindfulness and guided meditation. \n\nColleen Quigley is a middle-distance runner who placed 8th in the 3000-meter steeplechase at the 2016 Summer Olympics.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MINDFULNESS_WALK",
		properties: {
			activeGoal: 1203.0,
			autodownload: false,
			goal: 1203.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Mindfulness Walk",
			subtitle: "20 Min • Walk",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/8e4ae2e0-1c45-4c35-9b5d-dfa618c094ca/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/8e4ae2e0-1c45-4c35-9b5d-dfa618c094ca/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Mindfulness Walk",
				subtitle: "20 Min • Walk",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/8e4ae2e0-1c45-4c35-9b5d-dfa618c094ca/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This is a moment for you. For you to refocus, to center yourself, and to move forward with intention. Join Coach Sashah for Mindfulness Walk, a 20-minute walk at a controlled pace, designed to give you a well-deserved moment of peace, and a chance to ground yourself in what’s important to you. Yes we’re moving our bodies, but this is a session dedicated to enhancing your mental wellbeing too. Root yourself in the here and now, and explore the effects mindfulness can have on your overall health. Let's embrace this journey together!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Walk Details",
					body: "<p>A 20-minute easy walk focusing on staying mindful and present in the here and now.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/image.png",
					titleColor: "#ffffff",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "Meet Coach Sashah",
					body: "<p>For Coach Sashah Handal, it's all about finding balance and treating our bodies with the kindness they deserve. The NYC-based Nike Running Coach focuses on building healthy fitness habits we can use day in and day out. Coach Sashah will help you find fitness goals that work for you and always make time to celebrate the little wins along the way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MIND_OVER_MILES_WITH_CITYBOYMOE_EN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Mind Over Miles with Cityboymoe",
			subtitle: "30 Min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/4f806842-cc37-4297-a083-8c65b32c2f44/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/4f806842-cc37-4297-a083-8c65b32c2f44/image.png",
			backgroundColor: "#A373C7",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#A373C7",
			headerCard: {
				title: "Mind Over Miles with Cityboymoe",
				subtitle: "30 Min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/4f806842-cc37-4297-a083-8c65b32c2f44/image.png",
				backgroundColor: "#A373C7",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Run Overview",
					body: "<p>In this Guided Run, you’ll pick up pace and create mental space to navigate the hectic streets of London. Coach Dora and Cityboymoe share their personal experiences on how running has kept them present in their daily lives. You can also listen to a special chilled playlist from cityboymoe to drown out the hype and stride stress-free. By the end, you’ll overcome barriers and no matter what this city throws at you, remember we run with it. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>This is a 30-minute easy run with one minute of guided reflection at the halfway point.<br>\n<br>\nTotal experience: 30 Min </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Mind Over Miles with Cityboymoe",
					url: "https://static.nike.com/a/images/w_960,c_limit/7ef41820-bb5c-4ce8-8770-7c0c2af3db1e/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/playlist/0LbGMFfszl7MJifLKKOQ3a?si=AU-2tcIsQt2WQJsWxKeuEw",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Coach Dora is a Nike Running London Coach and a Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and, in doing so, inspires other to do the same</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MIND_OVER_MILES_WITH_TAYLAH_ELAINE_GB",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Mind Over Miles with Taylah Elaine",
			subtitle: "30 Min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/bb4449a2-54e6-49d7-812d-a7fee94b00ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/bb4449a2-54e6-49d7-812d-a7fee94b00ac/image.png",
			backgroundColor: "#A373C7",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#A373C7",
			headerCard: {
				title: "Mind Over Miles with Taylah Elaine",
				subtitle: "30 Min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/bb4449a2-54e6-49d7-812d-a7fee94b00ac/image.png",
				backgroundColor: "#A373C7",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Run Overview",
					body: "<p>In this Guided Run, you’ll run the road and rule your mind over the madness that London can bring. Coach Dora and popular DJ Taylah Elaine share their reflections on how running calms nerves and helps them find peace in their daily lives. You can also listen to a special chilled playlist from Taylah to let you rise above the noise. By the end, you’ll embrace the lows, despite the madness of the city- we run with it.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>This is a 30-minute easy run with one minute of guided reflection at the halfway point.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Mind Over Miles with Taylah Elaine",
					url: "https://static.nike.com/a/images/w_960,c_limit/c176232c-d3f7-4134-8c63-a0c5babc7467/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Coach Dora is a Nike Running London Coach and a Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and, in doing so, inspires other to do the same.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MOMS_ON_THE_MOVE",
		properties: {
			activeGoal: 1535.0,
			autodownload: false,
			goal: 1535.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Moms On The Move",
			subtitle: "25 Min • Easy Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/ff7144e5-0c07-440a-92d3-18b432d9529b/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/ff7144e5-0c07-440a-92d3-18b432d9529b/image.png",
			backgroundColor: "#dfdfdf",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#dfdfdf",
			headerCard: {
				title: "Moms On The Move",
				subtitle: "25 Min • Easy Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/ff7144e5-0c07-440a-92d3-18b432d9529b/image.png",
				backgroundColor: "#dfdfdf",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This guided run is for all the incredible moms —or moms to be — out there. Coach Bec is joined by Dr. Kayla Hamm, physical therapist and postpartum fitness expert. The goal? Meet mothers where they are to help them prioritize postpartum recovery and take small steps towards running and fitness goals.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>25-minute easy run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/image.png",
					titleColor: "#ffffff",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bec",
					body: "<p>Knowledge is power. But when you run with Coach Bec, that knowledge turns into extra miles per hour. A native Australian now based in LA, Bec Wilcock is a trainer and endurance athlete who knows that tackling any challenge—whether it’s your first run or your tenth marathon—starts with understanding yourself. With an attention to detail and a sense of adventure, Coach Bec helps you go farther and get there smarter.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MORNING_MILES_WITH_HEADSPACE",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",

			previousId: "MORNING_MILES_WITH_HEADSPACE_ENGB",
			previousIds: [
				"MORNING_MILES_WITH_HEADSPACE_ENGB",
				"MORNING_MILES_WITH_HEADSPACE",
			],
		},
		landing: {
			title: "Morning\n Run With Headspace",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/3943ae33be32703274ba02f27edef286/morning-run-with-headspace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/3943ae33be32703274ba02f27edef286/morning-run-with-headspace.png",
			backgroundColor: "#7BCDC8",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#7BCDC8",
			headerCard: {
				title: "Morning\n Run With Headspace",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/3943ae33be32703274ba02f27edef286/morning-run-with-headspace.png",
				backgroundColor: "#7BCDC8",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start your day a better way with Andy Puddicombe, co-founder of Headspace & former Buddhist monk, as he joins Nike Head Coach Chris Bennett on this 30 minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#55505A",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute comfortable run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#55505A",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run With Headspace",
					url: "https://static.nike.com/ntc-prod/images/5033e66339bd97b48b8b2836045e19f5/morning-run-with-headspace.png",
					titleColor: "#ffffff",
					backgroundColor: "#55505A",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-headspace/pl.5599ee1dc0e048bda9d11c65deb6a150",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/5UeYUUQnTy2amoVm6Tbmeb",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#55505A",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MOVIN_ON_UP",
		properties: {
			activeGoal: 1890.0,
			autodownload: false,
			goal: 1890.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Movin’ On Up",
			subtitle: "30 Min • Hill Interval Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/770479bf-9d5b-4e9f-89c9-41bbe2d81902/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/770479bf-9d5b-4e9f-89c9-41bbe2d81902/image.png",
			backgroundColor: "#dfdfdf",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "ON",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#dfdfdf",
			headerCard: {
				title: "Movin’ On Up",
				subtitle: "30 Min • Hill Interval Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/770479bf-9d5b-4e9f-89c9-41bbe2d81902/image.png",
				backgroundColor: "#dfdfdf",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Add some elevation to your training routine. Coach Bec designed Movin’ On Up to help you build resilience, develop a love for hills or stairs, and increase your running confidence. Just find a hill and you’ll be ready to take on this guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>30 minute hill interval run with an 8-minute warm up and a 5-minute cool down.</p>\n<p>&#8232;● 10 x 45-second incline intervals (hills or stairs) at 7/10 effort, followed by 60 seconds of downhill walking recovery.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bec",
					body: "<p>Knowledge is power. But when you run with Coach Bec, that knowledge turns into extra miles per hour. A native Australian now based in LA, Bec Wilcock is a trainer and endurance athlete who knows that tackling any challenge—whether it’s your first run or your tenth marathon—starts with understanding yourself. With an attention to detail and a sense of adventure, Coach Bec helps you go farther and get there smarter.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MUSIC_FOR_A_MOOD_WITH_CITYBOYMOE_EN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Music for a Mood with Cityboymoe",
			subtitle: "30 Min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/ae3304b9-1b12-4595-9af8-6da3a05ce5c5/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/ae3304b9-1b12-4595-9af8-6da3a05ce5c5/image.png",
			backgroundColor: "#FFCAE8",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FFCAE8",
			headerCard: {
				title: "Music for a Mood with Cityboymoe",
				subtitle: "30 Min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/ae3304b9-1b12-4595-9af8-6da3a05ce5c5/image.png",
				backgroundColor: "#FFCAE8",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Run Overview",
					body: "<p>This Guided Run is about helping you rise above the noise in London and stride forward at your own beat. Coach Dora and Cityboymoe share personal memories of music in their lives and how it keeps them in the zone whilst on the move. You can also listen to an exclusive high tempo playlist from Cityboymoe to keep you locked in. By the end, you’ll step ahead and from one pavement pusher to another: we run with it.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>This is a 30-minute easy run with one minute of guided reflection at the halfway point.</p>\n<p>Total experience: 30 Min</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Music for a Mood with Cityboymoe",
					url: "https://static.nike.com/a/images/w_960,c_limit/1c993edd-4dac-4153-907b-ea23ba80fc27/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Coach Dora is a Nike Running London Coach and a Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and, in doing so, inspires other to do the same. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MUSIC_FOR_A_MOOD_EN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Music For A Mood With Taylah Elaine",
			subtitle: "30 Min • Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/7a078a2a-7086-4c01-af33-7b9745e82be9/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/7a078a2a-7086-4c01-af33-7b9745e82be9/image.png",
			backgroundColor: "#ff0b46",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Music For A Mood With Taylah Elaine",
				subtitle: "30 Min • Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/7a078a2a-7086-4c01-af33-7b9745e82be9/image.png",
				backgroundColor: "#ff0b46",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Run Overview",
					body: "<p>This Guided Run is about helping you navigate the chaos of London and set pace to find your rhythm. Coach Dora and rising DJ Taylah Elaine share personal stories on the impact of music on their lives and how it keeps them feeling lighter whilst running. You can also listen to an exclusive high tempo playlist from Taylah to help you move different on your run. By the end, you’ll find the joy in movement, stride forward and whatever the weather-we run with it.\t\t</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>This is a 30-minute easy run with one minute of guided reflection at the halfway point.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Music For A Mood With Taylah Elaine",
					url: "https://static.nike.com/a/images/w_960,c_limit/92510018-c6f3-4300-bb34-0e4a898ba041/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/playlist/4wjDBmwWbZfLougGqC9dcM?si=XNzZ29rORIWDnvnzZuTjXQ&pt_success=1&nd=1",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Coach Dora is a Nike Running Londong Coach and a Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and, in doing so, inspires other to do the same.\t\t\t</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "MYSTERY_SPEED_RUN",
		properties: {
			activeGoal: 960.0,
			autodownload: false,
			goal: 1470.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Mystery Speed Run",
			subtitle: "26 min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/705f745798e353834a301da86abe64a8/mystery-speed-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/705f745798e353834a301da86abe64a8/mystery-speed-run.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "DEFAULT",
			metricVoiceovers: "DEFAULT",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Mystery Speed Run",
				subtitle: "26 min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/705f745798e353834a301da86abe64a8/mystery-speed-run.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Want to know what you're doing for this Speed Run? You'll just need to do it to find out because it's a MYSTERY! Join Nike Running UK Coach Cory for a fun & surprising speed run. You'll know what you need to do... when you need to do it!",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "Ha! You thought we would forget? No details!\nThere is a guided warm up followed by an interval based speed run.\nThe athlete will run a variety of paces and durations over the course of the run. There will be different recovery durations between running intervals.\nCoach Cory will guide the athlete through the entire workout.\nThat's all you need to know.\nWell, that and that this is a really fun Speed Run!\n~26:00 Total Experience",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/mystery-speed-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NEED_A_TEAMMATE",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",

			previousId: "NEED_A_TEAMMATE_ENGB",
			previousIds: ["NEED_A_TEAMMATE_ENGB", "NEED_A_TEAMMATE"],
		},
		landing: {
			title: "Need A Teammate Run",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/263cb82dc2c3d447071c84e5c568da86/need-a-teammate-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/263cb82dc2c3d447071c84e5c568da86/need-a-teammate-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Need A Teammate Run",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/263cb82dc2c3d447071c84e5c568da86/need-a-teammate-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "We all need teammates. We need people in our lives that we can count on to show up, help out, pitch in, & stand by us when we are right & stand up to us when we are wrong. Come along on this great 20-minute easy run with Coach Bennett and Coach Flanagan and learn what makes up a great teammate and how we can all be better teammates to others and be a better teammate to ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and motivational 20-minute easy run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/need-a-teammate-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. Shalane Flanagan is a coach with the elite Bowerman Track Club. Coach Flanagan is an Olympic medalist, American Record Holder and winner of theNYC Marathon.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NEED_THIS_RUN",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",

			previousId: "NEED_THIS_RUN_ENGB",
			previousIds: ["NEED_THIS_RUN_ENGB", "NEED_THIS_RUN"],
		},
		landing: {
			title: "Need This Run",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/9006734d5199ad6c1b85fb0c31f68b87/need-this-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/9006734d5199ad6c1b85fb0c31f68b87/need-this-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Need This Run",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/9006734d5199ad6c1b85fb0c31f68b87/need-this-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Sometimes we may need some help. Sometimes we need support. Sometimes we need to be inspired... motivated... guided. Join Coach Bennett, the Nike Running Global Head Coach, for this 20-minute easy recovery run. If you feel like you need something to move you forward... you Need This Run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and inspiring 20-minute easy run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/need-this-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NEW_MORNING_RUN_WITH_HEADSPACE",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",

			previousId: "NEW_MORNING_RUN_WITH_HEADSPACE_ENGB",
			previousIds: [
				"NEW_MORNING_RUN_WITH_HEADSPACE_ENGB",
				"NEW_MORNING_RUN_WITH_HEADSPACE",
			],
		},
		landing: {
			title: "New Morning Run With Headspace",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a9b380f3e03834698f51dbc98f420d23/new-morning-run-with-headspace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a9b380f3e03834698f51dbc98f420d23/new-morning-run-with-headspace.png",
			backgroundColor: "#66D2CE",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#66D2CE",
			headerCard: {
				title: "New Morning Run With Headspace",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a9b380f3e03834698f51dbc98f420d23/new-morning-run-with-headspace.png",
				backgroundColor: "#66D2CE",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "New morning. New you. Every run is a chance to experience something fresh and new. Join Headspace co-founder Andy Puddicombe and Nike Running Global Head Coach Chris Bennett on this easy 30 minute run and learn how every moment can be a new starting line.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed 30 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/new-morning-run-with-headspace.png",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NEXT_LONG_RUN",
		properties: {
			activeGoal: 2520.0,
			autodownload: false,
			goal: 2520.0,
			activityType: "DURATION",

			previousId: "NEXT_LONG_RUN_ENGB",
			previousIds: ["NEXT_LONG_RUN_ENGB", "NEXT_LONG_RUN"],
		},
		landing: {
			title: "Next Long Run",
			subtitle: "42 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/95f9ef666d7aa64c331f4cd715c67247/next-long-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/95f9ef666d7aa64c331f4cd715c67247/next-long-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Next Long Run",
				subtitle: "42 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/95f9ef666d7aa64c331f4cd715c67247/next-long-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's time for your Next Long Run. Once again, Coach Bennett will be with you as you take your running journey just a little bit further. You'll finish this relaxed 42 minute run knowing how inspired running is the result of an inspired runner.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 42 minute run with 1 minute of post run guidance.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/next-long-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NEXT_RUN",
		properties: {
			activeGoal: 1328.0,
			autodownload: true,
			goal: 1328.0,
			activityType: "DURATION",

			previousId: "NEXT_RUN",
			previousIds: ["NEXT_RUN"],
		},
		landing: {
			title: "Next Run",
			subtitle: "22 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/fc422ec30682ea060abb673640e94f41/next-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/fc422ec30682ea060abb673640e94f41/next-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Next Run",
				subtitle: "22 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/fc422ec30682ea060abb673640e94f41/next-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Coach Bennett is back with more running tips and motivation in this 25 minute audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed 22 minute run with a 3 minute cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Next Run",
					url: "https://static.nike.com/ntc-prod/images/434320b4588c076ff1c7ec1fd5e2eacb/next-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NEXT_SPEED_RUN",
		properties: {
			activeGoal: 1486.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "SPEED_DURATION",

			previousId: "NEXT_SPEED_RUN_ENGB",
			previousIds: ["NEXT_SPEED_RUN_ENGB", "NEXT_SPEED_RUN"],
		},
		landing: {
			title: "Next Speed Run",
			subtitle: "25 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/21be5975e21e0e382a59da20736fbe8d/next-speed-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/21be5975e21e0e382a59da20736fbe8d/next-speed-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Next Speed Run",
				subtitle: "25 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/21be5975e21e0e382a59da20736fbe8d/next-speed-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This is the Next Speed Run. And that means more speeds, more intervals, and more chances for you to have fun being awesome. Join Coach Bennett for this exciting Speed Run and you'll end a smarter, faster, and more motivated athlete.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "5:00      Warm up\n1:00      5K pace\n2:00      10K pace\n1:00      5K pace\n0:45      Mile pace\n0:45      Mile pace\n2:00      10K pace\n1:00      5K pace\n0:45      Mile pace\n0:30      Best pace\n0:15      Best pace\n\nRecovery intervals will be 1 minute in duration.\n\n25 minute total experience.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/next-speed-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NINE_MINUTE_RUN",
		properties: {
			activeGoal: 540.0,
			autodownload: false,
			goal: 540.0,
			activityType: "DURATION",

			previousId: "NINE_MINUTE_RUN_ENGB",
			previousIds: ["NINE_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Nine Minute Run",
			subtitle: "9 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/941109a7-fbbd-4faf-ba6c-c86b421f561c/nine_minute_run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/941109a7-fbbd-4faf-ba6c-c86b421f561c/nine_minute_run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Nine Minute Run",
				subtitle: "9 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/941109a7-fbbd-4faf-ba6c-c86b421f561c/nine_minute_run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Waiting for you on the other side of the starting here are nine minutes of inspiration and motivation. Join Nike Running Global Head Coach Chris Bennett for the easy and fun Nine Minute Run. This run is meant for everyone... because everyone is meant to be a runner. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A relaxed and motivational 9-minute easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/nine_minute_run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NO_REGRETS_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "No regrets run",
			subtitle: "25 min • run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/83d72119-a25e-45f8-8bab-d5155041af07/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/83d72119-a25e-45f8-8bab-d5155041af07/image.png",
			backgroundColor: "#6E1712",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#6E1712",
			headerCard: {
				title: "No regrets run",
				subtitle: "25 min • run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/83d72119-a25e-45f8-8bab-d5155041af07/image.png",
				backgroundColor: "#6E1712",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>You're eyes up looking forwards, not looking back. It's a metaphor<u>,</u> and it's also you on this easy run. Nike Run Coach Diljeet Taylor knows it's not always easy to get your run on. She also knows that once you allow yourself these 25 minutes of easy running, you'll be a better runner and not regret a damn thing about it.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run details",
					body: "<p>An easy 25-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NO_TIME_GO_TIME",
		properties: {
			activeGoal: 840.0,
			autodownload: false,
			goal: 1140.0,
			activityType: "SPEED_DURATION",

			previousId: "NO_TIME_GO_TIME_ENGB",
			previousIds: ["NO_TIME_GO_TIME_ENGB", "NO_TIME_GO_TIME"],
		},
		landing: {
			title: "No Time?\n Go Time!",
			subtitle: "20 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/1d549983ce44e787c47a5abdeee1534b/no-time-go-time.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/1d549983ce44e787c47a5abdeee1534b/no-time-go-time.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "No Time?\n Go Time!",
				subtitle: "20 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/1d549983ce44e787c47a5abdeee1534b/no-time-go-time.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It won't take you very long to realize this Speed Run is awesome. That's good news because the intervals go by fast! You'll be done before you know it. Join NRC London Coach Becs Gentry on this short and sweet speed run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n1:00 Mile pace<br>\n2:00 5K pace<br>\n3:00 10K pace<br>\n2:00 5K pace<br>\n1:00 Mile pace<br>\n<br>\nRecovery intervals will be 1 minute in duration between all intervals.<br>\n<br>\nCoach Becs will be providing guidance and motivation throughout the run.<br>\n<br>\n20 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/no-time-go-time.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Becs",
					body: "Coach Becs Gentry is an NRC London Coach. Gentry has been a competitive runner for years as well. Gentry knows that the best way to run your best is to enjoy the run. Coach Becs infuses her coaching with passion and joy and the result is your best run yet.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "NO_MOTIVATION_RUN_WITH_HEADSPACE",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",

			previousId: "NO_MOTIVATION_RUN_WITH_HEADSPACE_ENGB",
			previousIds: [
				"NO_MOTIVATION_RUN_WITH_HEADSPACE_ENGB",
				"NO_MOTIVATION_RUN_WITH_HEADSPACE",
			],
		},
		landing: {
			title: "Not Motivated Run w/ Headspace",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ea8b2aa607ad0d9e84fcf36be3c7e47e/not-motivated-run-w-headspace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ea8b2aa607ad0d9e84fcf36be3c7e47e/not-motivated-run-w-headspace.png",
			backgroundColor: "#FED48C",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FED48C",
			headerCard: {
				title: "Not Motivated Run w/ Headspace",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ea8b2aa607ad0d9e84fcf36be3c7e47e/not-motivated-run-w-headspace.png",
				backgroundColor: "#FED48C",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Some days you got it. And some days you don't think you got it. Join Andy Puddicombe of Headspace and NRC Global Head Coach Chris Bennett on this 25 minute easy run to discover how motivation is never really lost if you're motivated to find it.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 25 minute recovery run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/not-motivated-run-w-headspace.png",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
