export const runs = [
	{
		id: "RUN_WITH_PERRI",
		properties: {
			activeGoal: 3000.0,
			autodownload: false,
			goal: 3000.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_PERRI_ENGB",
			previousIds: ["RUN_WITH_PERRI_ENGB", "RUN_WITH_PERRI"],
		},
		landing: {
			title: "Run With Perri",
			subtitle: "50 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/4efd99f4d57210e141fb6d1653f9315c/run-with-perri.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/4efd99f4d57210e141fb6d1653f9315c/run-with-perri.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Run With Perri",
				subtitle: "50 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/4efd99f4d57210e141fb6d1653f9315c/run-with-perri.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "We’ve got British Olympian Perri Shakes-Drayton, Jane Wake and Coach Cory on this 50-minute easy run. We’ll join in on their conversation about Perri, her introduction to athletics and her pregnancy and postnatal experience.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable, fun and motivational 50-minute easy run or walk with one minute of post run inspiration.\n\nTotal Experience: 50 Minutes\n\nThis information should be used as a guide only and is not a substitute for advice from a medical professional.  Always consult a medical professional before engaging in a new exercise program and use your judgment for what feels right for you. If you feel faint, experience shortness of breath, dizziness, or related sensations while exercising, stop immediately and seek medical attention as necessary.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/run-with-perri.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Perri",
					body: "Perri Shakes-Drayton is a Track & Field Olympian from Great Britain. Shakes-Drayton has medaled at both the World Champs Outdoors and Indoors as well as the European Indoor and Outdoor Championships. Jane Wake is one of the leading experts on pre and postnatal exercise and training! Coach Cory is the Nike Run Club UK Head Coach.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_SANYA",
		properties: {
			activeGoal: 2400.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_SANYA_ENGB",
			previousIds: ["RUN_WITH_SANYA_ENGB", "RUN_WITH_SANYA"],
		},
		landing: {
			title: "Run With Sanya",
			subtitle: "40 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/76f18bed529b803ebbfd0dd5087c6676/run-with-sanya.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/76f18bed529b803ebbfd0dd5087c6676/run-with-sanya.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Run With Sanya",
				subtitle: "40 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/76f18bed529b803ebbfd0dd5087c6676/run-with-sanya.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Run this 40 minute easy run with Olympic Gold Medalist and American Record Holder Sanya Richards-Ross. You'll hear Sanya's incredible life story and end the run inspired and motivated to be the best version of yourself!",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 40 minute easy run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/run-with-sanya.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Sanya Richards-Ross",
					body: "Sanya Richards-Ross is the 400 meter American Record Holder. She won gold in the 400m at the 2012 London Olympics. Richards-Ross is an entrepreneur, business owner & mother. Sanya is joined on this run by Chelsea Cox, the Nike Running DC Head Coach.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_SHALANE",
		properties: {
			activeGoal: 2700.0,
			autodownload: false,
			goal: 2700.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_SHALANE_ENGB",
			previousIds: ["RUN_WITH_SHALANE_ENGB", "RUN_WITH_SHALANE"],
		},
		landing: {
			title: "Run With\n Shalane",
			subtitle: "45 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ea230622d36d6493009da812b8aa3155/run-with-shalane.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ea230622d36d6493009da812b8aa3155/run-with-shalane.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With\n Shalane",
				subtitle: "45 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ea230622d36d6493009da812b8aa3155/run-with-shalane.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It’s you and Olympic Medalist and NYC Marathon Champion Shalane Flanagan for this 45 minute guided run. You’ll finish inspired, motivated and ready to take on your next challenge.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 45 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run With Shalane",
					url: "https://static.nike.com/ntc-prod/images/7c7bf0aab2aceacc85a4d7da6105e649/run-with-shalane.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-shalane/pl.bffaa56f6d7e402992a07204304267aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/7tnXSTcfVmztjQShPqmgEB",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Shalane Flanagan",
					body: "Shalane Flanagan is an Olympic Silver Medalist, American Record Holder and the 2017 NYC Marathon Champion. She is joined by Nike Running Global Head Coach Chris Bennett.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_SHY",
		properties: {
			activeGoal: 3600.0,
			autodownload: false,
			goal: 3600.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_SHY_ENGB",
			previousIds: ["RUN_WITH_SHY_ENGB", "RUN_WITH_SHY"],
		},
		landing: {
			title: "Run with Shy",
			subtitle: "60 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/676b15cc99f4596f6437b2e6af2a45cb/run-with-shy.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/676b15cc99f4596f6437b2e6af2a45cb/run-with-shy.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run with Shy",
				subtitle: "60 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/676b15cc99f4596f6437b2e6af2a45cb/run-with-shy.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Running is all about resilience and dedication. Amateur boxer Shy LeBeau uses every stride to reach her goals, both in and out of the ring. Hear about the causes close to her heart that will inspire you to take action outside your run.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 60 minute run with 1 minute of post-run guidance and a cool-down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/run-with-shy.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Shy LeBeau",
					body: "Shy LeBeau is Navajo of the Honágháahnii clan and Sans Arc Lakota Sioux of the Cheyenne River tribe. She is an amateur boxer and frequent runner who strives to inspire others to take action to better themselves and the neighborhoods they live in. Outside the ring, her goal is to raise awareness for movements that impact her community. Nike Global Head Coach Chris Bennett joins her on this audio-guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_SLOANE",
		properties: {
			activeGoal: 1920.0,
			autodownload: false,
			goal: 1920.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_SLOANE_ENGB",
			previousIds: ["RUN_WITH_SLOANE_ENGB", "RUN_WITH_SLOANE"],
		},
		landing: {
			title: "Run With Sloane",
			subtitle: "32 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c1d2a90a7771be4e447ea5887f5fca73/run-with-sloane.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c1d2a90a7771be4e447ea5887f5fca73/run-with-sloane.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With Sloane",
				subtitle: "32 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c1d2a90a7771be4e447ea5887f5fca73/run-with-sloane.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Run with 2017 US Open Champion Sloane Stephens on a 32 minute recovery run. Joined by Nike Run Club LA Coach Sally McRae, the pair discuss Sloane’s crazy dreams and her recovery from a career-threatening injury to become a tennis champion.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 32 minute easy run.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-with-sloane.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "XC_WITH_JERRY_SCHUMACHER",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "XC_WITH_JERRY_SCHUMACHER_ENGB",
			previousIds: [
				"XC_WITH_JERRY_SCHUMACHER_ENGB",
				"XC_WITH_JERRY_SCHUMACHER",
			],
		},
		landing: {
			title: "Run XC with Jerry",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/09aa33d7cc75fa759cd094654d6ff655/run-xc-with-jerry.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/09aa33d7cc75fa759cd094654d6ff655/run-xc-with-jerry.png",
			backgroundColor: "#FF8F1C",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF8F1C",
			headerCard: {
				title: "Run XC with Jerry",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/09aa33d7cc75fa759cd094654d6ff655/run-xc-with-jerry.png",
				backgroundColor: "#FF8F1C",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Bowerman Track Club Coach Jerry Schumacher shares what it takes to not only be a great runner but what it takes to build a great team & be a great teammate. You'll end this run a better harrier. He's joined by Nike Running Head Coach Chris Bennett.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 25 minute easy recovery run with 1 minute of post run cool down and inspiration.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-xc-with-jerry.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Jerry Schumacher",
					body: "Jerry Schumacher is the Coach of the Bowerman Track Club. His athletes have won Olympic and World Championship medals, set national records and inspired a generation of new runners. Jerry Schumacher is joined by a former runner of his... Coach Bennett.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SEVEN_MILE_RUN",
		properties: {
			activeGoal: 11266.0,
			autodownload: false,
			goal: 11266.0,
			activityType: "DISTANCE",
			
			previousId: "SEVEN_MILE_RUN_ENGB",
			previousIds: ["SEVEN_MILE_RUN_ENGB", "SEVEN_MILE_RUN"],
		},
		landing: {
			title: "Seven Mile Run",
			subtitle: "7 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/9f644b0312cc1c4d04d7f244c47ec6af/seven-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/9f644b0312cc1c4d04d7f244c47ec6af/seven-mile-run.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "Seven Mile Run",
				subtitle: "7 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/9f644b0312cc1c4d04d7f244c47ec6af/seven-mile-run.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "We don’t know if 7 miles is a lucky distance or not... but we do know we’re lucky to get to run the Seven Mile Run with you! Join NRC Global Head Coach Chris Bennett for this 7-mile/11.26K distance based guided run. Bennett flips the script and turns this run inside out. The result is a better run and a smarter athlete.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and easy seven-mile (just over 11.25K) run. This is a distance based guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/seven-mile-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SEVEN_MINUTE_RUN",
		properties: {
			activeGoal: 420.0,
			autodownload: false,
			goal: 420.0,
			activityType: "DURATION",
			
			previousId: "SEVEN_MINUTE_RUN_ENGB",
			previousIds: ["SEVEN_MINUTE_RUN_ENGB", "SEVEN_MINUTE_RUN"],
		},
		landing: {
			title: "Seven Minute Run",
			subtitle: "7 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c883c13c9d6e8f892abadf5bd9d8b52a/seven-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c883c13c9d6e8f892abadf5bd9d8b52a/seven-minute-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Seven Minute Run",
				subtitle: "7 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c883c13c9d6e8f892abadf5bd9d8b52a/seven-minute-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "You know what’s awesome? A 7 Minute Run... that’s what! It’s you and Coach Bennett, the Nike Running Global Head Coach, for this fun and super positive run. Each and every run you do is an opportunity to move forward. And this run is a run worth celebrating because it’s a run that ends with you 7 minutes better.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and fun 7-minute recovery run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/seven-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SEVEN_MINUTE_SPEED_RUN",
		properties: {
			activeGoal: 885.0,
			autodownload: false,
			goal: 900.0,
			activityType: "SPEED_DURATION",
			
			previousId: "SEVEN_MINUTE_SPEED_RUN_ENGB",
			previousIds: ["SEVEN_MINUTE_SPEED_RUN_ENGB", "SEVEN_MINUTE_SPEED_RUN"],
		},
		landing: {
			title: "Seven Minute Speed Run",
			subtitle: "16 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/59221b81d198ac27d80244d0f742170c/seven-minute-speed-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/59221b81d198ac27d80244d0f742170c/seven-minute-speed-run.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "Seven Minute Speed Run",
				subtitle: "16 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/59221b81d198ac27d80244d0f742170c/seven-minute-speed-run.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This is the Seven Minute Speed Run. After you warm up, Coach Flanagan will guide you through a series of running and recovery intervals. And after seven minutes... you’re done. You’re also better. Stronger. Faster. More experienced. Because it doesn’t always need to take a long time to become a better version of yourself. So, get ready for some fun with the Seven Minute Speed Run.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>7:00 Warm Up<br>\n00:30 10K Pace<br>\n00:30 5K Pace<br>\n00:30 Mile Pace<br>\n1:15 10K Pace<br>\n1:00 5K Pace<br>\n00:45 Mile Pace<br>\n<br>\nRecovery is 30 seconds between all intervals<br>\n<br>\nTotal Experience: 16 minutes</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/seven-minute-speed-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Shalane Flanagan",
					body: "Shalane Flanagan is a coach with the Bowerman Track Club. Coach Flanagan was also one of the greatest distance runners of her generation. She is an Olympic Silver medalist in the 10K as well as a winner of the NYC Marathon. Coach Flanagan still holds numerous American Records. She’s now coaching one of the most successful groups of distance runners in the world with the Bowerman Track Club (BTC).",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SHAKEOUT_RUN_GB",
		properties: {
			activeGoal: 1572.0,
			autodownload: false,
			goal: 1572.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Shakeout Run",
			subtitle: "26 min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/253e465c16664b1aa1d9e24e126d2b29/shakeout-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/253e465c16664b1aa1d9e24e126d2b29/shakeout-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Shakeout Run",
				subtitle: "26 min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/253e465c16664b1aa1d9e24e126d2b29/shakeout-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "What’s the best way to prepare the day before a big race? A shakeout run, of course. Join NRC Coach and Track Mafia founder, Coach Cory for a 26.2 minute easy shakeout run. You’ll warm up, run easy and mentally prepare for everything you need to know for race day. This audio guided run is perfect for the day before any race, from 5k to marathon.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 26 minute easy run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/shakeout-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SIX_MINUTE_RUN",
		properties: {
			activeGoal: 360.0,
			autodownload: false,
			goal: 360.0,
			activityType: "DURATION",
			profiles: [],
			previousId: "SIX_MINUTE_RUN_ENGB",
			previousIds: ["SIX_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Six Minute Run",
			subtitle: "6 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/93d62404-697c-4be5-91e2-0f80fcce2da8/six-minute-run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/93d62404-697c-4be5-91e2-0f80fcce2da8/six-minute-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Six Minute Run",
				subtitle: "6 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/93d62404-697c-4be5-91e2-0f80fcce2da8/six-minute-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>You ready for a great six-minute run? We hope so because that’s exactly what this run with Coach Dora of Nike Running London is. Coach Dora shares her guidance on how to start, continue and finish a run the right way… a better way. You’ll end this run with Coach Dora a better coach and teammate to yourself. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An inspiring and motivational 6-minute easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/six-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dora",
					body: "<p>Coach Dora Atim is a Nike Running London Coach and Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and in doing so inspires others to do the same.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SLOW_DOWN_SPEED_UP",
		properties: {
			activeGoal: 1230.0,
			autodownload: false,
			goal: 1830.0,
			activityType: "SPEED_DURATION",
			
			previousId: "SLOW_DOWN_SPEED_UP_ENGB",
			previousIds: ["SLOW_DOWN_SPEED_UP_ENGB", "SLOW_DOWN_SPEED_UP"],
		},
		landing: {
			title: "Slow Down\n 2 Speed Up",
			subtitle: "33 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a3370035e11a6754141c4138d25b5ef9/slow-down-2-speed-up.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a3370035e11a6754141c4138d25b5ef9/slow-down-2-speed-up.png",
			backgroundColor: "#46B3AC",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#46B3AC",
			headerCard: {
				title: "Slow Down\n 2 Speed Up",
				subtitle: "33 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a3370035e11a6754141c4138d25b5ef9/slow-down-2-speed-up.png",
				backgroundColor: "#46B3AC",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Bring a whole new focus to your fast. Join Headspace co-founder Andy Puddicombe and Nike Global Head Coach Chris Bennett on this 30 minute interval run that helps you slow down your mind to speed up your run.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n3:30 10K pace<br>\n3:30 10K pace<br>\n2:30 5K pace<br>\n2:30 5K pace<br>\n1:30 Mile pace<br>\n1:30 Mile pace<br>\n0:30 Best pace<br>\n<br>\nRecovery intervals will vary between 1 and 2 minutes in duration.<br>\n<br>\nCoach Bennett and Andy will be providing guidance and motivation throughout the run.<br>\n<br>\n33 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Slow Down 2 Speed Up",
					url: "https://static.nike.com/ntc-prod/images/fad28c5086aa041b4aac95bb57b0d4cf/slow-down-2-speed-up.png",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/slow-down-2-speed-up/pl.4a5a2124f37c41a9a93d09e6f610d973",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/6e78FeS1ZOSkiAxTxuQLkV",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SNEAKY_SPEED",
		properties: {
			activeGoal: 975.0,
			autodownload: false,
			goal: 1695.0,
			activityType: "SPEED_DURATION",
			
			previousId: "SNEAKY_SPEED_ENGB",
			previousIds: ["SNEAKY_SPEED_ENGB", "SNEAKY_SPEED"],
		},
		landing: {
			title: "Sneaky Speed",
			subtitle: "30 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/03399fc1fabb654ad154106de412d9c6/sneaky-speed.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/03399fc1fabb654ad154106de412d9c6/sneaky-speed.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Sneaky Speed",
				subtitle: "30 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/03399fc1fabb654ad154106de412d9c6/sneaky-speed.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Join Coach Blue Benadum of NRC Los Angeles on this wild speed run that is the perfect mix of speed and strength. You'll have so much fun running these short intervals with Coach Blue you won't even realize just how fast you're going!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n1:30 5K pace<br>\n0:45 Mile pace<br>\n0:45 Mile pace<br>\n0:45 Mile pace<br>\n1:30 5K pace<br>\n0:45 Mile pace<br>\n0:45 Mile pace<br>\n0:45 Mile pace<br>\n1:30 5K pace<br>\n0:45 Mile pace<br>\n0:45 Mile pace<br>\n0:45 Mile pace<br>\n<br>\nRecovery intervals will be 1 minute.<br>\n<br>\nCoach Blue will be providing guidance and motivation throughout the run.<br>\n<br>\n30 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/sneaky-speed.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Blue",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their own greatest potential.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPEEDURANCE",
		properties: {
			activeGoal: 1740.0,
			autodownload: false,
			goal: 2220.0,
			activityType: "SPEED_DURATION",
			
			previousId: "SPEEDURANCE_ENGB",
			previousIds: ["SPEEDURANCE_ENGB", "SPEEDURANCE"],
		},
		landing: {
			title: "Speed-\n Durance",
			subtitle: "38 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/d5f4fc1ccd96054572eec36085d03c3e/speed-durance.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/d5f4fc1ccd96054572eec36085d03c3e/speed-durance.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Speed-\n Durance",
				subtitle: "38 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/d5f4fc1ccd96054572eec36085d03c3e/speed-durance.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Join Nike Trail Team member Sally McRae for a fun speed run that combines both endurance and speed work. You'll bookend a 10 minute tempo run with 6 sets of 2 minute intervals at your 5K pace. This speed run is a great way to get faster and stronger.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>7:00 Warm up<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n10:00 Tempo run<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n<br>\nRecovery intervals will be 1 minute after each 5K interval and 2 minutes after the tempo run.<br>\n<br>\n38 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/speed-durance.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPEED_PLAY",
		properties: {
			activeGoal: 2340.0,
			autodownload: false,
			goal: 2340.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Speed Play",
			subtitle: "38 Min • Speed Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/eb08187d-4e56-410a-9119-6e255de26865/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/eb08187d-4e56-410a-9119-6e255de26865/image.png",
			backgroundColor: "#dfdfdf",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#dfdfdf",
			headerCard: {
				title: "Speed Play",
				subtitle: "38 Min • Speed Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/eb08187d-4e56-410a-9119-6e255de26865/image.png",
				backgroundColor: "#dfdfdf",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Speed Play is — you guessed it — all about finding your fast. This is an opportunity to build strength and control by starting with a longer interval, running fast, and then doing it all again. Specifically, you’ll be running 2 long & strong intervals, each followed by 3 quick blasts of speed. Just stay focused, present, & work through the fatigue. Don’t worry, we promise it’ll be worth it. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>38 minute speed run starts with a 10 minute warm up before pushing the pace with tempo interval efforts. Wraps up with 5 minutes of easy running for the cool down.<br>\n<br>\nWorkout includes 2 sets of:</p>\n<ul>\n  <li>6 min tempo (at 4-5/10 effort) with 2 min recovery</li>\n  <li>3 x 30 seconds on (at 7/10 effort) with 1 minute recovery</li>\n</ul>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dan",
					body: "<p>Hone in and get ready to work — that's what Coach Dan is all about. He knows what each and every one of you can tap into, and his sessions will make you stronger and faster at any ability.<br>\n<br>\nCoach Dan Fitzgerald is our Boston-based dose of seriousness. He's the founder of Heartbreak.Run, an endurance runner, and surfer who leads thousands of runners from around the world to reach new PRs in the mile through the marathon every year.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPEED_RUN_B4_THE_HALF",
		properties: {
			activeGoal: 960.0,
			autodownload: false,
			goal: 1260.0,
			activityType: "SPEED_DURATION",
			
			previousId: "SPEED_RUN_B4_THE_HALF_ENGB",
			previousIds: ["SPEED_RUN_B4_THE_HALF_ENGB", "SPEED_RUN_B4_THE_HALF"],
		},
		landing: {
			title: "Speed Run B4 The Half",
			subtitle: "22 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/4f74d97c7c9b155c1fa151d6bd2ce077/speed-run-b4-the-half.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/4f74d97c7c9b155c1fa151d6bd2ce077/speed-run-b4-the-half.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "Speed Run B4 The Half",
				subtitle: "22 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/4f74d97c7c9b155c1fa151d6bd2ce077/speed-run-b4-the-half.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Here’s the final Speed Run before your Half Marathon race. Join Coach Bennett for this interval based workout and get your mind and body in the right place to race the right way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n1:00 5K Pace<br>\n2:00 10K Pace<br>\n5:00 Half Marathon Pace<br>\n2:00 10K Pace<br>\n1:00 5K Pace<br>\n<br>\n1:00 Recovery between intervals<br>\n<br>\n~22 minute total experience</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/speed-run-b4-the-half.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPEED_RUN_WITH_ELLIE",
		properties: {
			activeGoal: 600.0,
			autodownload: false,
			goal: 960.0,
			activityType: "SPEED_DURATION",
			profiles: [],
			previousId: "SPEED_RUN_WITH_ELLIE_ENGB",
			previousIds: ["SPEED_RUN_WITH_ELLIE_ENGB", "SPEED_RUN_WITH_ELLIE"],
		},
		landing: {
			title: "Speed Run With Ellie",
			subtitle: "17 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/222a7d8d6351ad6354edcd26262e7e2c/speed-run-with-ellie.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/222a7d8d6351ad6354edcd26262e7e2c/speed-run-with-ellie.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Speed Run With Ellie",
				subtitle: "17 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/222a7d8d6351ad6354edcd26262e7e2c/speed-run-with-ellie.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join one of the most electric footballers on the planet for this fast and fun speed run. Ellie Carpenter has played her way from small town Cowra, Australia to star on the greatest stages in the sport of soccer. She'll inspire you to run your best.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n1:30 10K pace<br>\n1:00 Best pace<br>\n1:00 5K pace<br>\n0:30 Best pace<br>\n0:45 Mile pace<br>\n0:15 Best pace<br>\n<br>\nRecovery intervals will be 1 minute in duration.<br>\n<br>\n17 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/speed-run-with-ellie.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Ellie Carpenter",
					body: "Ellie Carpenter is one of the most exciting young stars in the sport of global football. She is a member off the Australian national team and a defender for the Portland Thorns. She made her professional soccer debut at the age of 15.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPEED_RUN_WITH_JES",
		properties: {
			activeGoal: 1437.0,
			autodownload: false,
			goal: 1437.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Speed Run With Jes",
			subtitle: "30 Min • Speed Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/c7dc8ed8-85f6-431d-9ff0-7a7339745122/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/c7dc8ed8-85f6-431d-9ff0-7a7339745122/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Speed Run With Jes",
				subtitle: "30 Min • Speed Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/c7dc8ed8-85f6-431d-9ff0-7a7339745122/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Speed is an important tool in every runner’s toolkits. This speed workout will give runners a chance to put it all together to build consistency and to build speed. It’s all about going faster. Emphasis on the -er.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>25 minutes of total running broken up by a 5-minute warm up, 20 minutes over three varying speeds and a 3-minute cool down. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach and Talent",
					body: "<p>With a dynamic brand of coaching that will keep you on your toes, Brooklyn-based Coach Jes Woods is here to help each runner find their own fun, sustainable running practice they’ll be excited to keep for the long run. You can get serious results without being too serious, and Coach Jes will show you how. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPEED_RUN_WITH_SANYA",
		properties: {
			activeGoal: 930.0,
			autodownload: false,
			goal: 1680.0,
			activityType: "SPEED_DURATION",
			
			previousId: "SPEED_RUN_WITH_SANYA_ENGB",
			previousIds: ["SPEED_RUN_WITH_SANYA_ENGB", "SPEED_RUN_WITH_SANYA"],
		},
		landing: {
			title: "Speed Run With Sanya",
			subtitle: "30 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/00c35712ce1a160d8a58917e2cc3e5c7/speed-run-with-sanya.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/00c35712ce1a160d8a58917e2cc3e5c7/speed-run-with-sanya.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Speed Run With Sanya",
				subtitle: "30 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/00c35712ce1a160d8a58917e2cc3e5c7/speed-run-with-sanya.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Olympic Champion Sanya Richards-Ross needed to be strong & fast to become the worlds best 400m runner. You'll work on both speed (mile pace & best pace) & strength (5K pace) during this fun speed run with Sanya & Nike Running D.C. Coach Chelsea Cox.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n2:00 5K pace<br>\n1:00 Mile pace<br>\n0:15 Best pace<br>\n0:15 Best pace<br>\n2:00 5K pace<br>\n1:00 Mile pace<br>\n0:15 Best pace<br>\n0:15 Best pace<br>\n2:00 5K pace<br>\n1:00 Mile pace<br>\n0:15 Best pace<br>\n0:15 Best pace<br>\n<br>\nRecovery intervals range from 30 seconds to 2 minutes in duration.<br>\n<br>\nSanya Richards-Ross and Coach Cox will be providing guidance and motivation throughout the speed run.<br>\n<br>\n30 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/speed-run-with-sanya.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Sanya Richards-Ross",
					body: "Sanya Richards-Ross is the 400 meter American Record Holder. She won gold in the 400m at the 2012 London Olympics. Richards-Ross is an entrepreneur, business owner & mother. Sanya is joined on this run by Chelsea Cox, the Nike Running DC Head Coach.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPEEDY_SMILES",
		properties: {
			activeGoal: 1852.0,
			autodownload: false,
			goal: 1852.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Speedy Smiles",
			subtitle: "30 Min • Fartlek Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/525dbfc1-ce58-41f8-9358-6f9de1ec8c3b/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/525dbfc1-ce58-41f8-9358-6f9de1ec8c3b/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Speedy Smiles",
				subtitle: "30 Min • Fartlek Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/525dbfc1-ce58-41f8-9358-6f9de1ec8c3b/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Running is supposed to be fun, right?! In Speedy (S)miles, you’ll play with small bouts of speed followed by dynamic recovery in a spontaneous fashion, pushing your paces while maintaining a sustained level of fun and positivity. Take this workout on the road, trail, track or treadmill—wherever you want to run— just don’t forget to bring your smile.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>30 min fartlek run with 10 min warm up and 10 min cool down.<br>\n</p>\n<p>• 10 min fartlek:</p>\n<p>• 45 sec on/45 sec recovery</p>\n<p>• 60 sec on/60 sec recovery</p>\n<p>• 90 sec on/90 sec recovery</p>\n<p>• 60 sec on/60 sec recovery</p>\n<p>• 45 sec on/45 sec recovery</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "Meet Coach Sashah",
					body: "<p>For Coach Sashah Handal, it's all about finding balance and treating our bodies with the kindness they deserve. The NYC-based Nike Running Coach focuses on building healthy fitness habits we can use day in and day out. Coach Sashah will help you find fitness goals that work for you and always make time to celebrate the little wins along the way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPICY_SPEED_III",
		properties: {
			activeGoal: 1590.0,
			autodownload: false,
			goal: 1590.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Spicy Speed III",
			subtitle: "29 Min • Tabata Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/892c6af8-b852-4b02-aec1-46edeab57024/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/892c6af8-b852-4b02-aec1-46edeab57024/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Spicy Speed III",
				subtitle: "29 Min • Tabata Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/892c6af8-b852-4b02-aec1-46edeab57024/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Coach Bec is bringing the heat with the third installment of her Spicy Speed series, the final spice! This run uses the traditional Tabata format of the 2:1 work to recovery ratio and delivers a quick, yet highly effective workout. Interval blocks are perfect for any runner looking to take it up a notch. If you’ve already challenged yourself with Spicy Speed I and II, welcome back! If you haven’t, crank up the heat with those first. You’re in for a treat with this 29 minute session of spicy sprints.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>29 min Tabata run with 5 min jogging warm up and a 5 min cool down.<br>\n</p>\n<ul>\n  <li>5 min warm up</li>\n  <li>3 sets of 8x30 second intervals with 10 seconds of recovery at an all out effort (21 min total work)</li>\n  <li>5 min cool down</li>\n</ul>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bec",
					body: "<p>Knowledge is power. But when you run with Coach Bec, that knowledge turns into extra miles per hour. A native Australian now based in LA, Bec Wilcock is a trainer and endurance athlete who knows that tackling any challenge—whether it’s your first run or your tenth marathon—starts with understanding yourself. With an attention to detail and a sense of adventure, Coach Bec helps you go farther and get there smarter.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPICY_SPEED_II_WITH_BEC",
		properties: {
			activeGoal: 1259.0,
			autodownload: false,
			goal: 1259.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Spicy Speed II With Bec",
			subtitle: "23 Min • Speed Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/0bf86457-6b07-4bbd-bad0-30c203a3ac57/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/0bf86457-6b07-4bbd-bad0-30c203a3ac57/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Spicy Speed II With Bec",
				subtitle: "23 Min • Speed Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/0bf86457-6b07-4bbd-bad0-30c203a3ac57/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>How can you make workouts extra challenging, and take something more from them? In our second Spicy Speed session with Coach Bec, we’ll up the ante with a another take at Tabata Interval Training.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>23 minutes of total running broken up by a 7-minute warm up, 11 minutes of varying speeds and a 5 minute cool-down.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach and Talent",
					body: "<p>Knowledge is power. But when you run with Coach Bec, that knowledge turns into extra miles per hour. A native Australian now based in LA, Bec Wilcock is a trainer and endurance athlete who knows that tackling any challenge – whether it’s your first run or your tenth marathon – starts with understanding yourself. With an attention to detail and a sense of adventure, Coach Bec helps you go farther, and get there smarter. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPICY_SPEED_RUN_WITH_BEC",
		properties: {
			activeGoal: 888.0,
			autodownload: false,
			goal: 888.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Spicy Speed I With Bec",
			subtitle: "17 Min • Speed Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/b2782df1-48a2-4107-88d1-5500b55ddf91/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/b2782df1-48a2-4107-88d1-5500b55ddf91/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Spicy Speed I With Bec",
				subtitle: "17 Min • Speed Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/b2782df1-48a2-4107-88d1-5500b55ddf91/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>How can you make workouts extra challenging, and take something more from them? In our first Spicy Speed session with Coach Bec, we’ll work on Sprint Interval Training with the traditional Tabata Method to get the most out of a short timeframe.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>17 minutes of total running broken up by an 8-minute warm up, 4 minutes of varying speeds and 5 minutes of a cool down.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach and Talent",
					body: "<p>Knowledge is power. But when you run with Coach Bec, that knowledge turns into extra miles per hour. A native Australian now based in LA, Bec Wilcock is a trainer and endurance athlete who knows that tackling any challenge – whether it’s your first run or your tenth marathon – starts with understanding yourself. With an attention to detail and a sense of adventure, Coach Bec helps you go farther, and get there smarter.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPOOKY_SPEED_RUN",
		properties: {
			activeGoal: 1539.0,
			autodownload: false,
			goal: 1539.0,
			activityType: "SPEED_DURATION",
			
			previousId: "SPOOKY_SPEED_RUN_ENGB",
			previousIds: ["SPOOKY_SPEED_RUN_ENGB"],
		},
		landing: {
			title: "Spooky Speed Run",
			subtitle: "27 Min • Speed Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/e6f678af-29bc-43d8-8b94-de54321eb2ba/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/e6f678af-29bc-43d8-8b94-de54321eb2ba/image.png",
			backgroundColor: "#E5623C",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#E5623C",
			headerCard: {
				title: "Spooky Speed Run",
				subtitle: "27 Min • Speed Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/e6f678af-29bc-43d8-8b94-de54321eb2ba/image.png",
				backgroundColor: "#E5623C",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Welcome to the Spooky Speed Run! You may be wondering how long the intervals are… or how fast you’ll need to run… you may be wondering how long the recovery will be… but no one knows! Actually, Coach Bennett knows but he’s only going to tell you how fast you need to run and when it’s time to recover and start running again. Everything else… is a mystery! Get ready to work on running in the moment with the Spooky Speed Run!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A five-minute warm up followed by… did you really think we were going to spill the beans? No way! You’ll be guided through this super fun and surprising (and spooky) speed run without knowing exactly how long each interval is. You will be told the pace and effort but that’s it. How long until the end of each interval? There’s no way to know. (Unless Daniel the Engineer gives hints.)</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SPRINTERVALS",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "SPEED_DURATION",
			profiles: [],
		},
		landing: {
			title: "Sprintervals",
			subtitle: "20 Min • Speed Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/e6f678af-29bc-43d8-8b94-de54321eb2ba/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/e6f678af-29bc-43d8-8b94-de54321eb2ba/image.png",
			backgroundColor: "#E5623C",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#E5623C",
			headerCard: {
				title: "Sprintervals",
				subtitle: "20 Min • Speed Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/e6f678af-29bc-43d8-8b94-de54321eb2ba/image.png",
				backgroundColor: "#E5623C",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Sprintervals... that’s the name. Sprintervals. And we’ll let you know that this is not false advertising because we are going to run fast today! You can call it sprinting... you can call it flying or rolling or rocking or zooming or whatever else you want to call it. But it is most definitely all about using and celebrating your speed today. Coach Manni of Nike Running London will guide you through this fast and fun speed run that has you alternating between your Mile/1500 pace and your Best Pace. Time flies today. And so will you!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n<br>\n:30 @ Mile/1500m Pace<br>\n:15 @ Best Pace<br>\n:45 @ Mile/1500m Pace<br>\n:15 @ Best Pace<br>\n1:00 @ Mile/1500m Pace<br>\n:15 @ Best Pace<br>\n:45 @ Mile/1500m Pace<br>\n:15 @ Best Pace<br>\n:30 @ Mile/1500m Pace<br>\n:15 @ Best Pace<br>\n:45 @ 5K Pace <br>\n<br>\nRecovery will range between 30 seconds and one minute between running intervals.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "Coach Manni",
					body: "<p>Manni Ovola is a UK Nike Run Club Coach and physiotherapist who treats all types of runners and is mad about running himself. He believes by helping people understand their bodies, he can bring out the most in them.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
