export const runs = [
	{
		id: "WEEK_7",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 7",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 7",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 7 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_8",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 8",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 8",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 8 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_9",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 9",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 9",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 9 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WHATS_YOUR_WHY",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "What's Your Why",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/b5fe5f98-e609-427d-b767-e691d005ee92/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/b5fe5f98-e609-427d-b767-e691d005ee92/image.png",
			backgroundColor: "#E0738A",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#E0738A",
			headerCard: {
				title: "What's Your Why",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/b5fe5f98-e609-427d-b767-e691d005ee92/image.png",
				backgroundColor: "#E0738A",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Get ready for 30 minutes of self-exploration and self-talk with Nike Run Coach Diljeet Taylor. During this easy run you’ll learn how to be your own best advocate/cheerleader. You’ll practice affirmations and get to know what drives you to be a better runner today than you were yesterday.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An easy 30 min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WILD_RUN_WITH_BEC",
		properties: {
			activeGoal: 2180.0,
			autodownload: false,
			goal: 2180.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Wild Run With Bec",
			subtitle: "40 Min • Trail Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/ae299667-f83b-480f-8ef0-056999f7a6e2/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/ae299667-f83b-480f-8ef0-056999f7a6e2/image.png",
			backgroundColor: "#dfdfdf",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#dfdfdf",
			headerCard: {
				title: "Wild Run With Bec",
				subtitle: "40 Min • Trail Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/ae299667-f83b-480f-8ef0-056999f7a6e2/image.png",
				backgroundColor: "#dfdfdf",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This run brings the excitement and passion from trail running to your feet. Coach Bec takes us off the concrete and into the mountains to run wild or at least makes us feel that way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>40 minutes of total running broken up by a 5-minute warm up, 30 minutes of varying speeds to simulate trails and a 5-minute cool down.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About The Coach",
					body: "<p>Knowledge is power. But when you run with Coach Bec, that knowledge turns into extra miles per hour. A native Australian now based in LA, Bec Wilcock is a trainer and endurance athlete who knows that tackling any challenge – whether it’s your first run or your tenth marathon – starts with understanding yourself. With an attention to detail and a sense of adventure, Coach Bec helps you go farther, and get there smarter.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WORST_ADVICE_EVER_RUN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "WORST_ADVICE_EVER_RUN_ENGB",
			previousIds: ["WORST_ADVICE_EVER_RUN_ENGB", "WORST_ADVICE_EVER_RUN"],
		},
		landing: {
			title: "Worst Advice Ever Run",
			subtitle: "30 min • Easy Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/2d2fbface042ed019c1e46230e7c7240/worst-advice-ever-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/2d2fbface042ed019c1e46230e7c7240/worst-advice-ever-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Worst Advice Ever Run",
				subtitle: "30 min • Easy Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/2d2fbface042ed019c1e46230e7c7240/worst-advice-ever-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It’s important to get good advice when it comes to running. But sometimes bad advice can be helpful too… as long as you know it’s bad advice. Join Nike Running Global Head Coach Chris Bennett for this easy 30-minute run as he shares some of the worst advice he’s ever heard about running and why that terrible advice is just so awful. You’ll learn, laugh and leave the run a better athlete, teammate and coach.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and inspirational 30-minute easy run.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/worst-advice-ever-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
