export const runs = [
	{
		id: "BEST_ADVICE_EVER",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "BEST_ADVICE_EVER_ENGB",
			previousIds: ["BEST_ADVICE_EVER_ENGB", "BEST_ADVICE_EVER"],
		},
		landing: {
			title: "Best Advice Ever Run",
			subtitle: "25 min • Easy Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/bbfc4e796100d5ea2b044694dbfd86ae/best-advice-ever-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/bbfc4e796100d5ea2b044694dbfd86ae/best-advice-ever-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Best Advice Ever Run",
				subtitle: "25 min • Easy Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/bbfc4e796100d5ea2b044694dbfd86ae/best-advice-ever-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The best advice is advice you can take advantage of… advice that can help you… advice you can use and share with others. Join Nike Running Global Head Coach Chris Bennett for this relaxed 25-minute run as he shares some of the best advice he’s got about running. Of course, this guided run is about running… and it’s not about running.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A fun and inspirational 25-minute easy run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/best-advice-ever-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "BEST_RUN_EVER",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Best Run Ever",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/0c59fb34-892d-468a-bfad-50e766ecd4a2/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/0c59fb34-892d-468a-bfad-50e766ecd4a2/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Best Run Ever",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/0c59fb34-892d-468a-bfad-50e766ecd4a2/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Could this be your best run ever? Maybe! One thing for sure is that this is the Best Run Ever guided run with Nike Running Global Head Coach, Coach Bennett. So, get ready for an inspirational and motivational 20-minute easy run where Coach will guide you through a conversation about the many, many different ways we can and should define the word “best” and our best runs. And who knows… maybe this run ends up being one of your best runs ever!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A motivational, mindful and inspirational 20-minute easy run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "BESTS_OF_THE_YEAR",
		properties: {
			activeGoal: 2400.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Bests Of The Year Run",
			subtitle: "40 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/794bcdda8ae68e345004592460ba459a/bests-of-the-year-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/794bcdda8ae68e345004592460ba459a/bests-of-the-year-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Bests Of The Year Run",
				subtitle: "40 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/794bcdda8ae68e345004592460ba459a/bests-of-the-year-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Whether it’s the end of the past year or the beginning of a new year... the calendar year or a rolling year... there are best moments and meals and there are best laughs and best learnings. There are best wins and best losses. Every year we get a year of bests. Join Nike Running Global Head Coach for a 40-minute easy run that guides you through your own year of bests. Coach Bennett will ask you for your best... best teacher, mistakes, wins, friends and so much more. You’ll rewind your past year as you run yourself forward into the future and a year of better bests.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and inspirational 40-minute recovery run with one minute of post run motivation.\n\nTotal Experience: 40 Minutes",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/bests-of-the-year-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "BETRUE_EQUALITY",
		properties: {
			activeGoal: 1270.0,
			autodownload: false,
			goal: 1270.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "BeTrue",
			subtitle: "21 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/bb7f5b307ce639da7265e81b1fabbcb4/betrue.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/bb7f5b307ce639da7265e81b1fabbcb4/betrue.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "BeTrue",
				subtitle: "21 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/bb7f5b307ce639da7265e81b1fabbcb4/betrue.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "BETRUE celebrates the pursuit of equality for all athletes. Spend your run with elite triathlete Chris Mosier and Chicago Nike Running Coach Emily Hutchins. During your 21 minute recovery run, Chris will share his story as the first openly transgender athlete to make a US National Team.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 21 minute easy run with 30 seconds of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/betrue.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Chris Mosier",
					body: "Chris Mosier is a five-time member of Team USA, silver medalist in the Gay Games, and a barrier-breaking athlete with many firsts to his name. As he continues his impressive career as an openly transgender Team USA duathlete, he is a champion for equality in sport at all levels of play.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HS_BIG_DAY_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "HS_BIG_DAY_RUN_ENGB",
			previousIds: ["HS_BIG_DAY_RUN_ENGB", "HS_BIG_DAY_RUN"],
		},
		landing: {
			title: "Big Day Run",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/d68fc6c991b13ece3d45b2ed050f066b/big-day-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/d68fc6c991b13ece3d45b2ed050f066b/big-day-run.png",
			backgroundColor: "#F3E6D4",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#F3E6D4",
			headerCard: {
				title: "Big Day Run",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/d68fc6c991b13ece3d45b2ed050f066b/big-day-run.png",
				backgroundColor: "#F3E6D4",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Big day soon? Race? Presentation? Exam? We know it can be scary and make you nervous. Join Andy Puddicombe of Headspace and NRC Global Head Coach Chris Bennett, the on this 25 minute run and learn how big days can also be exciting, positive & empowering.",
					titleColor: "#FFFFFF",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy 25 minute run with 1 minute of post run inspiration and cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/big-day-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#403D44",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#FFFFFF",
					backgroundColor: "#403D44",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "BIG_TREADMILL_RUN",
		properties: {
			activeGoal: 3600.0,
			autodownload: false,
			goal: 3600.0,
			activityType: "DURATION",
			
			previousId: "BIG_TREADMILL_RUN_ENGB",
			previousIds: ["BIG_TREADMILL_RUN_ENGB", "BIG_TREADMILL_RUN"],
		},
		landing: {
			title: "Big Treadmill Run",
			subtitle: "60 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/bedbbdddccfde2b060c962cce9564ab3/big-treadmill-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/bedbbdddccfde2b060c962cce9564ab3/big-treadmill-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Big Treadmill Run",
				subtitle: "60 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/bedbbdddccfde2b060c962cce9564ab3/big-treadmill-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "One hour. 60 minutes. Just you and the treadmill. Well, actually, it’s you and the treadmill and Coach Blue Benadum of NRC Los Angeles for this one. Get ready to roll through an excellent run with Coach Blue. He’ll make sure the hour on the treadmill is an hour well spent. This easy recovery run proves that the treadmill does not need to be a dreadmill.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and relaxed 60-minute run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/big-treadmill-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Benadum",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their own greatest potential.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HS_BREAKING_THROUGH_BARRIERS",
		properties: {
			activeGoal: 1860.0,
			autodownload: false,
			goal: 1860.0,
			activityType: "DURATION",
			
			previousId: "HS_BREAKING_THROUGH_BARRIERS_ENGB",
			previousIds: [
				"HS_BREAKING_THROUGH_BARRIERS_ENGB",
				"HS_BREAKING_THROUGH_BARRIERS",
			],
		},
		landing: {
			title: "Breaking Through Barriers",
			subtitle: "31 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/275b43cbffeee969dd1a8f7bac9f105a/breaking-through-barriers.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/275b43cbffeee969dd1a8f7bac9f105a/breaking-through-barriers.png",
			backgroundColor: "#46B3AC",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#46B3AC",
			headerCard: {
				title: "Breaking Through Barriers",
				subtitle: "31 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/275b43cbffeee969dd1a8f7bac9f105a/breaking-through-barriers.png",
				backgroundColor: "#46B3AC",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Becoming better is a challenge with breakthroughs and barriers along the way. Join Andy Puddicombe of Headspace and NRC Global Head Coach Chris Bennett on this 31 minute run. Learn to deal with both, real and imagined barriers, on your way to breaking through.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 31 minute recovery run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/breaking-through-barriers.png",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "BREATHING_IN_MOTION",
		properties: {
			activeGoal: 475.0,
			autodownload: false,
			goal: 475.0,
			activityType: "SPEED_DURATION",
			profiles: [],
		},
		landing: {
			title: "Breathing In Motion",
			subtitle: "10 Min • Walk",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/0771c166-7e09-4db3-bde7-8ce7b7b631df/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/0771c166-7e09-4db3-bde7-8ce7b7b631df/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Breathing In Motion",
				subtitle: "10 Min • Walk",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/0771c166-7e09-4db3-bde7-8ce7b7b631df/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Ever wondered, “How should I be breathing during a walk or run?” Well, Breathing in Motion is Coach Sashah’s answer to that question. In this engaging 10-minute walk-run interval workout, we’ll be mixing speeds and learning the perfect breath cadence for each effort level. This is a fantastic workout and a great chance to unlock some key skills – all while fitting perfectly into your busy schedule. You’ll walk away feeling more comfortable with every step and excited to keep the momentum going. Let’s get moving!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Walk Details",
					body: "<p>A 10-minute walk-run interval workout with varying effort levels.</p>\n<ul>\n  <li>4 blocks of 1 minute intervals with 30 seconds of recovery</li>\n</ul>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/image.png",
					titleColor: "#ffffff",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "Meet Coach Sashah",
					body: "<p>For Coach Sashah Handal, it's all about finding balance and treating our bodies with the kindness they deserve. The NYC-based Nike Running Coach focuses on building healthy fitness habits we can use day in and day out. Coach Sashah will help you find fitness goals that work for you and always make time to celebrate the little wins along the way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "BRING_IT_DOWN",
		properties: {
			activeGoal: 1260.0,
			autodownload: false,
			goal: 1260.0,
			activityType: "SPEED_DURATION",
			
			previousId: "BRING_IT_DOWN_ENGB",
			previousIds: ["BRING_IT_DOWN_ENGB", "BRING_IT_DOWN"],
		},
		landing: {
			title: "Bring It Down",
			subtitle: "22 Min • Tempo Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a0af58185779a74301df2c93d4ba0ae0/bring-it-down.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a0af58185779a74301df2c93d4ba0ae0/bring-it-down.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "DEFAULT",
			metricVoiceovers: "DEFAULT",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Bring It Down",
				subtitle: "22 Min • Tempo Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a0af58185779a74301df2c93d4ba0ae0/bring-it-down.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Getting uncomfortable never felt so good! Join Coach Cory of Nike Running UK for this progressively paced tempo run. You’ll start at your recovery run pace for 5 minutes and then run straight into 4 minutes at your 10K effort, 3 minutes at your 5k effort, 2 minutes at your Mile effort and then finish the 20 minute tempo run with one minute at your Best effort.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n17:00 Progressive Tempo Run<br>\n<br>\n22:00 Total Experience</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/bring-it-down.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "BUILDING_BLOCKS",
		properties: {
			activeGoal: 2040.0,
			autodownload: false,
			goal: 2040.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Building Blocks",
			subtitle: "34 Min • Interval Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/8315539b-cf50-4150-b9e8-42bae0ef7c21/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/8315539b-cf50-4150-b9e8-42bae0ef7c21/image.png",
			backgroundColor: "#dfdfdf",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#dfdfdf",
			headerCard: {
				title: "Building Blocks",
				subtitle: "34 Min • Interval Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/8315539b-cf50-4150-b9e8-42bae0ef7c21/image.png",
				backgroundColor: "#dfdfdf",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This run is all about the power of consistent work. In Building Blocks with Coach Dan, you’ll be challenged to keep your head down and embrace steady interval repeats. The pace you start at—which should feel slightly uncomfortable— is the pace you’ll hold. Learn to ride the line. You’ve got this.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>34 minute of total running kicked off by a 5 minute warm up and 5 minute stretch. The workout includes 10 intervals of 1 minute on, 1 minute off, and you'll wrap up with a 5 minute cool down.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dan",
					body: "<p>Hone in and get ready to work — that's what Coach Dan is all about. He knows what each and every one of you can tap into, and his sessions will make you stronger and faster at any ability.<br>\n<br>\nCoach Dan Fitzgerald is our Boston-based dose of seriousness. He's the founder of Heartbreak.Run, an endurance runner, surfer, and leads thousands of a runners from around the world to reach new PRs in the mile through the marathon every year.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "CELEBRATION_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "CELEBRATION_RUN_ENGB",
			previousIds: ["CELEBRATION_RUN_ENGB"],
		},
		landing: {
			title: "Celebration Run",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/1e8161e3-0958-43a8-acaf-ab823d4d9ee4/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/1e8161e3-0958-43a8-acaf-ab823d4d9ee4/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Celebration Run",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/1e8161e3-0958-43a8-acaf-ab823d4d9ee4/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It’s time to celebrate! What are we celebrating? We’re celebrating you and this sport of yours! Come join Coach Bennett, the Nike Running Global Head Coach, for this 25-minute-long party… we mean 25-minute-long easy run. You’ll be cheering yourself on to a better run and ending these 25 minutes as a better teammate, coach, and friend to yourself.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A fun and inspirational 25-minute easy run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "COMEBACK",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Comeback\n Run",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f42acbce80b1adb83c10da83d10aca5f/comeback-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f42acbce80b1adb83c10da83d10aca5f/comeback-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Comeback\n Run",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f42acbce80b1adb83c10da83d10aca5f/comeback-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Have you been away from the starting line for a while? Have you missed some runs? Do you miss running? Join Coach Bennett, the NRC Global Head Coach, for this 15 minute easy run that will inspire you to get back to starting and finishing runs again.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 15 minute recovery run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Comeback Run",
					url: "https://static.nike.com/ntc-prod/images/6f555cf342882b55e4c165c4ffe920b5/comeback-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/comback-run/pl.faad36850d9f4f978ca1126274cdf2c7",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/6pbWXdEKkSq5rgITu8AtHI",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "CORE_COORDINATION_WITH_BEC",
		properties: {
			activeGoal: 1839.0,
			autodownload: false,
			goal: 1839.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Core & Coordination With Bec",
			subtitle: "28 Min • Run & Train: Core",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/ec78a386-7425-47ff-b012-ba20f78a55ce/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/ec78a386-7425-47ff-b012-ba20f78a55ce/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Core & Coordination With Bec",
				subtitle: "28 Min • Run & Train: Core",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/ec78a386-7425-47ff-b012-ba20f78a55ce/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This run connects core and coordination exercises with running to find physical and mental balance through a varied workout. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>28 minutes of total work with everchanging running and core exercises. Can be completed on a treadmill or outside running, giving yourself space to pause runs for completing static exercises.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About The Coach",
					body: "<p>Knowledge is power. But when you run with Coach Bec, that knowledge turns into extra miles per hour. A native Australian now based in LA, Bec Wilcock is a trainer and endurance athlete who knows that tackling any challenge – whether it’s your first run or your tenth marathon – starts with understanding yourself. With an attention to detail and a sense of adventure, Coach Bec helps you go farther, and get there smarter. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "CRANK_AND_CRUISE",
		properties: {
			activeGoal: 1830.0,
			autodownload: false,
			goal: 1860.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Crank & Cruise",
			subtitle: "32 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/8db0047ea0344350484d5bf6752ae10c/crank-cruise.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/8db0047ea0344350484d5bf6752ae10c/crank-cruise.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "Crank & Cruise",
				subtitle: "32 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/8db0047ea0344350484d5bf6752ae10c/crank-cruise.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Get out fast… then settle in. Crank & Cruise! Join Coach Cory Wharton-Malcom of Nike London for this exciting Speed Run. You’ll start by doing 3 x 4:00. Each of the intervals will begin with you running at your fast and fun Mile pace for 30 seconds. You’ll shift gears to your 10K pace for the last 3:30 of the interval. Crank & Cruise ends with you running 4 x 1:00 at your 5K pace. You’ll find that groove of yours and run in it.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n3 x 4:00 Split Interval (0:30 Mile Pace straight into 3:30 10K Pace)<br>\n4 x 1:00 5K Pace<br>\n<br>\n~32:00 Total Experience</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/crank-cruise.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He co-founded Track Mafia Track Club and hosts the Tub Hub podcast. He’s also known as @bitbeefy and the ‘Chief Vibes Man’ as he brings such good energy to everyone he meets. Whether Coach Cory is working with his teammates or young Londoners, he leaves everyone wanting to run again!",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "DEUCES",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 2220.0,
			activityType: "SPEED_DURATION",
			
			previousId: "DEUCES_ENGB",
			previousIds: ["DEUCES_ENGB", "DEUCES"],
		},
		landing: {
			title: "Deuces",
			subtitle: "38 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/b02afd3a6879ec09b12ee13560977aec/deuces.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/b02afd3a6879ec09b12ee13560977aec/deuces.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Deuces",
				subtitle: "38 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/b02afd3a6879ec09b12ee13560977aec/deuces.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>When you combine a great workout with a great athlete and coach you get Deuces. Join Coach Blue Benadum of NRC LA for this Speed Run. You’ll take on 2 minute intervals and take away more strength and speed than you started with.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n2:00 5K pace<br>\n<br>\nRecovery intervals will vary between 1 and 2 minutes in duration.<br>\n<br>\nCoach Blue will be providing guidance and motivation throughout the run.<br>\n<br>\n38 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/deuces.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Blue",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their own greatest potential.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "DON'T_STOP!_GO!",
		properties: {
			activeGoal: 1993.0,
			autodownload: false,
			goal: 1202.0,
			activityType: "SPEED_DURATION",
			
			previousId: "DON'T_STOP!_GO!_ENGB",
			previousIds: ["DON'T_STOP!_GO!_ENGB"],
		},
		landing: {
			title: "Don't Stop! Go!",
			subtitle: "20 Min • Treadmill Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/05071a5c-09b7-463a-9466-e634af33e057/don-t_stop-_go.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/05071a5c-09b7-463a-9466-e634af33e057/don-t_stop-_go.png",
			backgroundColor: "#4C5AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4C5AFF",
			headerCard: {
				title: "Don't Stop! Go!",
				subtitle: "20 Min • Treadmill Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/05071a5c-09b7-463a-9466-e634af33e057/don-t_stop-_go.png",
				backgroundColor: "#4C5AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Get ready to have some fun on your treadmill. Yes. You read that right. We said fun and treadmill in the same sentence. NRC North America Coach Chelsea Cox will guide you on this great 9:00 fartlek speed run for the treadmill that starts with a 6:00 warm up and ends with a guided 5:00 cool down for a total running time of 20 minutes.<br>\n<br>\nYou’ll alternate between hard and easy running while Coach Cox gives you tips and inspiration so you can step off the treadmill with a smile knowing you can get better and have fun doing it.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>6:00 Warmup<br>\nRun 9:00 Fartlek (alternates between hard and easy efforts)<br>\n5:00 Cool Down</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/don-t_stop-_go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "<p>Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently a Nike Run Club North America Coach based out of North Carolina.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "DONT_WANT_TO_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "DONT_WANT_TO_RUN_ENGB",
			previousIds: ["DONT_WANT_TO_RUN_ENGB", "DONT_WANT_TO_RUN"],
		},
		landing: {
			title: "Don't Wanna Run Run",
			subtitle: "25 Min • Easy Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/917811446d7960e3dae1688427a7a80d/don-t-wanna-run-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/917811446d7960e3dae1688427a7a80d/don-t-wanna-run-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Don't Wanna Run Run",
				subtitle: "25 Min • Easy Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/917811446d7960e3dae1688427a7a80d/don-t-wanna-run-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "So, you don't want to run? We hear you! And we're here for you! All you need to do is press start and we'll take care of the rest. Coach Bennett will be with you every stride of this guided 25 minute run. Let's go!",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 25 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Don't Wanna Run Run",
					url: "https://static.nike.com/ntc-prod/images/bc363137e055903aa59f057bca41075a/don-t-wanna-run-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/dont-want-to-run-run/pl.04fcc81a0aa7473cb9c0a92e89a72598",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/3KNQbQf4NVIv0NLiPNy0nR",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "EASY_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "EASY_RUN_ENGB",
			previousIds: ["EASY_RUN_ENGB", "EASY_RUN"],
		},
		landing: {
			title: "Easy Run",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5d98c2cff36f78c80b70bcd295994edd/easy-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5d98c2cff36f78c80b70bcd295994edd/easy-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Easy Run",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5d98c2cff36f78c80b70bcd295994edd/easy-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This is the most important run you can do. The run you’ll do more than any other run. It’s the run that helps you recover from and get ready for hard efforts. This run always ends with you better. Easy to run but not always easy to do... it’s the Easy Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#4c5aff",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 25 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#4c5aff",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/easy-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#4c5aff",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#4c5aff",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "EASY_RUN_WITH_JES_WOODS",
		properties: {
			activeGoal: 1630.0,
			autodownload: false,
			goal: 1630.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Easy Run With Jes",
			subtitle: "30 Min • Easy Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/b7f49185-1296-4575-9b8f-89106b0f96c6/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/b7f49185-1296-4575-9b8f-89106b0f96c6/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Easy Run With Jes",
				subtitle: "30 Min • Easy Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/b7f49185-1296-4575-9b8f-89106b0f96c6/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Instead of focusing on the numbers – pace, distance, time – this run focuses on consistency, progress, and building a toolkit that you can use whether you’re a beginner or a seasoned runner.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>30 minutes of total running broken up by fun conversations and instruction from Coach Jes.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/image.png",
					titleColor: "#ffffff",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach and Talent",
					body: "<p>With a dynamic brand of coaching that will keep you on your toes, Brooklyn-based Coach Jes Woods is here to help each runner find their own fun, sustainable running practice they’ll be excited to keep for the long run. You can get serious results without being too serious, and Coach Jes will show you how.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "EIGHT_MILE_RUN",
		properties: {
			activeGoal: 12878.0,
			autodownload: false,
			goal: 12878.0,
			activityType: "DISTANCE",
			
			previousId: "EIGHT_MILE_RUN_ENGB",
			previousIds: ["EIGHT_MILE_RUN_ENGB", "EIGHT_MILE_RUN"],
		},
		landing: {
			title: "Eight Mile Run",
			subtitle: "8 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a5bba2f44e41a7fc97e98c520345344e/eight-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a5bba2f44e41a7fc97e98c520345344e/eight-mile-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Eight Mile Run",
				subtitle: "8 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a5bba2f44e41a7fc97e98c520345344e/eight-mile-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "8 miles is 12,875 meters. Sounds magical, right? Because it is! Join Coach Bennett on this distance based guided run. You’ll learn that duration & distance isn’t what makes a run magical. It’s what we do during those minutes & meters that makes a run magic.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and easy 8 Mile (or roughly 13K Run).\nThis is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/eight-mile-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "EIGHT_MINUTE_RUN",
		properties: {
			activeGoal: 480.0,
			autodownload: false,
			goal: 480.0,
			activityType: "DURATION",
			
			previousId: "EIGHT_MINUTE_RUN_ENGB",
			previousIds: ["EIGHT_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Eight Minute Run",
			subtitle: "8 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/cb62c396-3891-48ea-a158-9f6aa95455fa/eight-minute-run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/cb62c396-3891-48ea-a158-9f6aa95455fa/eight-minute-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Eight Minute Run",
				subtitle: "8 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/cb62c396-3891-48ea-a158-9f6aa95455fa/eight-minute-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>You know what’s great? Eight… minutes of running with Nike Running New Zealand Coach Lydia. Take the starting line for this motivational run led by Coach Lydia and you’ll be crossing the finish line ready to celebrate just how far you’ve come. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A fun and comfortable 8-minute easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/eight-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Lydia",
					body: "<p>Join Lydia O’Donnell of NRC New Zealand is an accomplished runner, coach, and wellness advocate. Coach O’Donnell works tirelessly to share the sport the right way with as many people as she can because Coach knows that a better run can lead to a better runner.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ELEVEN_MINUTE_RUN",
		properties: {
			activeGoal: 660.0,
			autodownload: false,
			goal: 660.0,
			activityType: "DURATION",
			profiles: [],
			previousId: "ELEVEN_MINUTE_RUN_ENGB",
			previousIds: ["ELEVEN_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Eleven Minute Run",
			subtitle: "11 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/9c982ad3-9b45-47f7-b9ec-7d43eb8f3cc3/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/9c982ad3-9b45-47f7-b9ec-7d43eb8f3cc3/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Eleven Minute Run",
				subtitle: "11 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/9c982ad3-9b45-47f7-b9ec-7d43eb8f3cc3/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This run goes to eleven… minutes! Join Nike Running London Coach Dora Atim for this relaxed and motivational easy run. Take the starting line with Coach Dora and eleven minutes later you’ll arrive at the end of the run as a better version of yourself.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable 11-minute recovery run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dora",
					body: "<p>Coach Dora Atim is a Nike Running London Coach and Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and in doing so inspires others to do the same.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "EOD_RUN_WITH_HEADSPACE",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "EOD_RUN_WITH_HEADSPACE_ENGB",
			previousIds: ["EOD_RUN_WITH_HEADSPACE_ENGB", "EOD_RUN_WITH_HEADSPACE"],
		},
		landing: {
			title: "End Of Day Run With Headspace",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/bec4aaf65140b4c634cfb269da4953d8/end-of-day-run-with-headspace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/bec4aaf65140b4c634cfb269da4953d8/end-of-day-run-with-headspace.png",
			backgroundColor: "#F3E6D4",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#F3E6D4",
			headerCard: {
				title: "End Of Day Run With Headspace",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/bec4aaf65140b4c634cfb269da4953d8/end-of-day-run-with-headspace.png",
				backgroundColor: "#F3E6D4",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "End your day with a relaxed and restoring run alongside Andy Puddicombe, a former Buddhist monk and the co-founder of Headspace, and Nike Running Global Head Coach Chris Bennett on this 25 minute recovery run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#55505A",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 25 minute relaxed run with 1 minute of post-run guidance and cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#55505A",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run With Headspace",
					url: "https://static.nike.com/ntc-prod/images/5033e66339bd97b48b8b2836045e19f5/end-of-day-run-with-headspace.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#55505A",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-headspace/pl.5599ee1dc0e048bda9d11c65deb6a150",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/5UeYUUQnTy2amoVm6Tbmeb",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "Andy Puddicombe is the co-founder of Headspace and an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#FFFFFF",
					backgroundColor: "#55505A",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ENERGY_WALK_UK",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Energy Walk",
			subtitle: "15 Min - Walk",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/74a436b2-3aad-464c-8646-6f035caea8ef/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/74a436b2-3aad-464c-8646-6f035caea8ef/image.png",
			backgroundColor: "#A373C7",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#A373C7",
			headerCard: {
				title: "Energy Walk",
				subtitle: "15 Min - Walk",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/74a436b2-3aad-464c-8646-6f035caea8ef/image.png",
				backgroundColor: "#A373C7",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Walk Overview",
					body: "<p>Slow pace, big energy. Join Coach Rebekah and Presenter Isla Loba for a fresh convo on wellbeing. We’re talking creativity, collective energy, and sharing positive vibes across London. And we’re diving into the power of connection: the real fuel for feeling good. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Walk Detail",
					body: "<p>Looking at the power of connection, with 3 prompts for self-reflection along the way (in soothing silence, or with your favourite playlist!) </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Energy Walk",
					url: "https://static.nike.com/a/images/w_960,c_limit/ebb4fe35-4c5d-4c79-849d-6992da554dd1/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Body",
					body: "<p>As a Nike yoga teacher, doctor, and DJ, Coach Rebekah has a fresh POV on wellbeing. Her interests are a blend of wellness, music and culture. Building spaces for diverse communities and helping people explore movement through new perspectives.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FASTER_FUN",
		properties: {
			activeGoal: 750.0,
			autodownload: false,
			goal: 1050.0,
			activityType: "SPEED_DURATION",
			
			previousId: "FASTER_FUN_ENGB",
			previousIds: ["FASTER_FUN_ENGB", "FASTER_FUN"],
		},
		landing: {
			title: "Faster Fun",
			subtitle: "18 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5e031b65ad2bfa312ef4fd002cd0f1a7/faster-fun.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5e031b65ad2bfa312ef4fd002cd0f1a7/faster-fun.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Faster Fun",
				subtitle: "18 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5e031b65ad2bfa312ef4fd002cd0f1a7/faster-fun.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Fast equals fun on this speed run with Nike Running DC Coach Chelsea Cox. You'll roll through Mile pace and 10K pace intervals on your way to the finish line of this workout. Coach Cox has you ending at your best... fastest... and most fun.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n2:00 Mile pace<br>\n0:30 10K pace<br>\n1:30 Mile pace<br>\n0:30 10K pace<br>\n1:00 Mile pace<br>\n0:30 10K pace<br>\n0:30 Mile pace<br>\n0:30 10K pace<br>\n0:30 Best pace<br>\n<br>\nRecovery intervals will be 30 seconds in duration.<br>\n<br>\n18 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/faster-fun.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently the Nike Run Club DC Head Coach.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
