export const runs = [
	{
		id: "STEP_ONE_EASY_RUN",
		properties: {
			activeGoal: 1560.0,
			autodownload: false,
			goal: 1560.0,
			activityType: "SPEED_DURATION",
			
		},
		landing: {
			title: "Step One Easy Run",
			subtitle: "25 Min • Easy Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/525dbfc1-ce58-41f8-9358-6f9de1ec8c3b/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/525dbfc1-ce58-41f8-9358-6f9de1ec8c3b/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Step One Easy Run",
				subtitle: "25 Min • Easy Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/525dbfc1-ce58-41f8-9358-6f9de1ec8c3b/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Sometimes starting a workout, or even getting out the door, can be a challenge in itself…we know! This run is meant to address those roadblocks we all have; whether mental, physical, or literal, and give you an extra hand to get you through. Whether you’re an experienced runner, new to running, or just trying to get back on track, Coach Sashah will keep you motivated just in time for the New Year in this 25 minute easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>25 min easy run with 5 min warm up and 5 min cool down.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/image.png",
					titleColor: "#ffffff",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "Meet Coach Sashah",
					body: "<p>For Coach Sashah Handal, it's all about finding balance and treating our bodies with the kindness they deserve. The NYC-based Nike Running Coach focuses on building healthy fitness habits we can use day in and day out. Coach Sashah will help you find fitness goals that work for you and always make time to celebrate the little wins along the way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "STRESS_FREE_RUN_WITH_HS",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Stress Free Run",
			subtitle: "25 Min • Recovery Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ac580912aa57e1bb9b9ce8ef297ec170/stress-free-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ac580912aa57e1bb9b9ce8ef297ec170/stress-free-run.png",
			backgroundColor: "#55C1BA",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#55C1BA",
			headerCard: {
				title: "Stress Free Run",
				subtitle: "25 Min • Recovery Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ac580912aa57e1bb9b9ce8ef297ec170/stress-free-run.png",
				backgroundColor: "#55C1BA",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "We all deal with stress. And we all can learn how to take advantage of the positive stress in our lives and deal with negative stress better. Join Andy Puddicombe of Headspace and Nike's Coach Bennett on this easy 25 minute run and learn how to do both.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 25 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/stress-free-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "STRONGER_FASTER",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 2280.0,
			activityType: "SPEED_DURATION",
			
			previousId: "STRONGER_FASTER_ENGB",
			previousIds: ["STRONGER_FASTER_ENGB", "STRONGER_FASTER"],
		},
		landing: {
			title: "Stronger Faster",
			subtitle: "38 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/4ab8d9809ce184dec2260e5beaf1c875/stronger-faster.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/4ab8d9809ce184dec2260e5beaf1c875/stronger-faster.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Stronger Faster",
				subtitle: "38 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/4ab8d9809ce184dec2260e5beaf1c875/stronger-faster.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Strength and speed come together in this awesome Speed Run with Coach Chelsea Cox of Nike Running DC. Working on your 5K pace and Mile pace will make sure that your faster gets stronger and your strength gets faster.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n<br>\nWorkout:<br>\n3:00 5K pace<br>\n0:30 Mile pace<br>\n0:30 Mile pace<br>\n0:30 Mile pace<br>\n0:30 Mile pace<br>\n<br>\nRepeat series 3 times.<br>\n<br>\nRecovery intervals will vary between 1 and 2 minutes in duration.<br>\n<br>\n38 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/stronger-faster.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently the Nike Run Club DC Head Coach.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "STRUGGLE_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "STRUGGLE_RUN_ENGB",
			previousIds: ["STRUGGLE_RUN_ENGB"],
		},
		landing: {
			title: "Struggle Run",
			subtitle: "25 Min • Easy Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/508dd84c-a940-4176-9b9e-ee54d5615f11/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/508dd84c-a940-4176-9b9e-ee54d5615f11/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Struggle Run",
				subtitle: "25 Min • Easy Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/508dd84c-a940-4176-9b9e-ee54d5615f11/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p> We all struggle. Sometimes we struggle on our runs. Sometimes we struggle before or after our runs. Speed Runs. Long Runs. Hills. Work. Home. School. Relationships. It doesn’t matter what you’re struggling with… you need to know that you are not alone. Join Nike Running Global Head Coach for this 25-minute recovery run and learn how struggling is not a sign of failure… instead struggling is a sign of successfully not giving up. Coach Bennett will guide your though this easy run and make sure you end the run not only a better runner but also a better coach and teammate to yourself.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p> A relaxed, motivational and inspirational 25-minute easy run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SUCKCESSFUL_RUN",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",
			
			previousId: "SUCKCESSFUL_RUN_ENGB",
			previousIds: ["SUCKCESSFUL_RUN_ENGB", "SUCKCESSFUL_RUN"],
		},
		landing: {
			title: "Suckcess Run",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/1973d58915518422fde017cf4c55edb3/suckcess-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/1973d58915518422fde017cf4c55edb3/suckcess-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Suckcess Run",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/1973d58915518422fde017cf4c55edb3/suckcess-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Did you know that every run can be a victory? Yes, even those runs when you feel tired or lack the motivation and inspiration to run. Join Coach Bennett on this easy 35 minute run and learn how runs that suck can still be a success.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 35 minute easy and comfortable run with 1 minute of post run guidance and motivation.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/suckcess-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "SUPER_EASY_EASY_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Super Easy Easy Run",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/4c8a808e-dfa1-472d-959a-570225a316b4/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/4c8a808e-dfa1-472d-959a-570225a316b4/image.png",
			backgroundColor: "#415F96",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#415F96",
			headerCard: {
				title: "Super Easy Easy Run",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/4c8a808e-dfa1-472d-959a-570225a316b4/image.png",
				backgroundColor: "#415F96",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>25 minutes of easy running. Strike that. 25 minutes of super easy… easy running. Because sometimes easy just isn’t easy enough. Join Nike Running Global Head Coach Chris Bennett for this relaxed twenty-five-minute recovery run. It’s exactly the right run for you when you need a run before or after a long or hard or stressful or busy day.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A fun and easy 25-minute recovery run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TEMPO_RUN_WITH_PAULA",
		properties: {
			activeGoal: 1620.0,
			autodownload: false,
			goal: 1680.0,
			activityType: "SPEED_DURATION",
			
			previousId: "TEMPO_RUN_WITH_PAULA_ENGB",
			previousIds: ["TEMPO_RUN_WITH_PAULA_ENGB", "TEMPO_RUN_WITH_PAULA"],
		},
		landing: {
			title: "Tempo Run With Paula",
			subtitle: "29 Min • Tempo Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/19e755dfd686172891c1c179f6f2b7a5/tempo-run-with-paula.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/19e755dfd686172891c1c179f6f2b7a5/tempo-run-with-paula.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Tempo Run With Paula",
				subtitle: "29 Min • Tempo Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/19e755dfd686172891c1c179f6f2b7a5/tempo-run-with-paula.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Want to know what it's like to start & finish a Tempo Run with a Marathon World Record Holder? Now you can! Join Paula Radcliffe as she guides & motivates you through this 20 minute Tempo Run. You'll end this run closer to breaking your own records!\n\nCoach Becs Gentry of NRC London joins Radcliffe on this run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 7 minute warm up followed by a 20 minute tempo run. 1 minute of post run guidance and cool down.\n\n29 minute total experience.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/tempo-run-with-paula.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Paula Radcliffe",
					body: "Paula Radcliffe has run the fastest marathon ever by a woman. Her time of 2:15:25 has stood as World Record since 2003. She has won marathons in Chicago, London, and New York and has been World Champion in XC and on the roads.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TEMPO_WITH_EMILY_INFELD",
		properties: {
			activeGoal: 1920.0,
			autodownload: false,
			goal: 1980.0,
			activityType: "SPEED_DURATION",
			
			previousId: "TEMPO_WITH_EMILY_INFELD_ENGB",
			previousIds: ["TEMPO_WITH_EMILY_INFELD_ENGB", "TEMPO_WITH_EMILY_INFELD"],
		},
		landing: {
			title: "Tempo with Emily Infeld",
			subtitle: "35 Min • Tempo Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f307d9a00c179b9b25c7437134687b7c/tempo-with-emily-infeld.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f307d9a00c179b9b25c7437134687b7c/tempo-with-emily-infeld.png",
			backgroundColor: "#FF8F1C",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF8F1C",
			headerCard: {
				title: "Tempo with Emily Infeld",
				subtitle: "35 Min • Tempo Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f307d9a00c179b9b25c7437134687b7c/tempo-with-emily-infeld.png",
				backgroundColor: "#FF8F1C",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's time to Tempo! Join Emily Infeld, World Championship Bronze Medalist and Bowerman Track Club member for this 25 minute Tempo Run. Emily will guide, inspire and motivate you through a run that gets you stronger with every stride.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 7 minute warm up followed by a 25 minute Tempo Run. 1 minute of post run guidance and cool down.\n\n35 minute total experience.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/tempo-with-emily-infeld.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Emily Infeld",
					body: "Emily Infeld is a member of the Bowerman Track Club. Infeld is a World Championships Bronze Medalist in the 10,000 meters and a US XC Champion. Emily was also the NCAA Champ in the 3K. She is joined on this run by Nike Running Head Coach Chris Bennett.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TEN_MILE_RUN",
		properties: {
			activeGoal: 16096.0,
			autodownload: false,
			goal: 16096.0,
			activityType: "DISTANCE",
			
			previousId: "TEN_MILE_RUN_ENGB",
			previousIds: ["TEN_MILE_RUN_ENGB", "TEN_MILE_RUN"],
		},
		landing: {
			title: "Ten Mile Run",
			subtitle: "10 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/73ec88c0b76a1c58fd210c91ae31f628/ten-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/73ec88c0b76a1c58fd210c91ae31f628/ten-mile-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Ten Mile Run",
				subtitle: "10 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/73ec88c0b76a1c58fd210c91ae31f628/ten-mile-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Let's take this one all the way to 10! Ten miles that is. NRC Global Head Coach Chris Bennett will be there to guide you through every mile on your way to finishing a great long run at your best. This is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed ten mile run. This is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/ten-mile-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TEN_MINUTE",
		properties: {
			activeGoal: 600.0,
			autodownload: false,
			goal: 600.0,
			activityType: "DURATION",
			
			previousId: "TEN_MINUTE_ENGB",
			previousIds: ["TEN_MINUTE_ENGB", "TEN_MINUTE"],
		},
		landing: {
			title: "Ten Minute Run",
			subtitle: "10 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/cceb3d3db9e987b61dfe59ed68045173/ten-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/cceb3d3db9e987b61dfe59ed68045173/ten-minute-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Ten Minute Run",
				subtitle: "10 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/cceb3d3db9e987b61dfe59ed68045173/ten-minute-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "A Ten Minute Run. It's only ten minutes but that's enough time for you to have a great run. Join Nike Running Global Head Coach Chris Bennett for this fun recovery run and you'll be a better version of yourself by the end...10 minutes better in fact!",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy 10 minute recovery run with 1 minute of post guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/ten-minute-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike+ Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TEN_MINUTE_TEMPO_RUN",
		properties: {
			activeGoal: 951.0,
			autodownload: false,
			goal: 960.0,
			activityType: "SPEED_DURATION",
			profiles: [],
			previousId: "TEN_MINUTE_TEMPO_RUN_ENGB",
			previousIds: ["TEN_MINUTE_TEMPO_RUN_ENGB", "TEN_MINUTE_TEMPO_RUN"],
		},
		landing: {
			title: "Ten Minute Tempo Run",
			subtitle: "16 Min • Tempo Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ff3debcbc8004a4363dac38cbc5d0edb/ten-minute-tempo-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ff3debcbc8004a4363dac38cbc5d0edb/ten-minute-tempo-run.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "Ten Minute Tempo Run",
				subtitle: "16 Min • Tempo Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ff3debcbc8004a4363dac38cbc5d0edb/ten-minute-tempo-run.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "If you want to get better at running… get better at running Tempo Runs. They’re one of the best ways to work on mental and physical strength and endurance. Join Nike Running London Coach Dora Atim for this Ten Minute Tempo Run. After a five minute warm up you’ll be guided through the entire Tempo Run by Coach Dora. It doesn’t take too long to get better. In fact, all you need is ten minutes.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n10:00 Tempo Run<br>\n<br>\nTotal Experience: 16:00</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/ten-minute-tempo-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dora",
					body: "Coach Dora is a Nike Running London Coach and Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and in doing so inspires others to do the same.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THANK_YOU_RUN",
		properties: {
			activeGoal: 2700.0,
			autodownload: false,
			goal: 2700.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Thank You Run",
			subtitle: "45 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/75bece29384ea223aa6ae821160b65e3/thank-you-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/75bece29384ea223aa6ae821160b65e3/thank-you-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Thank You Run",
				subtitle: "45 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/75bece29384ea223aa6ae821160b65e3/thank-you-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Every run is a run to be thankful for. Join NRC Global Head Coach Chris Bennett on this easy 45 minute run and take part in an exercise of gratitude as you roll through the meters and miles.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 45 minute easy run with 1 minute of post run guidance and cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/thank-you-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THE_PASSION_RUN",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "The Passion Run",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/e23dd4e1-db45-4a05-ae53-96ef1634c46b/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/e23dd4e1-db45-4a05-ae53-96ef1634c46b/image.png",
			backgroundColor: "#E1224B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#E1224B",
			headerCard: {
				title: "The Passion Run",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/e23dd4e1-db45-4a05-ae53-96ef1634c46b/image.png",
				backgroundColor: "#E1224B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Passion. It’s expressed in many ways. Over the course of this 20-minute recovery run, Coach Taylor will tell you how her passion with running started and where it’s taken her. You’ll also have quiet moments to allow your mind to reflect on your own relationship with running. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An easy and inspirational 20 min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THE_PERFECT_RUN",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "The Perfect Run",
			subtitle: "15 min • Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/f8cb2fa2-6618-47fd-8e5c-8bd03e345aea/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/f8cb2fa2-6618-47fd-8e5c-8bd03e345aea/image.png",
			backgroundColor: "#C42E22",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#C42E22",
			headerCard: {
				title: "The Perfect Run",
				subtitle: "15 min • Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/f8cb2fa2-6618-47fd-8e5c-8bd03e345aea/image.png",
				backgroundColor: "#C42E22",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This 15-minute easy run is the perfect run. Why? Because it's the run you're doing. And while you're doing it, you'll hear about all the ways you get to define the perfect run. Nike Run Coach Diljeet Taylor will also share the multitude of ways SHE defines the perfect run.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run details",
					body: "<p>An easy 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ROLLERCOASTER",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "The Roller Coaster",
			subtitle: "20 Min • Treadmill Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/6d45733409fc3ce5a468831bf15b4a2c/the-roller-coaster.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/6d45733409fc3ce5a468831bf15b4a2c/the-roller-coaster.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "The Roller Coaster",
				subtitle: "20 Min • Treadmill Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/6d45733409fc3ce5a468831bf15b4a2c/the-roller-coaster.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join NRC UK Head Coach Cory Wharton-Malcolm on this rolling 20 minute easy run that is specially made for the treadmill. You'll run up and down hills as Coach motivates and inspires you to a great workout.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 20 minute easy run specially made for the treadmill.\n\nYou will receive guidance on how to adjust the elevation and speed over the course of the run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/the-roller-coaster.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THE_RUNDOWN",
		properties: {
			activeGoal: 2250.0,
			autodownload: false,
			goal: 2250.0,
			activityType: "SPEED_DURATION",
			
			previousId: "THE_RUNDOWN_ENGB",
			previousIds: ["THE_RUNDOWN_ENGB", "THE_RUNDOWN"],
		},
		landing: {
			title: "The Rundown",
			subtitle: "38 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/6ad63c707a5ae3e0fe8fc000d4a0a6a6/the-rundown.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/6ad63c707a5ae3e0fe8fc000d4a0a6a6/the-rundown.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "The Rundown",
				subtitle: "38 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/6ad63c707a5ae3e0fe8fc000d4a0a6a6/the-rundown.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>A great Speed Run is a combination of speed and endurance. That makes The Rundown one of the greatest! Join Coach Cory Wharton-Malcolm of NRC London for this fun workout. Every 5K and Mile pace interval gets you closer to running down your own greatness!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n3 x 1:00 Mile pace<br>\n3 x 2:00 5K pace<br>\n2 x 1:00 Mile pace<br>\n2 x 2:00 5K pace<br>\n1 x 1:00 Mile pace<br>\n1 x 2:00 5K pace<br>\n<br>\nRecovery periods will be 60 seconds after each 1 minute interval and 90 seconds after each 2 minute interval.<br>\n<br>\nCoach Cory will be providing guidance and motivation throughout the run.<br>\n<br>\n39 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/the-rundown.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THE_SHIFTER",
		properties: {
			activeGoal: 1140.0,
			autodownload: false,
			goal: 1470.0,
			activityType: "SPEED_DURATION",
			
			previousId: "THE_SHIFTER_ENGB",
			previousIds: ["THE_SHIFTER_ENGB", "THE_SHIFTER"],
		},
		landing: {
			title: "The Shifter",
			subtitle: "25 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ae74b7027d8fa73a516a97a84326120e/the-shifter.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ae74b7027d8fa73a516a97a84326120e/the-shifter.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "The Shifter",
				subtitle: "25 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ae74b7027d8fa73a516a97a84326120e/the-shifter.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It's time to shift gears, change paces and take your fast faster. Get moving in this Speed Run with NRC UK Coach Cory. You'll change paces within each running interval... always ending better. So be prepared for fun mixing things up with The Shifter.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n4:00 Recovery pace<br>\n1:00 Mile pace<br>\n3:00 10K pace<br>\n1:00 Mile pace<br>\n2:00 5K pace<br>\n1:00 Mile pace<br>\n1:00 Mile pace <br>\n1:00 Best pace<br>\n<br>\nRecovery intervals will vary between 1 and 2 minutes in duration.<br>\n<br>\n25 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/the-shifter.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THE_YES_RUN",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "The Yes Run",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/75d8c31c-cf71-49ca-96b9-b8922b138611/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/75d8c31c-cf71-49ca-96b9-b8922b138611/image.png",
			backgroundColor: "#C93266",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#C93266",
			headerCard: {
				title: "The Yes Run",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/75d8c31c-cf71-49ca-96b9-b8922b138611/image.png",
				backgroundColor: "#C93266",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Yes. It’s both a sentence and a single word. It’s also your answer to the question you asked yourself about whether you were going to run today. And Coach Taylor likes that answer. She’ll guide you through this 35-minute easy run where you’ll explore how to keep saying yes to running.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An easy 35 min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THIRD_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "THIRD_RUN_ENGB",
			previousIds: ["THIRD_RUN_ENGB", "THIRD_RUN"],
		},
		landing: {
			title: "Third Run",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/83ab65954ce33ad933eb23cf81c17c0a/third-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/83ab65954ce33ad933eb23cf81c17c0a/third-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Third Run",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/83ab65954ce33ad933eb23cf81c17c0a/third-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "You’ve done the 20-minute First Run. You’ve done the 22-minute Next Run. Now, it’s time for the 25-minute Third Run. You know how to start smart. And you know how to maintain or adjust your effort. You know how to coach and support yourself over the course of a run. You know you need to celebrate every run as well. So, now it’s time to just do what you know how to do. It’s time to run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and fun 25-minute recovery run with one minute of post-run motivation and inspiration.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/third-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THIRTEEN_MINUTE_RUN",
		properties: {
			activeGoal: 780.0,
			autodownload: false,
			goal: 780.0,
			activityType: "DURATION",
			
			previousId: "THIRTEEN_MINUTE_RUN_ENGB",
			previousIds: ["THIRTEEN_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Thirteen Minute Run",
			subtitle: "13 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/c11ff945-cfb5-4d95-bed4-0bf8126f10b6/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/c11ff945-cfb5-4d95-bed4-0bf8126f10b6/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Thirteen Minute Run",
				subtitle: "13 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/c11ff945-cfb5-4d95-bed4-0bf8126f10b6/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Feeling lucky? You should! Because you found the Thirteen Minute Run and it’s a great run! And you are so close to starting it! Join Nike Running New Zealand Coach Lydia O’Donnell for the Thirteen Minute Run. This easy recovery run is meant to be run relaxed and comfortably. So, lace up your trainers and cross the starting line with Coach Lydia.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable 13-minute recovery run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Join Lydia O’Donnell of NRC New Zealand is an accomplished runner, coach, and wellness advocate. Coach O’Donnell works tirelessly to share the sport the right way with as many people as she can because Coach knows that a better run can lead to a better runner. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "35_MINUTE_RUN",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Thirty Five Minute Run",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/7986f759-8d4c-47b1-845f-3ee476aa5c1d/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/7986f759-8d4c-47b1-845f-3ee476aa5c1d/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Thirty Five Minute Run",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/7986f759-8d4c-47b1-845f-3ee476aa5c1d/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>35 minutes… it’s the new classic. Sure, everyone has heard of running 30 minutes. But did you know that 35 minutes has 5 more minutes of running awesomeness? It does! And Coach Bennett, the Nike Running Global Head Coach, is ready to guide you through all of it. Get ready for the fun and inspirational easy run known as the… wait for it… Thirty Five Minute Run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable, fun and easy 35-minute recovery run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THIRTY_MINUTE_RUN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "THIRTY_MINUTE_RUN_ENGB",
			previousIds: ["THIRTY_MINUTE_RUN_ENGB", "THIRTY_MINUTE_RUN"],
		},
		landing: {
			title: "Thirty Minute Run",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/8ffe75551d584a5ee7acb3b0649ddd5e/thirty-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/8ffe75551d584a5ee7acb3b0649ddd5e/thirty-minute-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Thirty Minute Run",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/8ffe75551d584a5ee7acb3b0649ddd5e/thirty-minute-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "30 minutes. Half an hour. Classic. When it comes to duration... thirty minutes is the most popular duration of them all. But just because everyone is doing it... doesn’t mean they are doing it the right way. That’s why we made the Thirty Minute Run. You’ll not only run these thirty minutes a better way... you’ll end the run loving every minute of it.  Join Nike Running Global Head Coach Chris Bennett for this relaxed and fun thirty minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and easy 30-minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/thirty-minute-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "THREE_MINUTE_RUN",
		properties: {
			activeGoal: 180.0,
			autodownload: false,
			goal: 180.0,
			activityType: "DURATION",
			profiles: [],
			previousId: "THREE_MINUTE_RUN_ENGB",
			previousIds: ["THREE_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Three Minute Run",
			subtitle: "3 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/77592bcb-35ca-42fb-8b14-dbf4ab74eb17/three-minute-run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/77592bcb-35ca-42fb-8b14-dbf4ab74eb17/three-minute-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Three Minute Run",
				subtitle: "3 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/77592bcb-35ca-42fb-8b14-dbf4ab74eb17/three-minute-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Three is a crowd? Not when it comes to a run! Three is a party!<br>\n<br>\nGet ready for some real fun on the Three Minute Run! join Nike Running London Coach Dora for 180 seconds of running. You'll end inspired and happy. Sounds like a great way to finish a run today and want to start another one tomorrow.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A motivational and relaxed 3-minute easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/three-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dora",
					body: "<p>Coach Dora Atim is a Nike Running London Coach and Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and in doing so inspires others to do the same.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TINY_TREADMILL_RUN",
		properties: {
			activeGoal: 600.0,
			autodownload: false,
			goal: 600.0,
			activityType: "DURATION",
			
			previousId: "TINY_TREADMILL_RUN_ENGB",
			previousIds: ["TINY_TREADMILL_RUN_ENGB", "TINY_TREADMILL_RUN"],
		},
		landing: {
			title: "Tiny Treadmill Run",
			subtitle: "10 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5353be94778e992c22f74474cbd82a76/tiny-treadmill-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5353be94778e992c22f74474cbd82a76/tiny-treadmill-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Tiny Treadmill Run",
				subtitle: "10 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5353be94778e992c22f74474cbd82a76/tiny-treadmill-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Sometimes something tiny is a really big deal. Like with this 10-minute treadmill run here. Join NRC UK Head Coach Cory Wharton-Malcolm for this super fun ten-minute easy run. This run is specially made for the treadmill. Make sure you have the NRC app set for an indoor run and that you’re set for a great run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "10-minute easy run specially made for the treadmill with one minute of post run guidance and inspiration.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/tiny-treadmill-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory-Wharton-Malcolm is the Nike Run Club UK Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TODAYS_30_MINUTE_RUN",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "TODAYS_30_MINUTE_RUN_ENGB",
			previousIds: ["TODAYS_30_MINUTE_RUN_ENGB", "TODAYS_30_MINUTE_RUN"],
		},
		landing: {
			title: "Today's 30 Minute Run",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/580dafc27815f970aa419170500c7d8a/today-s-30-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/580dafc27815f970aa419170500c7d8a/today-s-30-minute-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Today's 30 Minute Run",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/580dafc27815f970aa419170500c7d8a/today-s-30-minute-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Today’s 30 Minute Run is all about you & this day that just began or ended. Chris Bennett, the Nike Running Global Head Coach, will offer up questions throughout the run for you to answer that will help you start or finish your day in a better place. Join Coach Bennett for this easy & comfortable 30 minute run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and motivational 30 minute easy run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/today-s-30-minute-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
