export const runs = [
	{
		id: "FEAR_LESS_5K",
		properties: {
			activeGoal: 5003.0,
			autodownload: false,
			goal: 5003.0,
			activityType: "DISTANCE",

			previousId: "FEAR_LESS_5K_ENGB",
			previousIds: ["FEAR_LESS_5K_ENGB", "FEAR_LESS_5K"],
		},
		landing: {
			title: "Fear Less 5K",
			subtitle: "5K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/89fd7a0893d002aed959d6ba40e6a57e/fear-less-5k.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/89fd7a0893d002aed959d6ba40e6a57e/fear-less-5k.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "Fear Less 5K",
				subtitle: "5K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/89fd7a0893d002aed959d6ba40e6a57e/fear-less-5k.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "We all have fears. It’s natural. How we acknowledge them, handle them, deal with them, live with them, overcome them, and run with them is the conversation on this run. Join Nike Running Global Head Coach for this inspirational 5K distance based guided run. This is not a run about being fearless… it’s a run about being brave.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and motivational 5K run. That’s just over 3.1 miles. This is a distance-based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/fear-less-5k.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIFTEEN_MINUTE_RUN",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Fifteen Minute Run",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/63de15cc973cd1f09df376fa22dba9b7/fifteen-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/63de15cc973cd1f09df376fa22dba9b7/fifteen-minute-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Fifteen Minute Run",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/63de15cc973cd1f09df376fa22dba9b7/fifteen-minute-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "15 minutes isn’t a short run. 15 minutes is a run! And this 15-minute run is a great run. Join Nike Running Global Head Coach Chris Bennett for this relaxed and comfortable recovery run. You’ll end the run knowing that every run is an important run and every runner can learn something new with every run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and easy 15-minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/fifteen-minute-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIND_YOUR_PACE",
		properties: {
			activeGoal: 600.0,
			autodownload: false,
			goal: 840.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Find Your\n Pace",
			subtitle: "15 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/45cf0a2d7e5e23c90871eb1c600d4f01/find-your-pace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/45cf0a2d7e5e23c90871eb1c600d4f01/find-your-pace.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Find Your\n Pace",
				subtitle: "15 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/45cf0a2d7e5e23c90871eb1c600d4f01/find-your-pace.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Ever wonder what 5k pace means… for you? ‬‪How about 10k or ‬Mile pace?‬ ‪Join Coach Cory Wharton-Malcolm on this short workout and unlock all your paces and finish a smarter and more confident runner.‬ ‪Learn to run the right way... your way.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n2:00 10K pace<br>\n1:30 5K pace<br>\n1:00 Mile pace<br>\n0:30 Best pace<br>\n<br>\nRecovery intervals will be 1 minute.<br>\n<br>\nCoach Cory will be providing guidance and motivation throughout the run.<br>\n<br>\n15 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Find Your Pace",
					url: "https://static.nike.com/ntc-prod/images/42c6a29ac65e0a96200d9db42c95d7d9/find-your-pace.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/find-your-pace/pl.4765719c90e74782aa855256070ebe33",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0gMSxTs5OYBaeXztxiF6eS",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIND_YOUR_RUN_WITH_DINA_ENGB",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",

			previousId: "FIND_YOUR_RUN_WITH_DINA_ENGB",
			previousIds: ["FIND_YOUR_RUN_WITH_DINA_ENGB"],
		},
		landing: {
			title: "Find Your Run with Dina",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/f951b35c-82d6-4a1b-8c60-efc7995cad50/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/f951b35c-82d6-4a1b-8c60-efc7995cad50/image.png",
			backgroundColor: "#E8E8E8",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#E8E8E8",
			headerCard: {
				title: "Find Your Run with Dina",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/f951b35c-82d6-4a1b-8c60-efc7995cad50/image.png",
				backgroundColor: "#E8E8E8",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This Guided Run is about finding and getting to know the runner within you. Coach Dora and sprinting champion Dina Asher-Smith will share their personal stories as to how they found their passion for running, while Dora will keep you running the right way with some coaching here and there. By the end, you’ll have truly found your run – and not just this once, but every run after that, too.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>This is a 30-minute easy run followed one minute of post-run coaching and guidance.<br>\n<br>\n  Total Experience: 31 Minutes</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Coach Dora is a Nike Running London Coach and a Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and, in doing so, inspires others to do the same.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIRST_FARTLEK_RUN",
		properties: {
			activeGoal: 1080.0,
			autodownload: false,
			goal: 1080.0,
			activityType: "SPEED_DURATION",

			previousId: "FIRST_FARTLEK_RUN_ENGB",
			previousIds: ["FIRST_FARTLEK_RUN_ENGB", "FIRST_FARTLEK_RUN"],
		},
		landing: {
			title: "First Fartlek Run",
			subtitle: "19  Min • Fartlek",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7a62d7271cef09957c516410d5bdc3f8/first-fartlek-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7a62d7271cef09957c516410d5bdc3f8/first-fartlek-run.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "First Fartlek Run",
				subtitle: "19  Min • Fartlek",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7a62d7271cef09957c516410d5bdc3f8/first-fartlek-run.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Fartlek is an essential part of any runners training. Fartlek is loosely translated as speed play. And that is exactly what you will do with Coach Bennett during this fun and exciting speed run. After a seven-minute warm up Coach Bennett will guide you through a ten-minute fartlek run. You will change speeds and paces throughout this ten-minute fartlek alternating between easier and harder efforts. You’ll build strength… physical and mental strength… while you play with your speed and efforts. Running is meant to be fun and a fartlek run proves that it can be.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A seven-minute warm up followed by a ten-minute fartlek run that alternates between easy running and harder running.\n\nTotal Experience: 19:00",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/first-fartlek-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIRST_LONG_RUN",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",

			previousId: "FIRST_LONG_RUN_ENGB",
			previousIds: ["FIRST_LONG_RUN_ENGB", "FIRST_LONG_RUN"],
		},
		landing: {
			title: "First Long Run",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/320baa883999d432d478ba6026961111/first-long-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/320baa883999d432d478ba6026961111/first-long-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "First Long Run",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/320baa883999d432d478ba6026961111/first-long-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's time for your First Long Run. Coach Bennett will be with you for every stride to make sure this run is long on fun and motivation. You'll finish the 35 minutes feeling inspired by what you accomplished & ready for your next starting line.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 35 minute run with 1 minute of post run guidance.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/first-long-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIRST_RUN",
		properties: {
			activeGoal: 1205.0,
			autodownload: false,
			goal: 1205.0,
			activityType: "DURATION",

			previousId: "FIRST_RUN_ENGB",
			previousIds: ["FIRST_RUN_ENGB", "FIRST_RUN"],
		},
		landing: {
			title: "First Run",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/284fd799-c5ca-431a-b503-21782d36f991/first-run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/284fd799-c5ca-431a-b503-21782d36f991/first-run.png",
			backgroundColor: "#18B3D3",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#18B3D3",
			headerCard: {
				title: "First Run",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/284fd799-c5ca-431a-b503-21782d36f991/first-run.png",
				backgroundColor: "#18B3D3",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Get out on a great introductory audio guided run with Nike Running Global Head Coach Chris Bennett. Coach Bennett will give you some key pointers and guide you through a 23 minute easy run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 20 minute easy run with a 3 minute cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "First Run",
					url: "https://static.nike.com/ntc-prod/images/e77833cc1e7414064755652c20be7c31/first-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIRST_SPEED_RUN",
		properties: {
			activeGoal: 810.0,
			autodownload: false,
			goal: 1440.0,
			activityType: "SPEED_DURATION",

			previousId: "FIRST_SPEED_RUN_ENGB",
			previousIds: ["FIRST_SPEED_RUN_ENGB", "FIRST_SPEED_RUN"],
		},
		landing: {
			title: "First \nSpeed Run",
			subtitle: "27 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/58ec80d0c5ae2c71b77c6881ee636af5/first-speed-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/58ec80d0c5ae2c71b77c6881ee636af5/first-speed-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "First \nSpeed Run",
				subtitle: "27 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/58ec80d0c5ae2c71b77c6881ee636af5/first-speed-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Work on your speed with this introductory interval workout. Coach Bennett will guide you through a set of 8 x 1 minute intervals.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "8 x 1 minute intervals at your 5k pace with 1 minute recovery after each running interval.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "First Speed Run",
					url: "https://static.nike.com/ntc-prod/images/0346cc20098f5e6425a8d6a37b805a1b/first-speed-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIRST_TREADMILL_RUN",
		properties: {
			activeGoal: 1440.0,
			autodownload: false,
			goal: 1440.0,
			activityType: "DURATION",

			previousId: "FIRST_TREADMILL_RUN_ENGB",
			previousIds: ["FIRST_TREADMILL_RUN_ENGB", "FIRST_TREADMILL_RUN"],
		},
		landing: {
			title: "First Treadmill Run",
			subtitle: "24 Min • Treadmill Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f238076d551fbfb8f531e25611a516d7/first-treadmill-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f238076d551fbfb8f531e25611a516d7/first-treadmill-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "First Treadmill Run",
				subtitle: "24 Min • Treadmill Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f238076d551fbfb8f531e25611a516d7/first-treadmill-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Run on the treadmill a better way. Join Coach Bennett on this easy and fun 24 minute guided run. Your time on the treadmill doesn't need to feel like time on a treadmill. It can be a great run... every time.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 24 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/first-treadmill-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIVE_MILE_RUN",
		properties: {
			activeGoal: 8050.0,
			autodownload: false,
			goal: 8050.0,
			activityType: "DISTANCE",

			previousId: "FIVE_MILE_RUN_ENGB",
			previousIds: ["FIVE_MILE_RUN_ENGB", "FIVE_MILE_RUN"],
		},
		landing: {
			title: "Five Mile Run",
			subtitle: "5 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5cbe005525f8ae2a07744d9c82e1bc27/five-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5cbe005525f8ae2a07744d9c82e1bc27/five-mile-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Five Mile Run",
				subtitle: "5 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5cbe005525f8ae2a07744d9c82e1bc27/five-mile-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Who knew running 5 miles could be so much fun? We did! Join Nike Running Head Coach Chris Bennett on this distance based guided run. This run will have you motivated, inspired and excited to go longer and better.",
					titleColor: "#FFFFFF",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed five mile run. This is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/five-mile-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIVE_MINUTE_FARTLEK",
		properties: {
			activeGoal: 645.0,
			autodownload: false,
			goal: 660.0,
			activityType: "SPEED_DURATION",
			profiles: [],
			previousId: "FIVE_MINUTE_FARTLEK_ENGB",
			previousIds: ["FIVE_MINUTE_FARTLEK_ENGB", "FIVE_MINUTE_FARTLEK"],
		},
		landing: {
			title: "Five Minute Fartlek",
			subtitle: "12 Min • Fartlek",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/9be08e08d171e2d45a215f2b8fffbc1f/five-minute-fartlek.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/9be08e08d171e2d45a215f2b8fffbc1f/five-minute-fartlek.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "Five Minute Fartlek",
				subtitle: "12 Min • Fartlek",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/9be08e08d171e2d45a215f2b8fffbc1f/five-minute-fartlek.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This Five Minute Fartlek proves that it doesn’t take too long to change your pace, speed, effort… or even your day. Join Nike London Coach Dora Atim for a fun and fast fartlek that will have your run done in no time! After a relaxed and guided five-minute warm up, Coach Dora will get you moving. The Five Minute Fartlek will be a mix of 10K, 5K and Mile pace runs with easy and comfortable recovery running in-between those strong efforts. You won’t need to give too much time to do this speed run… but you will get so much from the time you give.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "The speed run begins with a 5 minute warm up and is followed by a 5 minute fartlek run that alternates between 10K (Hard), 5K (Harder) and Mile (Hardest) pace efforts with easy recovery running in-between each. The total experience is 12 minutes long.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/five-minute-fartlek.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dora",
					body: "Coach Dora is a Nike Running London Coach and Fitness Trainer. She is fueled by a passion for sharing movement and sport with everyone. Coach works every day to get more people moving and in doing so inspires others to do the same.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FIVE_MINUTE_RUN",
		properties: {
			activeGoal: 300.0,
			autodownload: false,
			goal: 300.0,
			activityType: "DURATION",

			previousId: "FIVE_MINUTE_RUN_ENGB",
			previousIds: ["FIVE_MINUTE_RUN_ENGB", "FIVE_MINUTE_RUN"],
		},
		landing: {
			title: "Five Minute Run",
			subtitle: "5 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f028ee4bdb078c1a76dd38a12ac6981a/five-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f028ee4bdb078c1a76dd38a12ac6981a/five-minute-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Five Minute Run",
				subtitle: "5 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f028ee4bdb078c1a76dd38a12ac6981a/five-minute-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "A Five Minute Run. If you've only got a few minutes... we've got the perfect run for you. Nike Running Global Head Coach Chris Bennett will be with you for every stride. It's not a long run... it's a 5 minutes long run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy 5 minute recovery run with 1 minute of post run guidance and cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/five-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FLY_WITH_MONAS",
		properties: {
			activeGoal: 1602.0,
			autodownload: false,
			goal: 1602.0,
			activityType: "SPEED_DURATION",
			profiles: [],
		},
		landing: {
			title: "Fly With Monas",
			subtitle: "20 Min • Fartlek",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/328c1d9d-71e7-49b1-8ee2-3faa106e8fd7/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/328c1d9d-71e7-49b1-8ee2-3faa106e8fd7/image.png",
			backgroundColor: "#bf0835",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#bf0835",
			headerCard: {
				title: "Fly With Monas",
				subtitle: "20 Min • Fartlek",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/328c1d9d-71e7-49b1-8ee2-3faa106e8fd7/image.png",
				backgroundColor: "#bf0835",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Want to know what it takes to be one of the best of all time? Steve Moneghetti one of Australia’s best athletes of all time takes you through the paces of his favourite Fartlek workout with a few stories along the way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A 20 minute guided fartlek session with 6 minutes warm up and cool down.<br>\n<br>\n6:00 Warm up<br>\n<br>\n:90 5k Pace<br>\n<br>\n:90 Easy<br>\n<br>\n:90 5k Pace<br>\n<br>\n:90 Easy<br>\n<br>\n:60 5k Pace<br>\n<br>\n:60 Easy<br>\n<br>\n:60 5k Pace<br>\n<br>\n:60 Easy<br>\n<br>\n:60 5k Pace<br>\n<br>\n:60 Easy<br>\n<br>\n:60 5k Pace<br>\n<br>\n:60 Easy<br>\n<br>\n:30 5k Pace<br>\n<br>\n:30 Easy<br>\n<br>\n:30 5k Pace<br>\n<br>\n:30 Easy<br>\n<br>\n:30 5k Pace<br>\n<br>\n:30 Easy<br>\n<br>\n:30 5k Pace<br>\n<br>\n:30 Easy<br>\n<br>\n:15 5k Pace<br>\n<br>\n:15 Easy<br>\n<br>\n:15 5k Pace<br>\n<br>\n:15 Easy<br>\n<br>\n:15 5k Pace<br>\n<br>\n:15 Easy<br>\n<br>\n:15 5k Pace<br>\n<br>\n:15 Easy</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Steve Moneghetti is one of Australia’s greatest ever long distance runners and marathon gold medallist.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FOURK_YEAH_RUN!",
		properties: {
			activeGoal: 4000.0,
			autodownload: false,
			goal: 4000.0,
			activityType: "DISTANCE",

			previousId: "FOURK_YEAH_RUN!_ENGB",
			previousIds: ["FOURK_YEAH_RUN!_ENGB"],
		},
		landing: {
			title: "FourK Yeah Run!",
			subtitle: "4K • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/619fa655-53f4-4f9e-ba59-f6d952da5a36/fourk-yeah-run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/619fa655-53f4-4f9e-ba59-f6d952da5a36/fourk-yeah-run.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "FourK Yeah Run!",
				subtitle: "4K • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/619fa655-53f4-4f9e-ba59-f6d952da5a36/fourk-yeah-run.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>FOURK YEAH RUN! You excited? So are we! So, let’s get this most excellent 4K run with Coach Shalane Flanagan started! This distance-based audio guided run is all about celebrating the ride… the whole ride. The highs and lows, the plateaus and mountaintops, the barriers and breakthroughs… they all are a part of the journey. And Coach Flanagan is here to celebrate it all. Shalane shares the insights and lessons she’s learned during the minutes, meters, and miles she’s spent running. You’ll end this 4K further ahead… and inspired to take another starting line.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An inspiring 4000 meter (almost 2.5 miles) easy run. This is a distance based guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/fourk-yeah-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Shalane Flanagan",
					body: "<p>Shalane Flanagan is a coach with the Bowerman Track Club. Coach Flanagan was also one of the greatest distance runners of her generation. She is an Olympic Silver medalist in the 10K as well as a winner of the NYC Marathon. Coach Flanagan still hold numerous American Records. She’s now coaching one of the most successful groups of distance runners in the world with the Bowerman Track Club (BTC).</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FOUR_MILE_HEAD_STARTS",
		properties: {
			activeGoal: 6443.0,
			autodownload: false,
			goal: 6443.0,
			activityType: "DISTANCE",

			previousId: "FOUR_MILE_HEAD_STARTS_ENGB",
			previousIds: ["FOUR_MILE_HEAD_STARTS_ENGB", "FOUR_MILE_HEAD_STARTS"],
		},
		landing: {
			title: "Four Mile Head Starts",
			subtitle: "4 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/ad444ef84277374e2b6c82223d418750/four-mile-head-starts.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/ad444ef84277374e2b6c82223d418750/four-mile-head-starts.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "Four Mile Head Starts",
				subtitle: "4 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/ad444ef84277374e2b6c82223d418750/four-mile-head-starts.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It’s time for another great conversation between your mind and body with Four Mile Head Starts! Join Nike Running Global Head Coach for this engaging and motivational distance-based run. Every run can and should be both a physical and mindful exercise. Over the course of this roughly 6.5K run you’ll be given a series of thought starters and questions. Coach Bennett will inspire you to let your mind run where it wants to and by the end of Four Mile Head Starts… you’ll end up where you need to be.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed, engaging and motivational 4 Mile/~6.5K Run. This is a distance-based run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/four-mile-head-starts.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FOUR_MILE",
		properties: {
			activeGoal: 6440.0,
			autodownload: false,
			goal: 6440.0,
			activityType: "DISTANCE",

			previousId: "FOUR_MILE_ENGB",
			previousIds: ["FOUR_MILE_ENGB", "FOUR_MILE"],
		},
		landing: {
			title: "Four Mile Run",
			subtitle: "4 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/e7f05999e14a71c2c7a8c4c0d1e62cc7/four-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/e7f05999e14a71c2c7a8c4c0d1e62cc7/four-mile-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Four Mile Run",
				subtitle: "4 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/e7f05999e14a71c2c7a8c4c0d1e62cc7/four-mile-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Sometimes you want to run longer than 5K. And sometimes you just want to go less than 5 miles. We get it! We really do! That’s why we’ve got the Four Mile Run. Join Coach Bennett on this excellent distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 4 Mile (or approximately 6.5K) run. This is a distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/four-mile-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FOUR_MINUTE_RUN",
		properties: {
			activeGoal: 240.0,
			autodownload: false,
			goal: 240.0,
			activityType: "DURATION",

			previousId: "FOUR_MINUTE_RUN_ENGB",
			previousIds: ["FOUR_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Four Minute Run",
			subtitle: "4 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/4fdc8ac1-1c3d-4816-a6d6-f13bfcab314e/four-minute-run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/4fdc8ac1-1c3d-4816-a6d6-f13bfcab314e/four-minute-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Four Minute Run",
				subtitle: "4 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/4fdc8ac1-1c3d-4816-a6d6-f13bfcab314e/four-minute-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Get ready to run forward for four minutes with Nike Running New Zealand Coach Lydia. Every run has the opportunity to end with a better version of yourself. This relaxed and inspiring run led by Coach Lydia is full of the motivation and guidance you need to run the run you want to run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A fun and comfortable 4-minute easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/four-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Lydia O'Donnell",
					body: "<p>Join Lydia O’Donnell of NRC New Zealand is an accomplished runner, coach, and wellness advocate. Coach O’Donnell works tirelessly to share the sport the right way with as many people as she can because Coach knows that a better run can lead to a better runner.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FOURTEEN_MINUTE_RUN",
		properties: {
			activeGoal: 840.0,
			autodownload: false,
			goal: 840.0,
			activityType: "DURATION",

			previousId: "FOURTEEN_MINUTE_RUN_ENGB",
			previousIds: ["FOURTEEN_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Fourteen Minute Run",
			subtitle: "14 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/32848b39-8f59-4b03-bc46-482b16ae06fc/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/32848b39-8f59-4b03-bc46-482b16ae06fc/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Fourteen Minute Run",
				subtitle: "14 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/32848b39-8f59-4b03-bc46-482b16ae06fc/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p> Let’s go! It’s time for the Fourteen Minute Run! Coach Bennett, the Nike Running Global Head Coach is ready to run with you on this inspiring easy run. You’ll get the guidance and motivation to have a better run from Coach Bennett and end these fourteen minutes feeling excited for that next starting line… and next run.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p> An easy 14-minute recovery run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FTR_WITH_SHALANE",
		properties: {
			activeGoal: 1980.0,
			autodownload: false,
			goal: 1980.0,
			activityType: "DURATION",

			previousId: "GO_FAST_WITH_ELAINE_ENGB",
			previousIds: ["GO_FAST_WITH_ELAINE_ENGB", "GO_FAST_WITH_ELAINE"],
		},
		landing: {
			title: "Fuel The Run with Shalane",
			subtitle: "33 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f3e227e403985b9d2c0d7625d486ae31/fuel-the-run-with-shalane.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f3e227e403985b9d2c0d7625d486ae31/fuel-the-run-with-shalane.png",
			backgroundColor: "#FF8F1C",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF8F1C",
			headerCard: {
				title: "Fuel The Run with Shalane",
				subtitle: "33 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f3e227e403985b9d2c0d7625d486ae31/fuel-the-run-with-shalane.png",
				backgroundColor: "#FF8F1C",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join Shalane Flanagan on this 33 minute easy run as she shares her passion for running and the fuel that powers it. Shalane talks about the power of better nutrition, the joy of cooking for yourself and others and the importance of being a great teammate.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 33 minute easy recovery run with 1 minute of post run cool down and inspiration.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/fuel-the-run-with-shalane.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Shalane Flanagan",
					body: "Shalane Flanagan of Bowerman Track Club is an Olympic 10K Silver Medalist and a winner of both the NYC and US Olympic Trials Marathons. Flanagan is co-author with Elyse Kopecky of the best selling Run Fast. Eat Slow. and Run Fast. Cook Fast. Eat Slow. cookbooks.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "FUNKY_FARTLEK",
		properties: {
			activeGoal: 1495.0,
			autodownload: false,
			goal: 1560.0,
			activityType: "SPEED_DURATION",

			previousId: "FUNKY_FARTLEK_ENGB",
			previousIds: ["FUNKY_FARTLEK_ENGB"],
		},
		landing: {
			title: "Funky Fartlek",
			subtitle: "20 Min • Fartlek",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/77101c30-5380-4b6a-b992-31c9b15e8dc3/funky-fartlek.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/77101c30-5380-4b6a-b992-31c9b15e8dc3/funky-fartlek.png",
			backgroundColor: "#D4FF2A",
			titleColor: "#111111",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D4FF2A",
			headerCard: {
				title: "Funky Fartlek",
				subtitle: "20 Min • Fartlek",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/77101c30-5380-4b6a-b992-31c9b15e8dc3/funky-fartlek.png",
				backgroundColor: "#D4FF2A",
				titleColor: "#111111",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It’s time to get funky! Join Coach Bennett on this fun and exciting fartlek. Fartlek is loosely translated as speed play and on this run that is exactly what you are going to do! You just may not know how long you’re going to be having so much fun because Coach isn’t going to tell you! That’s right. Coach Bennett will let you know when to run hard and when to run easy, but he won’t be telling you for how long. When it’s time to change pace and efforts Coach will simply count you down from one and into another. We told you things were going to get funky. And this fartlek puts the fun in funky!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A five-minute warm up followed by a twenty-minute fartlek run that alternates between easy running and harder running.<br>\n<br>\nTotal Experience: 27:00</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/funky-fartlek.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "GET_IN_YOUR_HEAD",
		properties: {
			activeGoal: 2163.0,
			autodownload: false,
			goal: 2163.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Get In Your Head",
			subtitle: "35 Min • Speed Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/c50446f4-ba7d-46b9-88f0-d90b13fe35df/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/c50446f4-ba7d-46b9-88f0-d90b13fe35df/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Get In Your Head",
				subtitle: "35 Min • Speed Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/c50446f4-ba7d-46b9-88f0-d90b13fe35df/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Expect the unexpected! The Get In Your Head run turns the tables with Community Running Coach and Captain for Old Man Run Club Kim Yee putting Jes in the hot seat. In this podcast-style run, they’ll talk about tips and tricks to improve your mental toughness across everything you do, while you’ll be asked to push the pace through four 5 minute intervals, each broken up by a 90 second recovery. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>35-minute progression run that starts with a 5 minute warm up and ends with a 5 minute cool down.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Jes",
					body: "<p>Running is for everyone. There’s nobody who exudes that all-are-welcome energy like Coach Jes. She’s an ultra-endurance runner, NYC-based Nike Running Coach, and an all-around running expert. She’s here to help each runner find their own fun, sustainable running practice they’ll be excited to keep for the long run.<br>\n<br>\nFrom the power of recovery to injury prevention, or long-haul mental toughness to face-paced training tips, Jes has got the wisdom and experience to help you become a better runner.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "GIANNIS_ON_THE_GO",
		properties: {
			activeGoal: 1380.0,
			autodownload: false,
			goal: 1440.0,
			activityType: "SPEED_DURATION",
			profiles: [],
		},
		landing: {
			title: "Giannis On The Go",
			subtitle: "25 Min • Tempo Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/81f48b1cf5e7b480ec0a688700586517/giannis-on-the-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/81f48b1cf5e7b480ec0a688700586517/giannis-on-the-go.png",
			backgroundColor: "#0032A1",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#0032A1",
			headerCard: {
				title: "Giannis On The Go",
				subtitle: "25 Min • Tempo Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/81f48b1cf5e7b480ec0a688700586517/giannis-on-the-go.png",
				backgroundColor: "#0032A1",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "How is a tempo run like a basketball game? Let the Greek Freak break it down for you one quarter at a time in this 16-minute, game-changing workout. Giannis Antetokounmpo will show you how to pace yourself, stay focused, and finish strong.",
					titleColor: "#ffffff",
					backgroundColor: "#002370",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 24 minute tempo run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#002370",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/giannis-on-the-go.png",
					titleColor: "#ffffff",
					backgroundColor: "#002370",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Giannis Antetokounmpo",
					body: "Giannis Antetokounmpo is an NBA All-Star and one of the most exciting players in the league. Standing 6’11” with the agility and ball-handling skills of a point guard, Antetokounmpo is a singular talent ushering in the modern era of basketball.",
					titleColor: "#ffffff",
					backgroundColor: "#002370",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "GO_FAST_WITH_ELAINE",
		properties: {
			activeGoal: 675.0,
			autodownload: false,
			goal: 1245.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Go Fast With Elaine",
			subtitle: "22 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/46b98e6c53ed56fb7faee83d3f2770c8/go-fast-with-elaine.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/46b98e6c53ed56fb7faee83d3f2770c8/go-fast-with-elaine.png",
			backgroundColor: "#DA2990",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DA2990",
			headerCard: {
				title: "Go Fast With Elaine",
				subtitle: "22 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/46b98e6c53ed56fb7faee83d3f2770c8/go-fast-with-elaine.png",
				backgroundColor: "#DA2990",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The fastest woman in the world cannot make you as fast as her. What she CAN, do, however, is make running your fastest fun enough that you’ll want to do it over. And over. It’s short, it’s fast, it’s intense—and it’ll leave you wanting more.",
					titleColor: "#ffffff",
					backgroundColor: "#BD006E",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n0:30 Mile pace<br>\n0:15 Best pace<br>\n0:45 Mile pace<br>\n0:15 Best pace<br>\n0:60 Mile pace<br>\n0:15 Best pace<br>\n0:75 Mile pace<br>\n0:15 Best pace<br>\n0:90 Mile pace<br>\n0:15 Best pace<br>\n<br>\nRecovery intervals will vary between 30 and 90 seconds in duration.<br>\n<br>\nCoach Sally and Elaine will provide guidance and motivation throughout the run.<br>\n<br>\n22 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#BD006E",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/go-fast-with-elaine.png",
					titleColor: "#ffffff",
					backgroundColor: "#BD006E",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Elaine Thompson",
					body: "Elaine Thompson of Jamaica is a gold medalist in the 100m, 200m and 4x100m relay. Her double gold in the individual sprints in Rio 2016 was the first since Florence Griffith Joyner in 1988.",
					titleColor: "#ffffff",
					backgroundColor: "#BD006E",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "GO_LONG_WITH_EVAN",
		properties: {
			activeGoal: 4500.0,
			autodownload: false,
			goal: 4500.0,
			activityType: "DURATION",
			profiles: [],
			previousId: "GO_LONG_WITH_EVAN_ENGB",
			previousIds: ["GO_LONG_WITH_EVAN_ENGB", "GO_LONG_WITH_EVAN"],
		},
		landing: {
			title: "Go Long\n With Evan",
			subtitle: "75 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/b9423292c1a4ad134c10e8c363f970fc/go-long-with-evan.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/b9423292c1a4ad134c10e8c363f970fc/go-long-with-evan.png",
			backgroundColor: "#0032A1",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#0032A1",
			headerCard: {
				title: "Go Long\n With Evan",
				subtitle: "75 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/b9423292c1a4ad134c10e8c363f970fc/go-long-with-evan.png",
				backgroundColor: "#0032A1",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Evan Jager is in it for the long haul. From his early dreams of becoming a professional soccer player to finding his footing on the track, the two-time Olympian and American record holder in the 3000m steeplechase shares his story of endurance.",
					titleColor: "#ffffff",
					backgroundColor: "#002370",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 75 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#002370",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/go-long-with-evan.png",
					titleColor: "#ffffff",
					backgroundColor: "#002370",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Evan Jager",
					body: "Evan Jager is an American distance runner. He is the American record holder in the 3000m steeplechase and is an Olympic silver medalist.",
					titleColor: "#ffffff",
					backgroundColor: "#002370",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "GRATEFUL_5K_RUN",
		properties: {
			activeGoal: 5000.0,
			autodownload: false,
			goal: 5000.0,
			activityType: "DISTANCE",

			previousId: "GRATEFUL_5K_RUN_ENGB",
			previousIds: ["GRATEFUL_5K_RUN_ENGB"],
		},
		landing: {
			title: "Grateful 5K Run",
			subtitle: "5K • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/8149c802-66e5-4ea4-abfb-a3e50579ead7/grateful_5k_run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/8149c802-66e5-4ea4-abfb-a3e50579ead7/grateful_5k_run.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "Grateful 5K Run",
				subtitle: "5K • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/8149c802-66e5-4ea4-abfb-a3e50579ead7/grateful_5k_run.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Want to have a better run? Have a grateful run! Join Nike Running Global Head Coach Chris Bennett on this beautiful 5K Run. Coach Bennett helps guide you through a powerful exercise in gratefulness. You’ll finish the 5K grateful for some many things...including the great run you just ran</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An easy and inspiring 5K run. That’s just over 3 miles. This is a distance-based audio guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/grateful_5k_run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
