export const runs = [
	{
		id: "RUNNER_UP",
		properties: {
			activeGoal: 600.0,
			autodownload: false,
			goal: 1215.0,
			activityType: "SPEED_DURATION",
			
			previousId: "RUNNER_UP_ENGB",
			previousIds: ["RUNNER_UP_ENGB", "RUNNER_UP"],
		},
		landing: {
			title: "Runner\n Up",
			subtitle: "21 Min • Hill Workout",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/4c393503404657ddc46b4015eb8bb35b/runner-up.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/4c393503404657ddc46b4015eb8bb35b/runner-up.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Runner\n Up",
				subtitle: "21 Min • Hill Workout",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/4c393503404657ddc46b4015eb8bb35b/runner-up.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Let's go up! This super fun hill workout includes a series of short intervals of 45 and 15 seconds and is meant to be done on a hill or incline. Hills are a great way to become a better athlete and you'll work on speed and strength with every interval in this run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n<br>\nWorkout:<br>\n0:45 10K pace<br>\n0:15 Best pace<br>\n<br>\nRepeat series 5 times.<br>\n<br>\nRecovery intervals will vary between 45 and 75 seconds in duration.<br>\n<br>\n21 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/runner-up.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Blue",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their greatest potential.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "PREGNANCY_RUNNING_WHAT_TO_EXPECT",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "PREGNANCY_RUNNING_WHAT_TO_EXPECT_ENGB",
			previousIds: [
				"PREGNANCY_RUNNING_WHAT_TO_EXPECT_ENGB",
				"PREGNANCY_RUNNING_WHAT_TO_EXPECT",
			],
		},
		landing: {
			title: "Running & Pregnancy",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/91fdcec3a2a7cc97e10ee3d8335e93db/running-pregnancy.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/91fdcec3a2a7cc97e10ee3d8335e93db/running-pregnancy.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Running & Pregnancy",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/91fdcec3a2a7cc97e10ee3d8335e93db/running-pregnancy.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "On this 30-minute easy run we’ve got one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy. Join Jane and Coach Bennett for this easy run and end with the knowledge you need to navigate your own exercise through pregnancy or help someone do the same through theirs.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable, educational and inspirational 30 minute easy run or walk.\n\nTotal Experience: 30 Minutes\n\nThis information should be used as a guide only and is not a substitute for advice from a medical professional. Always consult a medical professional before engaging in a new exercise program and use your judgment for what feels right for you. If you feel faint, experience shortness of breath, dizziness, or related sensations while exercising, stop immediately and seek medical attention as necessary.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/running-pregnancy.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Jane Wake",
					body: "Jane Wake is one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUNNING_AND_YOGA",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			profiles: [],
			previousId: "RUNNING_&_YOGA_ENGB",
			previousIds: ["RUNNING_&_YOGA_ENGB"],
		},
		landing: {
			title: "Running & Yoga",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/33d40d98-eb4b-4f3f-b41d-93cf0f629d59/running-yoga.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/33d40d98-eb4b-4f3f-b41d-93cf0f629d59/running-yoga.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Running & Yoga",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/33d40d98-eb4b-4f3f-b41d-93cf0f629d59/running-yoga.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Want to improve your running? Want to remix your training and strengthen body and mind? In this easy 25-minute run, Coach Manni from Nike Running London puts Nike Training Club expert, yoga teacher and artist Sam Vora through her paces to talk all things yoga and find out how it can make you a better runner.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An easy 25-minute run to inspire you to find your inner yogi.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/running-yoga.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Manni",
					body: "<p>Manni Ovola is a Nike Run Club Coach and physiotherapist who treats all types of runners and is mad about running himself. He believes by helping people understand their bodies, he can bring out the most in them.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUNNING_FOR_CONNECTIONS",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "RUNNING_FOR_CONNECTIONS_ENGB",
			previousIds: ["RUNNING_FOR_CONNECTIONS_ENGB", "RUNNING_FOR_CONNECTIONS"],
		},
		landing: {
			title: "Running for More: Connections",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/679a5036389f5185ddaf5aaf8db4c814/running-for-more-connections.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/679a5036389f5185ddaf5aaf8db4c814/running-for-more-connections.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Running for More: Connections",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/679a5036389f5185ddaf5aaf8db4c814/running-for-more-connections.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Every run and all runners have connections -connections with the environment, the community, their body and minds, other runners and a connection with the sport. Over the course of this 25-minute easy run Coach Bennett will help you understand how those connections play a part in your running and how you can strengthen positive connections and break with bad ones.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and motivational 25-minute easy run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/running-for-more-connections.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUNNING_FOR_MORE_JOY",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",
			
			previousId: "RUNNING_FOR_MORE_JOY_ENGB",
			previousIds: ["RUNNING_FOR_MORE_JOY_ENGB"],
		},
		landing: {
			title: "Running For More: Joy",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/50890dd9-331f-4973-9f50-4828b4c223a6/running_for_more_joy.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/50890dd9-331f-4973-9f50-4828b4c223a6/running_for_more_joy.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Running For More: Joy",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/50890dd9-331f-4973-9f50-4828b4c223a6/running_for_more_joy.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>One of the necessary ingredients for long term success in running (and life) is joy. If you can find joy in your running, then you will find a joyful runner. And that’s the type of runner that will be able to find and cross starting lines over and over again. That is how running becomes a lifelong journey. Join Nike Running Global Head Coach Chris Bennett for this insightful and inspiring 35-minute easy run and be open to finding and running with more joy along the way.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and motivational 35-minute easy run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/running_for_more_joy.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUNNING_FOR_PURPOSE",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",
			
			previousId: "RUNNING_FOR_PURPOSE_ENGB",
			previousIds: ["RUNNING_FOR_PURPOSE_ENGB", "RUNNING_FOR_PURPOSE"],
		},
		landing: {
			title: "Running for More: Purpose",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/130da82382695643d7bc325849df8ef2/running-for-more-purpose.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/130da82382695643d7bc325849df8ef2/running-for-more-purpose.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Running for More: Purpose",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/130da82382695643d7bc325849df8ef2/running-for-more-purpose.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Every run has a purpose. Every run has many purposes. And if you can run with purpose, you will find that every run can end with you as a better version of yourself. Join Nike Running Global Head Coach Chris Bennett for this inspirational 20-minute easy run and explore the purpose of your own running.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and easy 20-minute recovery run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/running-for-more-purpose.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUNNING_FOR_MORE_SUCCESS",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "RUNNING_FOR_MORE_SUCCESS_ENGB",
			previousIds: [
				"RUNNING_FOR_MORE_SUCCESS_ENGB",
				"RUNNING_FOR_MORE_SUCCESS",
			],
		},
		landing: {
			title: "Running For More: Success",
			subtitle: "30 min. • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a428a6a67b7a1ced639c903a2ccabcca/running-for-more-success.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a428a6a67b7a1ced639c903a2ccabcca/running-for-more-success.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Running For More: Success",
				subtitle: "30 min. • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a428a6a67b7a1ced639c903a2ccabcca/running-for-more-success.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Measure success as many ways as you can and you'll be able to find success in every one of your runs. Over the course of this 30-minute Recovery Run, Coach Bennett will work to uncover and celebrate all the success your running offers you with every minute, metre and mile covered.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run details",
					body: "A relaxed and inspirational 30-minute easy run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/running-for-more-success.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUNNING_HIGHS",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "RUNNING_HIGHS_ENGB",
			previousIds: ["RUNNING_HIGHS_ENGB", "RUNNING_HIGHS"],
		},
		landing: {
			title: "Running Highs",
			subtitle: "30 Min • Treadmill Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/4ead5c39fa539d96e763297687245b50/running-highs.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/4ead5c39fa539d96e763297687245b50/running-highs.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Running Highs",
				subtitle: "30 Min • Treadmill Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/4ead5c39fa539d96e763297687245b50/running-highs.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join NRC Los Angeles Coach Blue Benadum on this hilly 30 minute recovery run. This run is made specially for the treadmill and will have you running up a series of hills and most importantly, learning how to make the treadmill a fun experience.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "30 minute recovery run specially made for the treadmill. You will receive guidance on how to adjust the elevation and speed over the course of the run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/running-highs.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Blue",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their greatest potential.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUNNING_IN_THE_DARK",
		properties: {
			activeGoal: 2880.0,
			autodownload: false,
			goal: 2880.0,
			activityType: "DURATION",
			
			previousId: "RUNNING_IN_THE_DARK_ENGB",
			previousIds: ["RUNNING_IN_THE_DARK_ENGB", "RUNNING_IN_THE_DARK"],
		},
		landing: {
			title: "Running In The Dark",
			subtitle: "48 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/18fefd8956749e62ed07479c4fbc6998/running-in-the-dark.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/18fefd8956749e62ed07479c4fbc6998/running-in-the-dark.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Running In The Dark",
				subtitle: "48 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/18fefd8956749e62ed07479c4fbc6998/running-in-the-dark.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Getting your run in is a big deal. And sometimes that means running in the dark. Join Nike Running Global Head Coach on this easy 48 minute run and get tips and guidance on how to run your best and safest when daylight is at a minimum.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 48 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/running-in-the-dark.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUNNING_ON_EMPTY_WITH_HEADSPACE",
		properties: {
			activeGoal: 1920.0,
			autodownload: false,
			goal: 1920.0,
			activityType: "DURATION",
			
			previousId: "RUNNING_ON_EMPTY_WITH_HEADSPACE_ENGB",
			previousIds: [
				"RUNNING_ON_EMPTY_WITH_HEADSPACE_ENGB",
				"RUNNING_ON_EMPTY_WITH_HEADSPACE",
			],
		},
		landing: {
			title: "Running On Empty w/ Headspace",
			subtitle: "32 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/740c6bdc7ec0ec58ca3d1648b0152d78/running-on-empty-w-headspace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/740c6bdc7ec0ec58ca3d1648b0152d78/running-on-empty-w-headspace.png",
			backgroundColor: "#FED48C",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FED48C",
			headerCard: {
				title: "Running On Empty w/ Headspace",
				subtitle: "32 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/740c6bdc7ec0ec58ca3d1648b0152d78/running-on-empty-w-headspace.png",
				backgroundColor: "#FED48C",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Sometimes you feel like you're starting your run on empty. Headspace co-founder Andy Puddicombe and Nike Global Head Coach Chris Bennett make sure you end this relaxed 32 minute run feeling energized and in the moment.",
					titleColor: "#FFFFFF",
					backgroundColor: "#55505A",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed 32 minute run with 1 minute of post-run guidance and cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#55505A",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run With Headspace",
					url: "https://static.nike.com/ntc-prod/images/5033e66339bd97b48b8b2836045e19f5/running-on-empty-w-headspace.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#55505A",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-headspace/pl.5599ee1dc0e048bda9d11c65deb6a150",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/5UeYUUQnTy2amoVm6Tbmeb",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "Andy Puddicombe is the co-founder of Headspace and an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#FFFFFF",
					backgroundColor: "#55505A",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HS_RUNNING_TOWARDS_YOUR_GOAL",
		properties: {
			activeGoal: 2400.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "Running Towards Your Goal",
			subtitle: "40 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f8ed9177b1c2e138075da2a5d07ab306/running-towards-your-goal.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f8ed9177b1c2e138075da2a5d07ab306/running-towards-your-goal.png",
			backgroundColor: "#66D2CE",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#66D2CE",
			headerCard: {
				title: "Running Towards Your Goal",
				subtitle: "40 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f8ed9177b1c2e138075da2a5d07ab306/running-towards-your-goal.png",
				backgroundColor: "#66D2CE",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Setting a goal is brave. Achieving that goal takes determination, mindfulness and motivation. Join Andy Puddicombe of Headspace and NRC Global Head Coach Chris Bennett for an inspiring 40 minute run. You’ll end closer to the goals you set for yourself.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 40 minute recovery run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/running-towards-your-goal.png",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_STRONG_REPEAT",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1680.0,
			activityType: "SPEED_DURATION",
			
			previousId: "RUN_STRONG_REPEAT_ENGB",
			previousIds: ["RUN_STRONG_REPEAT_ENGB", "RUN_STRONG_REPEAT"],
		},
		landing: {
			title: "Run Strong. \nRepeat.",
			subtitle: "30 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7f82e232fef270daae04c27420246c8f/run-strong-repeat.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7f82e232fef270daae04c27420246c8f/run-strong-repeat.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Run Strong. \nRepeat.",
				subtitle: "30 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7f82e232fef270daae04c27420246c8f/run-strong-repeat.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This speed run is a strength based workout. Short rest will make sure you are dependent on your endurance as you recover quickly and get back on the line. And two intervals at your mile pace are sure to add some excitement to the run!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n1:30 5k pace<br>\n1:30 5k pace<br>\n1:30 5k pace<br>\n1:30 5k pace<br>\n1:30 Mile pace<br>\n1:30 5k pace<br>\n1:30 5k pace<br>\n1:30 5k pace<br>\n1:30 5k pace<br>\n1:30 Mile pace<br>\n<br>\nRecovery intervals vary between 45 seconds and 1 minute.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run Strong. Repeat.",
					url: "https://static.nike.com/ntc-prod/images/6e9413b8ebbc64a71af7dec9755eb481/run-strong-repeat.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-strong-repeat/idpl.1f7370f6bd034680ac0089fd376d0014",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/07FCmlZCSSv5q4Is51gx76",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently the Nike Run Club DC Head Coach.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_BIANCA",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_BIANCA_ENGB",
			previousIds: ["RUN_WITH_BIANCA_ENGB", "RUN_WITH_BIANCA"],
		},
		landing: {
			title: "Run With Bianca",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/cfe762a95b3e9558d5fd5fc2424a2764/run-with-bianca.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/cfe762a95b3e9558d5fd5fc2424a2764/run-with-bianca.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Run With Bianca",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/cfe762a95b3e9558d5fd5fc2424a2764/run-with-bianca.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join world class British sprinter Bianca Williams on this 20-minute easy run (or walk… you decide!) as she talks motherhood and training with Jane Wake - one of the leading experts on pre and postnatal exercise and training and London NRC Coach Dora Atim.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable, educational and motivational 20-minute easy run or walk with one minute of post run inspiration.\n\nTotal Experience: 20 Minutes\n\nThis information should be used as a guide only and is not a substitute for advice from a medical professional. Always consult a medical professional before engaging in a new exercise program and use your judgment for what feels right for you. If you feel faint, experience shortness of breath, dizziness, or related sensations while exercising, stop immediately and seek medical attention as necessary.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-with-bianca.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bianca",
					body: "Bianca Williams is a world class sprinter from England. Williams has medaled at both the World Relays and Commonwealth Games. Jane Wake is one of the leading experts on pre and postnatal exercise and training! Coach Dora is a Nike Running London Coach as well as a  fitness coach. Coach Dora is also one of the founding members of the Last Pick AC.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_CHARLIE_ROCKET",
		properties: {
			activeGoal: 1830.0,
			autodownload: false,
			goal: 1830.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_CHARLIE_ROCKET_ENGB",
			previousIds: ["RUN_WITH_CHARLIE_ROCKET_ENGB", "RUN_WITH_CHARLIE_ROCKET"],
		},
		landing: {
			title: "Run With Charlie Rocket",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5a0a0dc64422648d5b3b520364aaf433/run-with-charlie-rocket.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5a0a0dc64422648d5b3b520364aaf433/run-with-charlie-rocket.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With Charlie Rocket",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5a0a0dc64422648d5b3b520364aaf433/run-with-charlie-rocket.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: 'Want to know what it takes to achieve your crazy dream? Charlie Jabaley a.k.a. "Charlie Rocket" joins Nike Run Club LA Coach Blue Benadum to share his story of overcoming adversity and achieving his crazy dream of becoming a Nike athlete.',
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute easy run.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-with-charlie-rocket.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Blue",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their greatest potential.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_DAPAAH",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Run With Dapaah",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/2dd7cad00d55bce5c89410adc6d0c301/run-with-dapaah.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/2dd7cad00d55bce5c89410adc6d0c301/run-with-dapaah.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With Dapaah",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/2dd7cad00d55bce5c89410adc6d0c301/run-with-dapaah.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "London Comedian Michael Dapaah is taking on the running world one run at a time. Fresh from going head to head with British legend Sir Mo Farah over 26 miles, Dapaah isn’t finished yet. Join him and NRC Coach Cory for an easy 20 minute run.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 20 minute run with 1 minute of post run guidance.\n\nThis run features Dapaah's favourite tracks and is best experienced with the selected music.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run With Dapaah",
					url: "https://static.nike.com/ntc-prod/images/b2a46314c1a79c5c6d049593e5f0a26c/run-with-dapaah.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-michael-agr-music/pl.31b0090b8b2646e5bb7c6a0008465cbc",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/3wVnTy0OdcdCR8dHW7bPD0",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Michael Dapaah",
					body: "Michael Dapaah is a London-based comedian and rapper, most well-known for his characters Big Shaq and Dr. Ofori.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_ELIUD",
		properties: {
			activeGoal: 3600.0,
			autodownload: false,
			goal: 3600.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_ELIUD_ENGB",
			previousIds: ["RUN_WITH_ELIUD_ENGB", "RUN_WITH_ELIUD"],
		},
		landing: {
			title: "Run\n With Eliud",
			subtitle: "60 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/2c2d765239cc40da89a59fa3db6d8d98/run-with-eliud.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/2c2d765239cc40da89a59fa3db6d8d98/run-with-eliud.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run\n With Eliud",
				subtitle: "60 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/2c2d765239cc40da89a59fa3db6d8d98/run-with-eliud.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "No one runs long better than Eliud Kipchoge, the worlds greatest marathoner. Join Eliud on this 60 minute guided run and you'll get better and better the longer you go.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 60 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run With Eliud",
					url: "https://static.nike.com/ntc-prod/images/965cb511f4b9994d4f1cd61029d2a11c/run-with-eliud.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-eliud/pl.38bd55cbec064ebc99bc5bebfdf77e53",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/3gJX84BBycAJ11ddL7TNp4",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Eliud Kipchoge",
					body: "Eliud Kipchoge is the Olympic Gold Medalist as well as the winner of the Berlin, Chicago and London Marathons. Kipchoge ran 2 hours and 25 seconds for the marathon distance during the Breaking2 event in Italy. Coach Bennett joins Eliud for the run.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_HEADSPACE",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_HEADSPACE_ENGB",
			previousIds: ["RUN_WITH_HEADSPACE_ENGB", "RUN_WITH_HEADSPACE"],
		},
		landing: {
			title: "Run With Headspace",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/412a66674651f7418d62ef9926d02afe/run-with-headspace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/412a66674651f7418d62ef9926d02afe/run-with-headspace.png",
			backgroundColor: "#E76770",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#E76770",
			headerCard: {
				title: "Run With Headspace",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/412a66674651f7418d62ef9926d02afe/run-with-headspace.png",
				backgroundColor: "#E76770",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Experience a greater clarity of mind with Andy Puddicombe, co-founder of Headspace and former Buddhist monk, as he joins Nike Head Coach Chris Bennett on this 30-minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute recovery run with 2 minutes of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run With Headspace",
					url: "https://static.nike.com/ntc-prod/images/5033e66339bd97b48b8b2836045e19f5/run-with-headspace.png",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-headspace/pl.5599ee1dc0e048bda9d11c65deb6a150",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/5UeYUUQnTy2amoVm6Tbmeb",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#413D45",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_JOANIE",
		properties: {
			activeGoal: 3900.0,
			autodownload: false,
			goal: 3900.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_JOANIE_ENGB",
			previousIds: ["RUN_WITH_JOANIE_ENGB", "RUN_WITH_JOANIE"],
		},
		landing: {
			title: "Run With Joanie",
			subtitle: "65 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/6f10aaad69aeade802e112e0dad517e0/run-with-joanie.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/6f10aaad69aeade802e112e0dad517e0/run-with-joanie.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Run With Joanie",
				subtitle: "65 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/6f10aaad69aeade802e112e0dad517e0/run-with-joanie.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join living legend Joan Benoit Samuelson as she tells her incredible life story on this relaxed 65 minute run. JBS is the winner of the first-ever Women's Olympic Marathon. Joanie won the Boston and Chicago Marathons and broke 2:50 for the marathon at age 50! She is truly one of the greatest and most inspiring runners of all-time. JBS is interviewed on this run by her daughter, Abby Samuelson. You'll end this run more inspired than ever to be the best you can be.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 65 minute easy run with 1 minute of post run guidance, motivation and inspiration.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/run-with-joanie.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Joan Benoit Samuelson",
					body: "Joan Benoit Samuelson won the first-ever Women's Olympic Marathon at the 1984 LA Games. She won Boston & Chicago Marathons & held the American Record for 18 years when she ran 2:21:21 in 1985. At the 2008 Olympic Trials, at age 50, JBS ran 2:49:08.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_LOPEZ_1",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_LOPEZ_1_ENGB",
			previousIds: ["RUN_WITH_LOPEZ_1_ENGB", "RUN_WITH_LOPEZ_1"],
		},
		landing: {
			title: "Run With Lopez\n Part 1",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-1.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-1.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With Lopez\n Part 1",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-1.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This is Part 1 of Run with Lopez Lomong and his epic story. Lopez was one of the Lost Boys of Sudan. His story is one of tragedy and triumph, horror and hope, and the power of family. Run and listen as Lopez runs from war to the greatest stage in sport.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-with-lopez-part-1.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Lopez Lomong",
					body: "Lopez Lomong is one of the best runners in the world. He was a Lost Boy of Sudan living in a refugee camp in Kenya for ten years. Lopez was an Olympian and flag bearer for the US in 2008. He's a member of the Bowerman Track Club.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_LOPEZ_2",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_LOPEZ_2_ENGB",
			previousIds: ["RUN_WITH_LOPEZ_2_ENGB", "RUN_WITH_LOPEZ_2"],
		},
		landing: {
			title: "Run With Lopez\n Part 2",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-2.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-2.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With Lopez\n Part 2",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-2.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This is Part 2 of 3 of the Run with Lopez and his epic story. Lopez was one of the Lost Boys of Sudan. His story is one of tragedy and triumph, horror and hope, and the power of family. Run and listen as Lopez runs from war to the greatest stage in sport.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-with-lopez-part-2.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Lopez Lomong",
					body: "Lopez Lomong is one of the best runners in the world. He was a Lost Boy of Sudan living in a refugee camp in Kenya for ten years. Lopez was an Olympian and flag bearer for the US in 2008. He's a member of the Bowerman Track Club.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_LOPEZ_3",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_LOPEZ_3_ENGB",
			previousIds: ["RUN_WITH_LOPEZ_3_ENGB", "RUN_WITH_LOPEZ_3"],
		},
		landing: {
			title: "Run With Lopez\n Part 3",
			subtitle: "30 min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-3.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-3.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With Lopez\n Part 3",
				subtitle: "30 min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-part-3.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This is Part 3 of 3 of the Run with Lopez and his epic story. Lopez was one of the Lost Boys of Sudan. His story is one of tragedy and triumph, horror and hope, and the power of family. Run and listen as Lopez runs from war to the greatest stage in sport.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/run-with-lopez-part-3.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Lopez Lomong",
					body: "Lopez Lomong is one of the best runners in the world. He was a Lost Boy of Sudan living in a refugee camp in Kenya for ten years. Lopez was an Olympian and flag bearer for the US in 2008. He's a member of the Bowerman Track Club.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_LOPEZ_FULL",
		properties: {
			activeGoal: 5400.0,
			autodownload: false,
			goal: 5400.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_LOPEZ_FULL_ENGB",
			previousIds: ["RUN_WITH_LOPEZ_FULL_ENGB", "RUN_WITH_LOPEZ_FULL"],
		},
		landing: {
			title: "Run With Lopez\n Parts 1-3",
			subtitle: "90 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-parts-1-3.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-parts-1-3.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With Lopez\n Parts 1-3",
				subtitle: "90 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a22b3f432f50eba38280dbd5f90d1502/run-with-lopez-parts-1-3.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Run with Lopez Lomong and hear his epic story. Lopez was one of the Lost Boys of Sudan. His story is one of tragedy and triumph, horror and hope, and the power of family. Run and listen as Lopez runs from war to the greatest stage in sport.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 90 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/run-with-lopez-parts-1-3.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Lopez Lomong",
					body: "Lopez Lomong is one of the best runners in the world. He was a Lost Boy of Sudan living in a refugee camp in Kenya for ten years. Lopez was an Olympian and flag bearer for the US in 2008. He's a member of the Bowerman Track Club.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_MANAL",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_MANAL_ENGB",
			previousIds: ["RUN_WITH_MANAL_ENGB", "RUN_WITH_MANAL"],
		},
		landing: {
			title: "Run With Manal",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7c7d52edeee94763666a9fb51b6b9322/run-with-manal.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7c7d52edeee94763666a9fb51b6b9322/run-with-manal.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run With Manal",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7c7d52edeee94763666a9fb51b6b9322/run-with-manal.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join NRC Dubai Coach Manal Rostom on this 25 minute easy run. Her extraordinary story will inspire and motivate you along the way.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 25 minute easy run with 1 minute of post run guidance and cooldown.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run With Manal",
					url: "https://static.nike.com/ntc-prod/images/e69fee1669e46725fd6e7f5773741c12/run-with-manal.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-manal/pl.c5c52c3a0a0c42888f2ebd3d4b59eb0a",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/7rAvvTCncwsglUkYX7XWFl",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Manal Rostom",
					body: "Dubai Nike Run Club coach Manal Rostom has accomplished many firsts throughout her life by competing in major marathons and reaching the highest peaks of the world. She is breaking barriers for women’s sports in the Middle East and inspiring thousands to get active every day.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_MO_RUN",
		properties: {
			activeGoal: 1530.0,
			autodownload: false,
			goal: 2190.0,
			activityType: "SPEED_DURATION",
			
			previousId: "RUN_WITH_MO_RUN_ENGB",
			previousIds: ["RUN_WITH_MO_RUN_ENGB", "RUN_WITH_MO_RUN"],
		},
		landing: {
			title: "Run\n With Mo",
			subtitle: "37 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/a05e80e532fb947c67f53b8d7038fc02/run-with-mo.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/a05e80e532fb947c67f53b8d7038fc02/run-with-mo.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Run\n With Mo",
				subtitle: "37 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/a05e80e532fb947c67f53b8d7038fc02/run-with-mo.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Run with one of the greatest distance runners in the world. Sir Mo Farah will be by your side for this fun workout that works your speed and strength. It will leave you wanting Mo!",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n2:00 5k pace<br>\n2:00 5k pace<br>\n4:00 10k pace<br>\n1:00 Mile pace<br>\n1:00 Mile pace<br>\n2:00 5k pace<br>\n2:00 5k pace<br>\n4:00 10k pace<br>\n1:00 Mile pace<br>\n1:00 Mile pace<br>\n0:30 Best pace<br>\n<br>\nRecovery intervals will be 1 minute.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Run with Mo",
					url: "https://static.nike.com/ntc-prod/images/b96d12a18e844e9034b8e2a6e8027f66/run-with-mo.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/run-with-mo/idpl.f251e64dcede4953a5aa85e3b2b66723",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4AmX8IcqtBnBvVlFikLaB2",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Mo Farah",
					body: "Sir Mo Farah is one of the world's greatest distance runners and a 4-time Olympic gold medalist. He won the 5k and 10k at both the 2012 London and 2016 Rio Olympic Games.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_PAULA",
		properties: {
			activeGoal: 2400.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_PAULA_ENGB",
			previousIds: ["RUN_WITH_PAULA_ENGB", "RUN_WITH_PAULA"],
		},
		landing: {
			title: "Run With Paula",
			subtitle: "40 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/89d9ca70bc5a728c49663a169b53422e/run-with-paula.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/89d9ca70bc5a728c49663a169b53422e/run-with-paula.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Run With Paula",
				subtitle: "40 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/89d9ca70bc5a728c49663a169b53422e/run-with-paula.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Join Marathon World Record Holder Paula Radcliffe on this easy 40 minute run. Radcliffe shares her incredible story that will have you ending this run motivated and inspired. Nike Running London Coach Cory Wharton-Malcolm joins Radcliffe on this run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 40 minute easy run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/run-with-paula.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Paula Radcliffe",
					body: "Paula Radcliffe has run the fastest marathon ever by a woman. Her time of 2:15:25 has stood as World Record since 2003. She has won marathons in Chicago, London, and New York and has been World Champion in XC and on the roads.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
