export const runs = [
	{
		id: "6_WEEKS_TO_GO_ENGB",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
			previousId: "6_WEEKS_TO_GO",
			previousIds: ["6_WEEKS_TO_GO"],
		},
		landing: {
			title: "6 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/18cc0053906c9244fe467b7cc3402496/6-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/18cc0053906c9244fe467b7cc3402496/6-weeks-to-go.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "6 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/18cc0053906c9244fe467b7cc3402496/6-weeks-to-go.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 6  weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/6-weeks-to-go.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "7K_RUN",
		properties: {
			activeGoal: 7000.0,
			autodownload: false,
			goal: 7000.0,
			activityType: "DISTANCE",
			
			previousId: "7K_RUN_ENGB",
			previousIds: ["7K_RUN_ENGB", "7K_RUN"],
		},
		landing: {
			title: "7K Run",
			subtitle: "7K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/bb13193b98663f454420b733fc869917/7k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/bb13193b98663f454420b733fc869917/7k-run.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "7K Run",
				subtitle: "7K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/bb13193b98663f454420b733fc869917/7k-run.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The 7K Run (just less than 4.50 miles) is an awesome distance. It’s not 5K or 10K and it’s not 4 miles or 5 miles. It’s 7K! And 7K is more than okay… it’s great! Join Nike Running Global Head Coach Chris Bennett on this comfortable 7K distance-based guided run. You’ll get the motivation, inspiration and guidance you need to have a better run. Be prepared for a fun run and get ready to celebrate!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 7K run. That’s just a little less than 4.50 miles… 4.35 miles actually. This is a distance-based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/7k-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "7_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "7 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/91a26f69193483e324b5fc86737db3e1/7-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/91a26f69193483e324b5fc86737db3e1/7-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "7 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/91a26f69193483e324b5fc86737db3e1/7-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 7  weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/7-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "80'S_RUN",
		properties: {
			activeGoal: 1560.0,
			autodownload: false,
			goal: 1560.0,
			activityType: "SPEED_DURATION",
			
			previousId: "80'S_RUN_ENGB",
			previousIds: ["80'S_RUN_ENGB"],
		},
		landing: {
			title: "80's",
			subtitle: "26 Min • Speed Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/101787fb-d6f6-4036-855b-b1791f7139b5/80-s_run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/101787fb-d6f6-4036-855b-b1791f7139b5/80-s_run.png",
			backgroundColor: "#D4FF2A",
			titleColor: "#111111",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D4FF2A",
			headerCard: {
				title: "80's",
				subtitle: "26 Min • Speed Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/101787fb-d6f6-4036-855b-b1791f7139b5/80-s_run.png",
				backgroundColor: "#D4FF2A",
				titleColor: "#111111",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Who doesn’t love the 80’s? We’re talking about the 80 seconds intervals you’re going to do… not the decade. (The decade had some cool stuff too. But nothing as electric as this speed run.) Join Coach Chelsea Cox for this always moving and always fun speed run. You’ll have eight 80 seconds running intervals with… you guessed it… 80 seconds recovery after each. So, go get that epic 80’s playlist cued up because it’s time to roll!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n80 seconds @ 10K Pace<br>\n2 x 80 seconds @ 5K Pace<br>\n80 seconds @ Mile/1500m Pace<br>\n<br>\nRepeat entire set again for total of 8 intervals<br>\n<br>\nRecovery will be 80 seconds after each interval<br>\n<br>\n26:00 Total Experience</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/80-s_run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently a Nike Run Club North America Coach based out of North Carolina. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "8K_RUN",
		properties: {
			activeGoal: 8002.0,
			autodownload: false,
			goal: 8002.0,
			activityType: "DISTANCE",
			
			previousId: "8K_RUN_ENGB",
			previousIds: ["8K_RUN_ENGB"],
		},
		landing: {
			title: "8K Run",
			subtitle: "8K • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/543a1666-296b-4a96-8185-def280dd897f/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/543a1666-296b-4a96-8185-def280dd897f/image.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "8K Run",
				subtitle: "8K • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/543a1666-296b-4a96-8185-def280dd897f/image.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The 8K Run (4.97 miles) is an awesome distance. It’s more than the ever-popular 5K Run and it’s less than the classic 10K. Somewhere Goldilocks is running an 8K. You can be sure of that! Join Nike Running Global Head Coach Chris Bennett on this fun 8K distance-based guided run. On this relaxed run you’ll get all the guidance you need, as well as the motivation and inspiration, to have a better run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p><br>\nA comfortable and fun 8K run. That’s just less than 5 miles. This is a distance-based audio guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "8K_TEMPO_RUN",
		properties: {
			activeGoal: 12004.0,
			autodownload: false,
			goal: 12004.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "8K Tempo Run",
			subtitle: "12K • Tempo Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/b317fdce4359d3a84596e2d5f13e6881/8k-tempo-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/b317fdce4359d3a84596e2d5f13e6881/8k-tempo-run.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "8K Tempo Run",
				subtitle: "12K • Tempo Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/b317fdce4359d3a84596e2d5f13e6881/8k-tempo-run.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The Tempo Run is one of the essential ingredients in any successful running recipe. Join Nike Running Global Head Coach on this 8K Tempo Run. You’ll warm up 2K and then roll right into a distance based guided Tempo Run. Learning how to get comfortable with being uncomfortable is the goal of the run… well, that and having a great time doing it!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>2000m/~1.25 Miles Warm Up<br>\n8000m/~5.0 Miles Tempo Run<br>\n2000m/~1.25 Miles Cool Down<br>\n12000m/~7.5 miles Total Distance<br>\n<br>\nThis is a distance based guided Speed Run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/8k-tempo-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "8_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "8 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/13c3161277612a8bae877984dc23ccd0/8-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/13c3161277612a8bae877984dc23ccd0/8-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "8 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/13c3161277612a8bae877984dc23ccd0/8-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 8 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/8-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "90S_RUN",
		properties: {
			activeGoal: 1110.0,
			autodownload: false,
			goal: 1890.0,
			activityType: "SPEED_DURATION",
			
			previousId: "90s_RUN_ENGB",
			previousIds: ["90s_RUN_ENGB", "90s_RUN"],
		},
		landing: {
			title: "90's",
			subtitle: "31 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/09f024273cfe9a1c078ac974c69757e5/90-s.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/09f024273cfe9a1c078ac974c69757e5/90-s.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "90's",
				subtitle: "31 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/09f024273cfe9a1c078ac974c69757e5/90-s.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The recipe is nine 90 second intervals with 90 seconds of recovery between each. You'll be guided by Coach Cory through 3 interval sets, running each at a different pace. The first set is at your 5K pace, followed by a set at your 10K pace and the workout ends with a set at your Mile pace.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n1:30 5K pace (repeat 3 times)<br>\n1:30 10K pace (repeat 3 times)<br>\n1:30 Mile pace (repeat 3 times)<br>\n<br>\nRecovery intervals will be 90 seconds in duration.<br>\n<br>\n33 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/90-s.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "90_MINUTE_RUN",
		properties: {
			activeGoal: 5400.0,
			autodownload: false,
			goal: 5400.0,
			activityType: "DURATION",
			
			previousId: "90_MINUTE_RUN_ENGB",
			previousIds: ["90_MINUTE_RUN_ENGB", "90_MINUTE_RUN"],
		},
		landing: {
			title: "90 Minute Run",
			subtitle: "90 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/96cd95a480b3ede86692994f06bdaf2b/90-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/96cd95a480b3ede86692994f06bdaf2b/90-minute-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "90 Minute Run",
				subtitle: "90 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/96cd95a480b3ede86692994f06bdaf2b/90-minute-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Don't just run long... run long the right way. Join Nike Running Global Head Coach Bennett on this 90 minute guided run. Coach will be alongside you the entire way guiding, motivating, inspiring and coaching you to your best & most fun long run yet!",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 90 minute guided run with 1 minute of post run cool down and inspiration.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/90-minute-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "99_MIN_59_SECONDS",
		properties: {
			activeGoal: 6000.0,
			autodownload: false,
			goal: 6000.0,
			activityType: "DURATION",
			
			previousId: "99_MIN_59_SECONDS_ENGB",
			previousIds: ["99_MIN_59_SECONDS_ENGB", "99_MIN_59_SECONDS"],
		},
		landing: {
			title: "99 Minutes 59 Seconds Run",
			subtitle: "99 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/8c1d5ecd0ed2a240b0c53b511e65b5bd/99-minutes-59-seconds-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/8c1d5ecd0ed2a240b0c53b511e65b5bd/99-minutes-59-seconds-run.png",
			backgroundColor: "#FF5500",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "99 Minutes 59 Seconds Run",
				subtitle: "99 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/8c1d5ecd0ed2a240b0c53b511e65b5bd/99-minutes-59-seconds-run.png",
				backgroundColor: "#FF5500",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It’s not 100 minutes (unless you add on one second)… it’s the 99 Minutes 59 Seconds Run. Join Nike Running Global Head Coach Chris Bennett for this fun and inspiring long run. You’ll learn how to run in the moment and how to run efficiently so every run becomes a better run the longer you run. So, fuel up and get yourself to the starting line. We’ll meet you there and help you get to the end of this run as a better version of you. This run is so good… you may even want to add on one second of running at the end!",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and controlled 99-minute and 59 seconds run.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/99-minutes-59-seconds-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that built the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "9K_RUN",
		properties: {
			activeGoal: 9002.0,
			autodownload: false,
			goal: 8999.0,
			activityType: "DISTANCE",
			
			previousId: "9K_RUN_ENGB",
			previousIds: ["9K_RUN_ENGB"],
		},
		landing: {
			title: "9K Run",
			subtitle: "9K • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/8149c802-66e5-4ea4-abfb-a3e50579ead7/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/8149c802-66e5-4ea4-abfb-a3e50579ead7/image.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "9K Run",
				subtitle: "9K • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/8149c802-66e5-4ea4-abfb-a3e50579ead7/image.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Get ready to cross the starting line of the 9K Run with Nike Running Global Head Coach Chris Bennett. 9K is just over 5.5 miles and is a great distance to both build endurance and learn about yourself as a runner. Coach Bennett makes sure that you run the right way and have some serious fun while you do. So, get on those trainers and get started on the 9K Run!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p> A fun and motivational 9K run. 9K is just over 5.5 miles. This is a distance-based audio guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "9_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "9 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5b299bf9b9c54a2d71250a66cef29454/9-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5b299bf9b9c54a2d71250a66cef29454/9-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "9 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5b299bf9b9c54a2d71250a66cef29454/9-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 9 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/9-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "COLD_RUN",
		properties: {
			activeGoal: 2700.0,
			autodownload: false,
			goal: 2700.0,
			activityType: "DURATION",
			
			previousId: "COLD_RUN_ENGB",
			previousIds: ["COLD_RUN_ENGB", "COLD_RUN"],
		},
		landing: {
			title: "A Cold Run",
			subtitle: "45 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/3aeecd5417e77009ded74e43044dab31/a-cold-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/3aeecd5417e77009ded74e43044dab31/a-cold-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "A Cold Run",
				subtitle: "45 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/3aeecd5417e77009ded74e43044dab31/a-cold-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "A cold run can still be a great run. Join NRC Head Coach Chris Bennett on this easy 45 minute run. Coach talks about everything from which direction to start a cold run to how best to layer gear in chilly temps. A smarter runner is a better runner.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 45 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/a-cold-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "HOT_RUN",
		properties: {
			activeGoal: 2100.0,
			autodownload: false,
			goal: 2100.0,
			activityType: "DURATION",
			
			previousId: "HOT_RUN_ENGB",
			previousIds: ["HOT_RUN_ENGB", "HOT_RUN"],
		},
		landing: {
			title: "A Hot Run",
			subtitle: "35 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/1f68f0b67244766ef8b4f8cafac23604/a-hot-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/1f68f0b67244766ef8b4f8cafac23604/a-hot-run.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "A Hot Run",
				subtitle: "35 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/1f68f0b67244766ef8b4f8cafac23604/a-hot-run.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "A hot run can still be a great run. Join Nike Running Head Coach Chris Bennett on this 35 minute easy run. Coach talks about everything from hydration to the best time of day to run. You'll learn how to end a hot run cooler... and better.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 35 minute run with 1 minute of post run cool down and guidance.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/a-hot-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ALL_OVER_THE_PACE",
		properties: {
			activeGoal: 1245.0,
			autodownload: false,
			goal: 1920.0,
			activityType: "SPEED_DURATION",
			
			previousId: "ALL_OVER_THE_PACE_ENGB",
			previousIds: ["ALL_OVER_THE_PACE_ENGB", "ALL_OVER_THE_PACE"],
		},
		landing: {
			title: "All Over\n The Pace",
			subtitle: "33 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/2722317ff6be83aa653bf7ec7b7cbe57/all-over-the-pace.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/2722317ff6be83aa653bf7ec7b7cbe57/all-over-the-pace.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "All Over\n The Pace",
				subtitle: "33 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/2722317ff6be83aa653bf7ec7b7cbe57/all-over-the-pace.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Every runner owns a fast, faster, and fastest and this seriously fun Speed Run will make sure you have the chance to experience them all. Join Coach Becs Gentry as you run All Over The Pace.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n2:00 Recovery pace<br>\n1:00 10K pace<br>\n1:00 10K pace<br>\n0:45 5K pace<br>\n0:30 Mile pace<br>\n0:30 Mile pace<br>\n2:00 Recovery pace<br>\n0:30 Mile pace<br>\n1:00 5K pace<br>\n1:30 10K pace<br>\n2:00 Recovery pace<br>\n3:00 All paces<br>\n<br>\nRecovery intervals vary between 30 seconds and 1 minute.<br>\n<br>\n33 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "All Over The Pace",
					url: "https://static.nike.com/ntc-prod/images/75deac3bc934b94cee1f38c6ca1b6f93/all-over-the-pace.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/all-over-the-pace/pl.f2e82e042cb344be9e52cf8a9f587238",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/3ysJvoDFtzyaM7bzm3eU7J",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Becs",
					body: "Coach Becs Gentry is an NRC London Coach. Gentry has been a competitive runner for years as well. Gentry knows that the best way to run your best is to enjoy the run. Coach Becs infuses her coaching with passion and joy and the result is your best run yet.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "A_NEW_RUN_2021",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
			
			previousId: "A_NEW_RUN_2021_ENGB",
			previousIds: ["A_NEW_RUN_2021_ENGB", "A_NEW_RUN_2021"],
		},
		landing: {
			title: "A New Run",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/2bd95ff701258138248ba3670352d44d/a-new-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/2bd95ff701258138248ba3670352d44d/a-new-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "A New Run",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/2bd95ff701258138248ba3670352d44d/a-new-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Every run begins on a new starting line. And every starting line gets crossed by a new runner... the latest and greatest version of you. We can start, start over, start again with every run we begin. Join Nike Running Global Head Coach Chris Bennett on this 25-minute recovery run and be guided through an exercise in mindfully approaching every run as a new beginning.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and motivation 25-minute recovery run with one minute of post run motivation.\n\nTotal Experience: 25 minutes",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/a-new-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ANOTHER_10K",
		properties: {
			activeGoal: 10002.0,
			autodownload: false,
			goal: 10002.0,
			activityType: "DISTANCE",
			
			previousId: "ANOTHER_10K_ENGB",
			previousIds: ["ANOTHER_10K_ENGB", "ANOTHER_10K"],
		},
		landing: {
			title: "Another 10K Run",
			subtitle: "10K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/509d8068198222ba992e5433d892b9bd/another-10k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/509d8068198222ba992e5433d892b9bd/another-10k-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Another 10K Run",
				subtitle: "10K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/509d8068198222ba992e5433d892b9bd/another-10k-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "It's 10K time again! Join Nike Running Head Coach Chris Bennett on this distance based run. We had such a great time on the first 10K Run that we just had to do another. You'll get coaching, guidance and inspiration throughout this fun run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and easy 10K run. This is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/another-10k-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ANOTHER_5K",
		properties: {
			activeGoal: 5002.0,
			autodownload: false,
			goal: 5002.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "Another 5K Run",
			subtitle: "5K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/0fe25693f35af2961376b36484534c46/another-5k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/0fe25693f35af2961376b36484534c46/another-5k-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Another 5K Run",
				subtitle: "5K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/0fe25693f35af2961376b36484534c46/another-5k-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "You love the 5K! We love the 5K! Everyone loves the 5K! Join Nike Running Head Coach Chris Bennett on this distance based guided run. You'll get motivation, guidance and inspiration to run this and every other run a better way.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 5K run. This is a distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/another-5k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ANOTHER_MILE_RUN",
		properties: {
			activeGoal: 1611.0,
			autodownload: false,
			goal: 1611.0,
			activityType: "DISTANCE",
			
			previousId: "ANOTHER_MILE_RUN_ENGB",
			previousIds: ["ANOTHER_MILE_RUN_ENGB", "ANOTHER_MILE_RUN"],
		},
		landing: {
			title: "Another Mile Run",
			subtitle: "1 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7b3279f1031b732365cf293e1e636f0a/another-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7b3279f1031b732365cf293e1e636f0a/another-mile-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Another Mile Run",
				subtitle: "1 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7b3279f1031b732365cf293e1e636f0a/another-mile-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Another Mile Run starts with you! It's another chance to become stronger and another opportunity to get better. Another mile run means another success and another victory. Join NRC Head Coach Chris Bennett on this great one mile distance based run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and inspiring one mile run. This is a distance based guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/another-mile-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ANOTHER_TEN_MILE_RUN",
		properties: {
			activeGoal: 16094.0,
			autodownload: false,
			goal: 16094.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "Another Ten Mile Run",
			subtitle: "Ten Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/7f17a16a5b3889c8d862eb06e6f2acc3/another-ten-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/7f17a16a5b3889c8d862eb06e6f2acc3/another-ten-mile-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Another Ten Mile Run",
				subtitle: "Ten Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/7f17a16a5b3889c8d862eb06e6f2acc3/another-ten-mile-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "You know what’s cooler than doing a ten mile run? Doing Another Ten Mile Run! Join Nike Running Global Head Coach Chris Bennett on this distance based guided run. You’ll cover so much more than ten miles on this fun run with Coach Bennett.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed ten mile run.\nThis is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/another-ten-mile-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "ANOTHER_THANK_YOU_RUN",
		properties: {
			activeGoal: 2700.0,
			autodownload: false,
			goal: 2700.0,
			activityType: "DURATION",
			
			previousId: "ANOTHER_THANK_YOU_RUN_ENGB",
			previousIds: ["ANOTHER_THANK_YOU_RUN_ENGB", "ANOTHER_THANK_YOU_RUN"],
		},
		landing: {
			title: "Another Thank You Run",
			subtitle: "45 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/e868d85b2a4a12c60fcba26a53f29eea/another-thank-you-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/e868d85b2a4a12c60fcba26a53f29eea/another-thank-you-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Another Thank You Run",
				subtitle: "45 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/e868d85b2a4a12c60fcba26a53f29eea/another-thank-you-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Being thankful should be a part of every run. Thankful for the opportunity to run & people, places & things that make each run a better run. Join Coach Bennett for Another Thank You Run & another great exercise in gratitude. Thank you for running with us.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "Relaxed and inspiring 45 minute easy run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/another-thank-you-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "A_RAINY_RUN",
		properties: {
			activeGoal: 2700.0,
			autodownload: false,
			goal: 2700.0,
			activityType: "DURATION",
			
			previousId: "A_RAINY_RUN_ENGB",
			previousIds: ["A_RAINY_RUN_ENGB", "A_RAINY_RUN"],
		},
		landing: {
			title: "A Rainy Run",
			subtitle: "45 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/6777da62064b05bab0ab0dbf877e55be/a-rainy-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/6777da62064b05bab0ab0dbf877e55be/a-rainy-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "A Rainy Run",
				subtitle: "45 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/6777da62064b05bab0ab0dbf877e55be/a-rainy-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "A rainy run can be a great run! Join Nike Running Head Coach Chris Bennett on this fun 45 minute run. Coach talks everything from the right gear to the best way to handle those dreaded puddles. You'll end the run a little wet but a whole lot better.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 45 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/a-rainy-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "RUN_WITH_SANDY",
		properties: {
			activeGoal: 2460.0,
			autodownload: false,
			goal: 2460.0,
			activityType: "DURATION",
			
			previousId: "RUN_WITH_SANDY_ENGB",
			previousIds: ["RUN_WITH_SANDY_ENGB", "RUN_WITH_SANDY"],
		},
		landing: {
			title: "A Run With Sandy",
			subtitle: "41 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/cbc3dc90ec180f080b83a7c45b065a0c/a-run-with-sandy.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/cbc3dc90ec180f080b83a7c45b065a0c/a-run-with-sandy.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "A Run With Sandy",
				subtitle: "41 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/cbc3dc90ec180f080b83a7c45b065a0c/a-run-with-sandy.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This run is a celebration of the life of Nike legend Sandy Bodecker. Join skateboarding greats Paul Rodriguez, Lance Mountain, Eric Koston; Olympian Galen Rupp; and Nike's Abby Samuelson, Kevin Imamura, Leo Saldana and Coach Bennett to run with Sandy.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 41 minute run with 1 minute of post run inspiration.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/a-run-with-sandy.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Sandy Bodecker",
					body: "Sandy Bodecker passed away in October of 2018. Sandy was an innovator, rebel, mentor, leader, cancer coach and friend to so many. He left behind a legacy of community and inspiration. He will always be missed and never forgotten.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "A_WHOLE_RUN_WITH_HS",
		properties: {
			activeGoal: 2700.0,
			autodownload: false,
			goal: 2700.0,
			activityType: "DURATION",
			
			previousId: "A_WHOLE_RUN_WITH_HS_ENGB",
			previousIds: ["A_WHOLE_RUN_WITH_HS_ENGB", "A_WHOLE_RUN_WITH_HS"],
		},
		landing: {
			title: "A Whole Run",
			subtitle: "45 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/e5edc45ca2c6e9eea49cd9133b3a163d/a-whole-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/e5edc45ca2c6e9eea49cd9133b3a163d/a-whole-run.png",
			backgroundColor: "#55C1BA",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#55C1BA",
			headerCard: {
				title: "A Whole Run",
				subtitle: "45 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/e5edc45ca2c6e9eea49cd9133b3a163d/a-whole-run.png",
				backgroundColor: "#55C1BA",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "A whole run means both your body and mind are active and engaged. Join Headspace co-founder Andy Puddicombe and Coach Bennett on this 45 minute run and end having become better, stronger and more wholly you.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 45 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/a-whole-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Andy Puddicombe",
					body: "As the co-founder of Headspace, Andy Puddicombe is an expert in mindfulness and meditation. After becoming a Tibetan Buddhist monk, he founded Headspace as part of his mission to improve the health and happiness of the world.",
					titleColor: "#ffffff",
					backgroundColor: "#403D44",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "BELIEVE_IN_THE_RUN",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Believe In The Run",
			subtitle: "20 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/ea69954c-51d8-4329-b479-1304d6f3702e/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/ea69954c-51d8-4329-b479-1304d6f3702e/image.png",
			backgroundColor: "#AE1210",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AE1210",
			headerCard: {
				title: "Believe In The Run",
				subtitle: "20 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/ea69954c-51d8-4329-b479-1304d6f3702e/image.png",
				backgroundColor: "#AE1210",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Believe in yourself because, as Coach Taylor says at the end of every run, she believes in you. This 20-minute run includes mantras and tips to reinforce the practice of belief in achieving your goals.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A motivational 20 min Recovery Run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
