export const runs = [
	{
		id: "30K_RUN",
		properties: {
			activeGoal: 30002.0,
			autodownload: false,
			goal: 30002.0,
			activityType: "DISTANCE",
			
			previousId: "30K_RUN_ENGB",
			previousIds: ["30K_RUN_ENGB"],
		},
		landing: {
			title: "30K Run",
			subtitle: "18.6 Mile • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/b533b58a-f40a-4bb9-a0b1-801fa63b8572/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/b533b58a-f40a-4bb9-a0b1-801fa63b8572/image.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "30K Run",
				subtitle: "18.6 Mile • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/b533b58a-f40a-4bb9-a0b1-801fa63b8572/image.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The 30K Run (just over 18.6 miles) is definitely about endurance and focus but it’s also about running relaxed and confidently… and with joy! So, charge your phone or watch, grab your fluids and fuel and get ready for an epic run. Nike Running Global Head Coach Chris Bennett will guide and motivate you on this 30K distance based guided run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A guided 30K (~18.6 mile) run. This is a distance based guided run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "30_MINUTE_FINISH_LINES",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "30_MINUTE_FINISH_LINES_ENGB",
			previousIds: ["30_MINUTE_FINISH_LINES_ENGB"],
		},
		landing: {
			title: "30 Minute Finish Lines",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/09c36755-3f73-4336-812a-96cad7d9827c/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/09c36755-3f73-4336-812a-96cad7d9827c/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "30 Minute Finish Lines",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/09c36755-3f73-4336-812a-96cad7d9827c/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Great runs exercise you mentally and physically… and are blast to do! That’s the goal of 30 Minute Finish Lines. Come along on a great run with Coach Bennett. Here’s how this guided run works – every couple of minutes Coach Bennett will start a sentence… but you will be asked to finish it. The topics will change. The subjects will be different. And you’ll need to complete the statements. Over the 30 minutes you’ll be the one finishing the lines that Coach Bennett starts. So, get ready to work both your mind and body and have a great time while you do. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A motivating and relaxed 30-minute run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "30_MINUTE_HEAD_STARTS",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "30_MINUTE_HEAD_STARTS_ENGB",
			previousIds: ["30_MINUTE_HEAD_STARTS_ENGB", "30_MINUTE_HEAD_STARTS"],
		},
		landing: {
			title: "30 Minute Head Starts",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5fd5bb1a186213597f45a29558747072/30-minute-head-starts.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5fd5bb1a186213597f45a29558747072/30-minute-head-starts.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "30 Minute Head Starts",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5fd5bb1a186213597f45a29558747072/30-minute-head-starts.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Every run is a conversation between mind and body. You need to talk and listen to yourself because there's always something to learn about the run and runner.  Coach Bennett will give 15 thought starters for you to run with and let your mind run with too.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/30-minute-head-starts.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "30_MINUTE_THANK_YOUS_2022",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",
			
			previousId: "30_MINUTE_THANK_YOUS_2022",
			previousIds: ["30_MINUTE_THANK_YOUS_2022"],
		},
		landing: {
			title: "30 Minute Thank Yous",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/0a340c21-25f5-4e7f-8914-a6216713fc7b/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/0a340c21-25f5-4e7f-8914-a6216713fc7b/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "30 Minute Thank Yous",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/0a340c21-25f5-4e7f-8914-a6216713fc7b/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Thank you for running! That’s only one thank you. You’ve got 29 more coming your way on this inspiring easy run with Nike Running Global Head Coach. Coach Bennett helps guide you through an exercise in gratefulness (as well as a 30-minute recovery run.) You’ll end the half hour not only a better runner… but more aware of how much you and others accomplish and do each day that is deserving of a thank you... or 30 thank you's!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An easy and motivational 30-minute recovery run.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Short Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "30_ON_30_OFF",
		properties: {
			activeGoal: 1218.0,
			autodownload: false,
			goal: 1260.0,
			activityType: "SPEED_DURATION",
			
			previousId: "30_ON_30_OFF_ENGB",
			previousIds: ["30_ON_30_OFF_ENGB"],
		},
		landing: {
			title: "30 On 30 Off",
			subtitle: "20 Min • Fartlek",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/e9e71a78-c6b1-472e-801e-4979bacfabd9/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/e9e71a78-c6b1-472e-801e-4979bacfabd9/image.png",
			backgroundColor: "#D4FF2A",
			titleColor: "#111111",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D4FF2A",
			headerCard: {
				title: "30 On 30 Off",
				subtitle: "20 Min • Fartlek",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/e9e71a78-c6b1-472e-801e-4979bacfabd9/image.png",
				backgroundColor: "#D4FF2A",
				titleColor: "#111111",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It’s time to turn it on! And then turn it off and then on and then off again and you get it. Get ready for another great fartlek run with Coach Chelsea Cox of Nike Running North America. This is 30 ON 30 OFF. After a five-minute warm up you’ll be guided through a fifteen minute fartlek that alternates between 30 seconds of hard running (5K effort) and 30 seconds of easy running. You’ll be working on getting stronger and faster by changing speeds and efforts. You’ll also be having fun… because running fast is meant to be fun.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warmup Run<br>\n15:00 Fartlek (alternates every 30 seconds between hard and easy efforts)<br>\n<br>\n21 Minutes Total Experience</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cox",
					body: "<p>Chelsea Cox was a standout middle distance runner for Georgetown University. She is currently a Nike Run Club North America Coach based out of North Carolina.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "3K_RUN",
		properties: {
			activeGoal: 3000.0,
			autodownload: false,
			goal: 3000.0,
			activityType: "DISTANCE",
			
			previousId: "3K_RUN_ENGB",
			previousIds: ["3K_RUN_ENGB", "3K_RUN"],
		},
		landing: {
			title: "3K Run",
			subtitle: "3K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/6c68415888af8fb342ff824f4942161e/3k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/6c68415888af8fb342ff824f4942161e/3k-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "3K Run",
				subtitle: "3K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/6c68415888af8fb342ff824f4942161e/3k-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Coach Cory is back with this fun and inspiring 3K Run. That’s just under 2 miles of easy running! You’ll be guided and motivated (and entertained) over the course of this run and before you know it Coach Cory will be asking you whether or not you want to add on or end the run at 3000 meters! Because when you and Coach Cory team up not only does time fly... but you fly too!",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 3K run. That’s just less than 2 miles. This is a distance-based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/3k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "Coach Cory",
					body: "Coach Cory-Wharton-Malcolm is the Nike Run Club UK Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "3K_WALK_BACKS",
		properties: {
			activeGoal: 3002.0,
			autodownload: false,
			goal: 3002.0,
			activityType: "DISTANCE",
			
			previousId: "3K_WALK_BACKS_ENGB",
			previousIds: ["3K_WALK_BACKS_ENGB"],
		},
		landing: {
			title: "3K Walk Backs",
			subtitle: "3K • Walk",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/acb271fb-1def-43b1-8b1f-c1824c788c07/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/acb271fb-1def-43b1-8b1f-c1824c788c07/image.png",
			backgroundColor: "#19B5E8",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#19B5E8",
			headerCard: {
				title: "3K Walk Backs",
				subtitle: "3K • Walk",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/acb271fb-1def-43b1-8b1f-c1824c788c07/image.png",
				backgroundColor: "#19B5E8",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Join Nike Running Global Head Coach Chris Bennett and take some time to walk back through your day, week, month, and year as you walk yourself 3K forward. This distance-based walk includes questions and prompts that have you mindfully think back on your near and not so near past. Taking time to look back can lead to great steps forward. So, get ready for some fun on the move with 3K Walk Backs.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Walk Details",
					body: "<p>A relaxed and motivational 3K walk/hike. This is a distance-based walk. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that built the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "3RD_TRIMESTER_RUN",
		properties: {
			activeGoal: 3000.0,
			autodownload: false,
			goal: 3000.0,
			activityType: "DURATION",
			
			previousId: "3RD_TRIMESTER_RUN_ENGB",
			previousIds: ["3RD_TRIMESTER_RUN_ENGB", "3RD_TRIMESTER_RUN"],
		},
		landing: {
			title: "3rd Trimester Running & Beyond",
			subtitle: "50 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/16a02f93ea3a8ba04809bc0fb9c1265d/3rd-trimester-running-beyond.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/16a02f93ea3a8ba04809bc0fb9c1265d/3rd-trimester-running-beyond.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "3rd Trimester Running & Beyond",
				subtitle: "50 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/16a02f93ea3a8ba04809bc0fb9c1265d/3rd-trimester-running-beyond.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "On this 50-minute easy run (or walk… you decide!) we’ve got one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy. Join Jane and Coach Bennett for this great conversation about running, movement and exercise during the 3rd Trimester of pregnancy.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable, educational and inspirational 50-minute easy run or walk with one minute of post run inspiration.\n\nTotal Experience: 50 Minutes\n\nThis information should be used as a guide only and is not a substitute for advice from a medical professional. Always consult a medical professional before engaging in a new exercise program and use your judgment for what feels right for you. If you feel faint, experience shortness of breath, dizziness, or related sensations while exercising, stop immediately and seek medical attention as necessary.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/3rd-trimester-running-beyond.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Jane Wake",
					body: "Jane Wake is one of the leading experts on pre and postnatal exercise and training! Jane Wake has been running her own Health & Fitness consultancy, Body A-Wake, since 1993 and in that time, she has helped countless athletes navigate and thrive before, during and after pregnancy.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "3_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "3 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/2d30d578c2c42473c266a5e12eb2c421/3-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/2d30d578c2c42473c266a5e12eb2c421/3-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "3 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/2d30d578c2c42473c266a5e12eb2c421/3-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 3 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/3-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "40_MINUTE_HEAD_STARTS",
		properties: {
			activeGoal: 2400.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "40 Minute Head Starts",
			subtitle: "40 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/a4d2c2e0-c822-4ef7-9ce1-3b369fb62da0/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/a4d2c2e0-c822-4ef7-9ce1-3b369fb62da0/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "40 Minute Head Starts",
				subtitle: "40 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/a4d2c2e0-c822-4ef7-9ce1-3b369fb62da0/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Are you ready for another fantastic run? And that means get ready for another run that includes a great conversation between you and yourself! 40 Minute Head Starts is a duration based guided run that initiates a series of conversations for you to take part in. Coach Bennett will check in over the course of the run with statements and follow up with some thought starters for you to take with you on your run. The Head Starts guided runs are some of the most popular and loved runs in the app. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A relaxed and motivational forty-minute recovery run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "4K_RUN",
		properties: {
			activeGoal: 4000.0,
			autodownload: false,
			goal: 4000.0,
			activityType: "DISTANCE",
			
			previousId: "4K_RUN_ENGB",
			previousIds: ["4K_RUN_ENGB", "4K_RUN"],
		},
		landing: {
			title: "4K Run",
			subtitle: "4K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/dc412b16514a58358af253c9a39f07b5/4k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/dc412b16514a58358af253c9a39f07b5/4k-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "4K Run",
				subtitle: "4K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/dc412b16514a58358af253c9a39f07b5/4k-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The 4K Run (just less than 2.50 miles) is an awesome distance. Especially when you want to start a run that’s more than 3k or 2 miles but less than 5K or 3 miles. Join Bowerman Track Club Coach Shalane Flanagan for this 4000 meter easy run. Coach Flanagan knows what it takes to make every run a better run. And at the end of this 4K you’ll know what it takes too.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 4K run. That’s just less than 2.50 miles. This is a distance-based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/4k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Shalane Flanagan",
					body: "Shalane Flanagan is a coach with the Bowerman Track Club. Coach Flanagan was also one of the greatest distance runners of her generation. She is an Olympic Silver medalist in the 10K as well as a winner of the NYC Marathon. Coach Flanagan still holds numerous American Records. She’s now coaching one of the most successful groups of distance runners in the world with the Bowerman Track Club (BTC).",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "4K_STARTING_LINES",
		properties: {
			activeGoal: 4002.0,
			autodownload: false,
			goal: 4002.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "4K Starting Lines",
			subtitle: "4K • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/9b61ee07-8a4b-4509-9165-8e3f36e85215/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/9b61ee07-8a4b-4509-9165-8e3f36e85215/image.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "4K Starting Lines",
				subtitle: "4K • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/9b61ee07-8a4b-4509-9165-8e3f36e85215/image.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>There is more than one starting line on this fun distance based guided run with Coach Bennett. At various points throughout the run Coach will give you the end of a statement or sentence. It will be your job to start… the… line. Get it? Witty, right? Be prepared to have a great conversation between your mind and body on this one. And remember… there are starting lines everywhere. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>An inspiring and mindful 4K run. That’s just about 2.5 miles. This is a distance-based audio guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Distance Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "4K_TEMPO_RUN",
		properties: {
			activeGoal: 6002.0,
			autodownload: false,
			goal: 6002.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "4K Tempo Run",
			subtitle: "4K • Tempo Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/3fe1f919-f3bf-4ca1-8138-b58fd4ebfd5e/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/3fe1f919-f3bf-4ca1-8138-b58fd4ebfd5e/image.png",
			backgroundColor: "#D4FF2A",
			titleColor: "#111111",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D4FF2A",
			headerCard: {
				title: "4K Tempo Run",
				subtitle: "4K • Tempo Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/3fe1f919-f3bf-4ca1-8138-b58fd4ebfd5e/image.png",
				backgroundColor: "#D4FF2A",
				titleColor: "#111111",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>One of the best ways a runner can work on developing physical and mental strength and endurance is the Tempo Run. Join Coach Bennett on this 4K Tempo Run. You’ll warm up 1K and then roll right into a distance based & guided Tempo Run. Once the 4K Tempo Run is done you’ll be guided through a 1000 meter guided cool down for a total running experience of 6K.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>1000m/~.62 Miles Warm Up</p>\n<p>4000m/~2.5 Miles Tempo Run</p>\n<p>1000m/~.62 Miles Cool Down</p>\n<p> </p>\n<p>6000m/~3.75 miles Total Distance</p>\n<p>This is a distance based guided Speed Run.</p>\n<p></p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "4_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "4 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/76cd3b9f126f3f02ae90fc7fd076fedc/4-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/76cd3b9f126f3f02ae90fc7fd076fedc/4-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "4 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/76cd3b9f126f3f02ae90fc7fd076fedc/4-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 4 weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/4-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "555_SECONDS_RUN",
		properties: {
			activeGoal: 555.0,
			autodownload: false,
			goal: 555.0,
			activityType: "DURATION",
			
			previousId: "555_SECONDS_RUN_ENGB",
			previousIds: ["555_SECONDS_RUN_ENGB"],
		},
		landing: {
			title: "555 Seconds Run",
			subtitle: "555 Sec • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/3a544e22-2388-4f33-8fac-c0fb0aee6ec9/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/3a544e22-2388-4f33-8fac-c0fb0aee6ec9/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "555 Seconds Run",
				subtitle: "555 Sec • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/3a544e22-2388-4f33-8fac-c0fb0aee6ec9/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>This run isn’t measured in minutes. And it’s not measured in distance. This run is measured in seconds! Why? Why not! Join Nike Running Global Head Coach Chris Bennett for the 555 Seconds Run. Measuring success as many ways as you can is one of the ways to make sure you not only experience more success but also don’t overlook success. So, let’s go celebrate 555 seconds of success!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A guided 555 second run (that’s 9 minutes and 15 seconds of running… don’t tell Coach Bennett we told you that!) This is a duration based guided run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Short Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "5K_FINISH_LINES",
		properties: {
			activeGoal: 5000.0,
			autodownload: false,
			goal: 5000.0,
			activityType: "DISTANCE",
			
			previousId: "5K_FINISH_LINES_ENGB",
			previousIds: ["5K_FINISH_LINES_ENGB"],
		},
		landing: {
			title: "5K Finish Lines",
			subtitle: "5K • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/034a1337-e408-4bf7-a07a-fef0b628769b/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/034a1337-e408-4bf7-a07a-fef0b628769b/image.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "5K Finish Lines",
				subtitle: "5K • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/034a1337-e408-4bf7-a07a-fef0b628769b/image.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The best runs exercise you mentally and physically… and are fun! That’s the goal of 5K Finish Lines. Come along on a great run with Coach Bennett. Here’s how this distance based guided run works – every couple hundred meters Coach Bennett will start a sentence… but you will be asked to finish it. The topics will change. The subjects will be different. And you’ll need to complete the statements. Over 5000 meters you’ll be the one finishing the lines that Coach Bennett starts. So, get ready to work both your mind and body and have a great time while you do. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A fun and inspiring 5K run. That’s just over 3 miles. This is a distance-based audio guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "5K_HEAD_STARTS",
		properties: {
			activeGoal: 5002.0,
			autodownload: false,
			goal: 5002.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "5K Head Starts",
			subtitle: "5K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/86a3ffdb08f5efd0816bb65703bdc9e3/5k-head-starts.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/86a3ffdb08f5efd0816bb65703bdc9e3/5k-head-starts.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "5K Head Starts",
				subtitle: "5K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/86a3ffdb08f5efd0816bb65703bdc9e3/5k-head-starts.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "We know that a great run means a great conversation between mind and body. You’ll join Nike Running Global Head Coach Chris Bennett on this 5K run and get a series of thought starters and questions to think about. So just let your mind run. Don’t worry... your body will follow.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable 5K run. This is a distance based audio guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/5k-head-starts.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "5K_RACE",
		properties: {
			activeGoal: 5000.0,
			autodownload: false,
			goal: 5000.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "5K Race",
			subtitle: "5K • Race",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f40fb65f9f5e87a7f7f813f1fb620dbd/5k-race.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f40fb65f9f5e87a7f7f813f1fb620dbd/5k-race.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "5K Race",
				subtitle: "5K • Race",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f40fb65f9f5e87a7f7f813f1fb620dbd/5k-race.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Let’s party! Because we don’t race to prove we’re runners… we race to celebrate we’re runners! Join Nike Running Global Head Coach Chris Bennett for this 5K/3.1 Mile guided run that will inspire and motivate you from the starting line of the 5K all the way to the finish line. So, charge that watch or phone, get yourself to a starting line... and let’s get this party started!",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An inspiring, fun and motivational 5K distance-based run. This run is meant to help an athlete during a race. This is a 5K/3.1 Mile distance guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/5k-race.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "5K_RUN",
		properties: {
			activeGoal: 5000.0,
			autodownload: false,
			goal: 5000.0,
			activityType: "DISTANCE",
			
			previousId: "5K_RUN_ENGB",
			previousIds: ["5K_RUN_ENGB", "5K_RUN"],
		},
		landing: {
			title: "5K Run",
			subtitle: "5K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/22489655717ab4d51f0aef6a97202d76/5k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/22489655717ab4d51f0aef6a97202d76/5k-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "5K Run",
				subtitle: "5K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/22489655717ab4d51f0aef6a97202d76/5k-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Time to run 5K the right way! Join Nike Running Head Coach Chris Bennett on this distance based guided run. You'll end this run a better and more motivated athlete. You'll also be 5000 meters further along on your running journey!",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed 5K run. This is a distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/5k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "5K_TEMPO_RUN",
		properties: {
			activeGoal: 8000.0,
			autodownload: false,
			goal: 8000.0,
			activityType: "DISTANCE",
			
			previousId: "5K_TEMPO_RUN_ENGB",
			previousIds: ["5K_TEMPO_RUN_ENGB", "5K_TEMPO_RUN"],
		},
		landing: {
			title: "5K Tempo Run",
			subtitle: "8K • Tempo Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/e06127e3ca246c2eb79dc32a7c7baf84/5k-tempo-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/e06127e3ca246c2eb79dc32a7c7baf84/5k-tempo-run.png",
			backgroundColor: "#D4FF2A",
			titleColor: "#111111",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#D4FF2A",
			headerCard: {
				title: "5K Tempo Run",
				subtitle: "8K • Tempo Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/e06127e3ca246c2eb79dc32a7c7baf84/5k-tempo-run.png",
				backgroundColor: "#D4FF2A",
				titleColor: "#111111",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>It’s a classic workout. It’s a staple workout. It belongs in every runner’s wheelhouse. It’s the 5K Tempo Run. Join Bowerman Track Club Coach Shalane Flanagan for this awesome strength workout. You’ll get guidance from one of the best with every stride you take. Coach Flanagan knows what it takes to get the best out of every run. And she’ll make sure you get the best coaching you can get to do the same.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>1.5K Warm Up<br>\n5K Tempo Run<br>\n1.5K Cool Down<br>\n<br>\nThe total distance of this Speed Run is 8000 meters.<br>\n<br>\nThis is a distance-based audio guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/5k-tempo-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Shalane Flanagan",
					body: "<p>Shalane Flanagan is a coach with the Bowerman Track Club. Coach Flanagan was also one of the greatest distance runners of her generation. She is an Olympic Silver medalist in the 10K as well as a winner of the NYC Marathon. Coach Flanagan still holds numerous American Records. She’s now coaching one of the most successful groups of distance runners in the world with the Bowerman Track Club (BTC).</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "5_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
		},
		landing: {
			title: "5 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c163c248c95ee0eee0f0840ae438bdc9/5-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c163c248c95ee0eee0f0840ae438bdc9/5-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "5 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c163c248c95ee0eee0f0840ae438bdc9/5-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 5  weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/5-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "5X_5X_10K_PACE_RUN",
		properties: {
			activeGoal: 1860.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "SPEED_DURATION",
			
			previousId: "5X_5X_10K_PACE_RUN_ENGB",
			previousIds: ["5X_5X_10K_PACE_RUN_ENGB", "5X_5X_10K_PACE_RUN"],
		},
		landing: {
			title: "5x5x10k Pace Run",
			subtitle: "41 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/b6aeaf6ec5a400d902901c77f6ba3f32/5x5x10k-pace-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/b6aeaf6ec5a400d902901c77f6ba3f32/5x5x10k-pace-run.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "DEFAULT",
			metricVoiceovers: "DEFAULT",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "5x5x10k Pace Run",
				subtitle: "41 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/b6aeaf6ec5a400d902901c77f6ba3f32/5x5x10k-pace-run.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>The title of the run says it all. 5 intervals of 5 minutes duration at 10K pace. That means you get to work on your strength and endurance. And that means you'll end this run ready to go longer and better. Sounds like a great workout...because it is.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n5 x 5:00 10K Pace<br>\n<br>\n2:00 Recovery between all intervals<br>\n<br>\n41 minute total experience</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/5x5x10k-pace-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Cory",
					body: "Coach Cory Wharton-Malcolm is the Nike London Head Coach. He also founded Track Mafia Track Club. Whether Coach Cory is working with his teammates, members of the London scene or local young people, everyone leaves wanting to run again.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "60S_RUN",
		properties: {
			activeGoal: 1848.0,
			autodownload: false,
			goal: 1860.0,
			activityType: "SPEED_DURATION",
			
			previousId: "60S_RUN_ENGB",
			previousIds: ["60S_RUN_ENGB", "60S_RUN"],
		},
		landing: {
			title: "60's",
			subtitle: "31 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/6a6079f08aad113cd0ad7efd50aa3908/60-s.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/6a6079f08aad113cd0ad7efd50aa3908/60-s.png",
			backgroundColor: "#00257E",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#00257E",
			headerCard: {
				title: "60's",
				subtitle: "31 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/6a6079f08aad113cd0ad7efd50aa3908/60-s.png",
				backgroundColor: "#00257E",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The name of this run says it all! This quick and fun speed run calls for 12 intervals. Each will be 60 seconds in length. You’ll roll four 60 second intervals at your 5K effort. Then you’ll run four more intervals at your 10K effort for 60 seconds. And then you’ll close out this workout with four 60 seconds intervals at your Mile Pace. Recovery will be 60 seconds long after each interval except for your last 5K and 10K intervals. You will get two minutes recovery after those. This is a fab speed run to work on your efforts and pacing. Believe me... it’s a gas!",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm Up<br>\n1:00 5K Pace (repeat 4 times)<br>\n1:00 10K Pace (repeat 4 times)<br>\n1:00 Mile Pace (repeat 4 times)<br>\n<br>\nRecovery will be 1:00 after each interval except for final interval at 5K Pace and 10K Pace.<br>\n<br>\nThere will be 2:00 recovery after each of those intervals.<br>\n<br>\n32:00 Total Experience</p>",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/60-s.png",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Benadum",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their own greatest potential.",
					titleColor: "#ffffff",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "6K_RUN",
		properties: {
			activeGoal: 6000.0,
			autodownload: false,
			goal: 6000.0,
			activityType: "DISTANCE",
			
		},
		landing: {
			title: "6K Run",
			subtitle: "6K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/c225aa6f54c590a4814e26ab299fd72d/6k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/c225aa6f54c590a4814e26ab299fd72d/6k-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "6K Run",
				subtitle: "6K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/c225aa6f54c590a4814e26ab299fd72d/6k-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The 6K Run (just less than 3.75 miles) is a great opportunity to run a new distance. Join Nike Running Global Head Coach Chris Bennett on this easy 6K distance-based guided run. You’ll get the motivation, inspiration and guidance you need to have a better run. So, meet us at the starting line for a run you’ll be proud of yourself for doing.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed 6Krun. That’s just less than 3.75 miles. This is a distance-based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/6k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "6_WEEKS_TO_GO",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			
			previousId: "6_WEEKS_TO_GO_ENGB",
			previousIds: ["6_WEEKS_TO_GO_ENGB", "6_WEEKS_TO_GO"],
		},
		landing: {
			title: "6 Weeks To Go",
			subtitle: "15 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/5cefacbfe718aba734cfec0d60c0b02d/6-weeks-to-go.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/5cefacbfe718aba734cfec0d60c0b02d/6-weeks-to-go.png",
			backgroundColor: "#FF433D",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF433D",
			headerCard: {
				title: "6 Weeks To Go",
				subtitle: "15 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/5cefacbfe718aba734cfec0d60c0b02d/6-weeks-to-go.png",
				backgroundColor: "#FF433D",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Start 6  weeks to go with Nike Running Global Head Coach Chris Bennett on this 15:00 easy run. You’ll go over the Half Marathon training for the week ahead & how best to approach & adjust your running so you can finish your week as best as you can.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A comfortable and relaxed 15:00 Recovery Run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/6-weeks-to-go.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
