export const runs = [
	{
		id: "TODAYS_30_MINUTE_WALK",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",

			previousId: "TODAYS_30_MINUTE_WALK_ENGB",
			previousIds: ["TODAYS_30_MINUTE_WALK_ENGB"],
		},
		landing: {
			title: "Today's 30 Minute Walk",
			subtitle: "30 Min • Walk",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/acb271fb-1def-43b1-8b1f-c1824c788c07/todays_30_minute_walk.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/acb271fb-1def-43b1-8b1f-c1824c788c07/todays_30_minute_walk.png",
			backgroundColor: "#19B5E8",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#19B5E8",
			headerCard: {
				title: "Today's 30 Minute Walk",
				subtitle: "30 Min • Walk",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/acb271fb-1def-43b1-8b1f-c1824c788c07/todays_30_minute_walk.png",
				backgroundColor: "#19B5E8",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Take the time to move through your day. Today’s 30 Minute Walk is all about you & this day that just began or is close to ending. Chris Bennett, the Nike Running Global Head Coach, will offer up questions throughout the walk (or hike, it’s up to you after all) for you to answer that will help you start or finish your day in a better place. Join Coach Bennett for this fun & relaxed 30-minute walk.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Walk Details",
					body: "<p>A relaxed and motivational 30-minute walk/hike. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/todays_30_minute_walk.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that built the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TODAYS_3K_RUN",
		properties: {
			activeGoal: 3002.0,
			autodownload: false,
			goal: 3002.0,
			activityType: "DISTANCE",
		},
		landing: {
			title: "Today's 3K Run",
			subtitle: "3K • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/27340de4-1b84-460b-8a1c-58c7ab78ded6/todays_3k_run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/27340de4-1b84-460b-8a1c-58c7ab78ded6/todays_3k_run.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "Today's 3K Run",
				subtitle: "3K • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/27340de4-1b84-460b-8a1c-58c7ab78ded6/todays_3k_run.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>All we need is 3K to help you start or end your day a great way. Today’s 3K Run is about your day… your day today. Chris Bennett, the Nike Running Global Head Coach, will offer up thought starters and questions throughout the run for you to think about or answer. The goal is to have an awesome run that will help you start or finish your day in a better place. Join Coach Bennett for this relaxed, fun and inspiring 3K easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and motivational 3000m easy run. This is a distance based guided run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/e60a040e-ce92-45d4-81cd-19e68bcb0581/todays_3k_run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TODAYS_40_MINUTE_RUN",
		properties: {
			activeGoal: 2400.0,
			autodownload: false,
			goal: 2400.0,
			activityType: "DURATION",

			previousId: "TODAYS_40_MINUTE_RUN_ENGB",
			previousIds: ["TODAYS_40_MINUTE_RUN_ENGB", "TODAYS_40_MINUTE_RUN"],
		},
		landing: {
			title: "Today's 40 Minute Run",
			subtitle: "40 Min • Long Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/acafa58540496f9a958bf76c605a3728/today-s-40-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/acafa58540496f9a958bf76c605a3728/today-s-40-minute-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Today's 40 Minute Run",
				subtitle: "40 Min • Long Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/acafa58540496f9a958bf76c605a3728/today-s-40-minute-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Take the time to run through your day. Today’s 40 Minute Run is all about you & this day that just began or is close to ending. Chris Bennett, the Nike Running Global Head Coach, will offer up questions throughout the run for you to answer that will help you start or finish your day in a better place. Join Coach Bennett for this easy & comfortable 40-minute run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and motivational 40 minute easy run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/today-s-40-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TODAYS_5K_RUN",
		properties: {
			activeGoal: 5000.0,
			autodownload: false,
			goal: 5000.0,
			activityType: "DISTANCE",

			previousId: "TODAYS_5K_RUN_ENGB",
			previousIds: ["TODAYS_5K_RUN_ENGB", "TODAYS_5K_RUN"],
		},
		landing: {
			title: "Today's 5K Run",
			subtitle: "5K • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/03a6a45cc200bf8599c6274dab5ac0c4/today-s-5k-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/03a6a45cc200bf8599c6274dab5ac0c4/today-s-5k-run.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Today's 5K Run",
				subtitle: "5K • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/03a6a45cc200bf8599c6274dab5ac0c4/today-s-5k-run.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "This 5K run is all about you and your day. Whether you need to process and think about the day that was or you need to start and prepare for the day that has just begun… this 5K is for you. Join Nike Running Global Head Coach Chris Bennett for an easy and comfortable 5K. Coach Bennett will offer up questions throughout the run for you to answer that will help you start or finish your day in a better place.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "An easy and motivational 5K run. That’s just over 3.1 miles. This is a distance-based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/today-s-5k-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#252525",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TRAIL_RUN_WITH_SALLY",
		properties: {
			activeGoal: 1800.0,
			autodownload: false,
			goal: 1800.0,
			activityType: "DURATION",

			previousId: "TRAIL_RUN_WITH_SALLY_ENGB",
			previousIds: ["TRAIL_RUN_WITH_SALLY_ENGB", "TRAIL_RUN_WITH_SALLY"],
		},
		landing: {
			title: "Trail Run With Sally",
			subtitle: "30 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/373f3d3705e4471a4d411bd760f5e8cf/trail-run-with-sally.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/373f3d3705e4471a4d411bd760f5e8cf/trail-run-with-sally.png",
			backgroundColor: "#ff0b46",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#ff0b46",
			headerCard: {
				title: "Trail Run With Sally",
				subtitle: "30 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/373f3d3705e4471a4d411bd760f5e8cf/trail-run-with-sally.png",
				backgroundColor: "#ff0b46",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Get ready to hit the trails with Nike Trail Team member and Nike Running Coach Sally McRae. McRae takes you on a 30 minute easy run filled with guidance, wisdom and stories from her thousands of miles on the trails.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 30 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/trail-run-with-sally.png",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.",
					titleColor: "#ffffff",
					backgroundColor: "#bf0835",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TREADHILLS",
		properties: {
			activeGoal: 930.0,
			autodownload: false,
			goal: 1470.0,
			activityType: "SPEED_DURATION",

			previousId: "TREADHILLS_ENGB",
			previousIds: ["TREADHILLS_ENGB", "TREADHILLS"],
		},
		landing: {
			title: "Treadhills",
			subtitle: "25 Min • Treadmill Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/62e1a27b111cee8621f2d08780928255/treadhills.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/62e1a27b111cee8621f2d08780928255/treadhills.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Treadhills",
				subtitle: "25 Min • Treadmill Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/62e1a27b111cee8621f2d08780928255/treadhills.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Every treadmill can be hill maker. And hills make you stronger and faster. That means every treadmill can make you stronger and faster. Hooray for treadmills! Join NRC Dubai Coach Manal Rostom for this exciting and fun treadmill hill workout.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up Workout: 2:00 10K pace - 3 percent elevation 1:00 5K pace - 2 percent elevation 0:30 Mile pace - 1 percent elevation Repeat series 3 times. Recovery intervals will be 1 minute in duration. <br>\n<br>\n25 minute total experience.</p>",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/treadhills.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Manal Rostom",
					body: "Dubai Nike Run Club Coach Manal Rostom has accomplished many firsts throughout her life by competing in major marathons and reaching the highest peaks of the world. She is breaking barriers for women’s sports globally and inspiring thousands to get active every day.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TRIPLE7",
		properties: {
			activeGoal: 1560.0,
			autodownload: false,
			goal: 1920.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Triple 7's",
			subtitle: "33 Min • Intervals",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/e22a164a1ef26548dba0854aa4c8fee9/triple-7-s.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/e22a164a1ef26548dba0854aa4c8fee9/triple-7-s.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Triple 7's",
				subtitle: "33 Min • Intervals",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/e22a164a1ef26548dba0854aa4c8fee9/triple-7-s.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Ultra-marathoner and Nike Trail Team Runner Sally McRae will be your coach for this great endurance workout. You’ll run 3 intervals that are 7 minutes each at your 5K pace. McRae will guide you through these intervals so you run the right way. Learn how to get stronger and have more fun the longer you go.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>5:00 Warm up<br>\n7:00 5K Pace<br>\n7:00 5K Pace<br>\n7:00 5K Pace<br>\n<br>\nRecovery intervals will be 2:30 in duration.<br>\n<br>\nCoach Sally will be providing guidance and motivation throughout the run.<br>\n<br>\n33 minute total experience.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Triple 7's",
					url: "https://static.nike.com/ntc-prod/images/4b2fa6bfc0a35ccf106b27c6ca80ed3f/triple-7-s.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/triple-7s/pl.df065251da9e4435b01041b148fbcd80",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/6whDZONsl4uVeFPBLe5EML",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Sally",
					body: "Coach Sally McRae is a NRC Los Angeles Coach and has competed internationally for the Nike Trail Team. Sally believes that every athlete has special potential inside them and wants to help unlock that for everyone.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TWELVE_MINUTE_RUN",
		properties: {
			activeGoal: 720.0,
			autodownload: false,
			goal: 720.0,
			activityType: "DURATION",

			previousId: "TWELVE_MINUTE_RUN_ENGB",
			previousIds: ["TWELVE_MINUTE_RUN_ENGB", "TWELVE_MINUTE_RUN"],
		},
		landing: {
			title: "Twelve Minute Run",
			subtitle: "12 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/70a05aad4f4929ca6ac0efe6b677af9f/twelve-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/70a05aad4f4929ca6ac0efe6b677af9f/twelve-minute-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Twelve Minute Run",
				subtitle: "12 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/70a05aad4f4929ca6ac0efe6b677af9f/twelve-minute-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The best runs aren’t decided by distance or duration. The best runs are measured by what you do over that distance or duration. Join Nike Running Global Head Coach Chris Bennett on this 12-minute easy run and maybe have one of those best runs. Coach covers how to measure what really matters when you’re running. It all adds up to a great run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A fun and comfortable 12 minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/twelve-minute-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "25_MINUTE_RUN",
		properties: {
			activeGoal: 1500.0,
			autodownload: false,
			goal: 1500.0,
			activityType: "DURATION",
		},
		landing: {
			title: "Twenty Five Minute Run",
			subtitle: "25 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/80cbcb6d-eed1-4cc4-83c2-cf7f6d9a048e/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/80cbcb6d-eed1-4cc4-83c2-cf7f6d9a048e/image.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Twenty Five Minute Run",
				subtitle: "25 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/80cbcb6d-eed1-4cc4-83c2-cf7f6d9a048e/image.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>25 minutes of running. You just got to love it. Sometimes you want to run more than twenty minutes… but you want to run less than thirty. Well, we’ve got you covered. Join Nike Running Global Head Coach, Chris Bennett, for this relaxed and totally motivational easy run. You’ll be sure to end the run better than you started… and more than just twenty-five minutes better. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A relaxed and easy 25-minute recovery run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TWENTY_MILE_RUN",
		properties: {
			activeGoal: 32190.0,
			autodownload: false,
			goal: 32190.0,
			activityType: "DISTANCE",

			previousId: "TWENTY_MILE_RUN_ENGB",
			previousIds: ["TWENTY_MILE_RUN_ENGB", "TWENTY_MILE_RUN"],
		},
		landing: {
			title: "Twenty Mile Run",
			subtitle: "20 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/f484e6fa0ded8bc9e0a76d3354563490/twenty-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/f484e6fa0ded8bc9e0a76d3354563490/twenty-mile-run.png",
			backgroundColor: "#FF5500",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#FF5500",
			headerCard: {
				title: "Twenty Mile Run",
				subtitle: "20 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/f484e6fa0ded8bc9e0a76d3354563490/twenty-mile-run.png",
				backgroundColor: "#FF5500",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "The Twenty Mile Run (almost 32.2K) is here. Are you ready? Join Bowerman TC Coach Shalane Flanagan on this guided long distance guided run. Coach Flanagan will coach and inspire over the almost 32.2K distance and help you run a smarter and better long run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "This is a ~32.2K/Twenty Mile Run. Make sure you have the necessary fitness, fluids and fuel to take on and complete this distance. You should also have a fully charged phone or watch that can stay powered throughout the run. This is a distance based guided run.",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/twenty-mile-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "Shalane Flanagan is a coach with the Bowerman Track Club. Coach Flanagan was also one of the greatest distance runners of her generation. She is an Olympic Silver medalist in the 10K as well as a winner of the NYC Marathon. Coach Flanagan still holds numerous American Records. She’s now coaching one of the most successful groups of distance runners in the world with the Bowerman Track Club (BTC).",
					titleColor: "#FFFFFF",
					backgroundColor: "#222222",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TWENTY_MINUTE_RUN",
		properties: {
			activeGoal: 1200.0,
			autodownload: false,
			goal: 1200.0,
			activityType: "DURATION",

			previousId: "TWENTY_MINUTE_RUN_ENGB",
			previousIds: ["TWENTY_MINUTE_RUN_ENGB", "TWENTY_MINUTE_RUN"],
		},
		landing: {
			title: "Twenty Minute Run",
			subtitle: "20 Min • Recovery Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/1b31b1f96d1f7cf8effb3dbb3ddb6b97/twenty-minute-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/1b31b1f96d1f7cf8effb3dbb3ddb6b97/twenty-minute-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Twenty Minute Run",
				subtitle: "20 Min • Recovery Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/1b31b1f96d1f7cf8effb3dbb3ddb6b97/twenty-minute-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "20 minutes. Long enough if you want it to be. Short enough if you want it to be. Easy enough or challenging enough… if you want it to be. It’s your run after all. Join Nike Running Global Head Coach Chris Bennett for this fun twenty minute recovery run. It’s the perfect run for you… if you want it to be.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and easy 20-minute recovery run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/twenty-minute-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TWO_HARD_ONE_EASY",
		properties: {
			activeGoal: 1560.0,
			autodownload: false,
			goal: 1620.0,
			activityType: "SPEED_DURATION",

			previousId: "TWO_HARD_ONE_EASY_ENGB",
			previousIds: ["TWO_HARD_ONE_EASY_ENGB", "TWO_HARD_ONE_EASY"],
		},
		landing: {
			title: "Two Hard. One Easy.",
			subtitle: "28 Min • Fartlek",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/8871b20dc516ae9f1988a4f0e59c2163/two-hard-one-easy.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/8871b20dc516ae9f1988a4f0e59c2163/two-hard-one-easy.png",
			backgroundColor: "#d4ff2a",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#d4ff2a",
			headerCard: {
				title: "Two Hard. One Easy.",
				subtitle: "28 Min • Fartlek",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/8871b20dc516ae9f1988a4f0e59c2163/two-hard-one-easy.png",
				backgroundColor: "#d4ff2a",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Fartlek time! No need to excuse yourself. Fartlek just means speed play! Join Coach Blue Benadum of NRC LA and get ready to work on your endurance and speed. You'll alternate between hard and easy running and end stronger and faster. Sounds like a great deal!</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "This speed workout begins with a 5 minute guided warmup, then a 21 minute fartlek that alternates between 2 minutes of hard running and 1 minute of easy running. There is 1 minute of post run guidance and cool down.\n\n28 minute total experience.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/ntc-prod/images/a92c3e16bb4cab9ff1e9a05469d786ac/two-hard-one-easy.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Blue",
					body: "Coach Blue Benadum is an NRC Coach based in Los Angeles. Coach Blue is an elite marathoner that has spent years helping all levels of runners realize their greatest potential.",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TWO_HOUR_RUN",
		properties: {
			activeGoal: 7200.0,
			autodownload: false,
			goal: 7200.0,
			activityType: "DURATION",

			previousId: "TWO_HOUR_RUN_ENGB",
			previousIds: ["TWO_HOUR_RUN_ENGB", "TWO_HOUR_RUN"],
		},
		landing: {
			title: "Two Hour Run",
			subtitle: "120 Min • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/e06553199c411801f0fa62641bf52055/two-hour-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/e06553199c411801f0fa62641bf52055/two-hour-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Two Hour Run",
				subtitle: "120 Min • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/e06553199c411801f0fa62641bf52055/two-hour-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Sometimes you need to go long. But that doesn't mean you need to go it alone. Join NRC Global Head Coach Chris Bennett for this 120 minute guided run. Coach will be with you every stride to make sure the longer you go... the better you get.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A 120 minute run with 1 minute of post run guidance and cool down.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Long Run",
					url: "https://static.nike.com/ntc-prod/images/8038e9f9814f2f030c7a2e70d2258e36/two-hour-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/long-run/pl.9d69835850fe46c6a8b693391f8659be",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/0UFQxGiMJtm0v71eQrgyTX",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TWO_MILE_RUN",
		properties: {
			activeGoal: 3220.0,
			autodownload: false,
			goal: 3220.0,
			activityType: "DISTANCE",

			previousId: "TWO_MILE_RUN_ENGB",
			previousIds: ["TWO_MILE_RUN_ENGB", "TWO_MILE_RUN"],
		},
		landing: {
			title: "Two Mile Run",
			subtitle: "2 Mile • Run",
			url: "https://static.nike.com/ntc-prod/images/ar_1.0,c_crop/w_589/293598c4c508d904a1a32b3de80853e1/two-mile-run.png",
			featuredUrl:
				"https://static.nike.com/ntc-prod/images/ar_1.5,c_crop,g_north/w_1179/293598c4c508d904a1a32b3de80853e1/two-mile-run.png",
			backgroundColor: "#4c5aff",
			titleColor: "#ffffff",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#4c5aff",
			headerCard: {
				title: "Two Mile Run",
				subtitle: "2 Mile • Run",
				url: "https://static.nike.com/ntc-prod/images/w_1179,h_2556,c_fill/293598c4c508d904a1a32b3de80853e1/two-mile-run.png",
				backgroundColor: "#4c5aff",
				titleColor: "#ffffff",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "Two miles is the distance and you are the runner. Sounds like the perfect combination. Get ready to have a great recovery run and an even better time with Nike Running Global Head Coach Chris Bennett on this distance based guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "A relaxed and easy two mile run. This is a distance based audio guided run.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/ntc-prod/images/0bec1ceee78ade63258edfaa91beff12/two-mile-run.png",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.",
					titleColor: "#ffffff",
					backgroundColor: "#3b42cf",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "TWO_MINUTE_RUN",
		properties: {
			activeGoal: 120.0,
			autodownload: false,
			goal: 120.0,
			activityType: "DURATION",

			previousId: "TWO_MINUTE_RUN_ENGB",
			previousIds: ["TWO_MINUTE_RUN_ENGB"],
		},
		landing: {
			title: "Two Minute Run",
			subtitle: "2 Min • Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/ba8baf21-fb71-4e60-867a-37a12c694f1c/two-minute-run.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/ba8baf21-fb71-4e60-867a-37a12c694f1c/two-minute-run.png",
			backgroundColor: "#002AFF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#002AFF",
			headerCard: {
				title: "Two Minute Run",
				subtitle: "2 Min • Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/ba8baf21-fb71-4e60-867a-37a12c694f1c/two-minute-run.png",
				backgroundColor: "#002AFF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Got a minute? Good. Got two? Great! Because that’s how long this run is! It’s you and Coach Bennett, the Nike Running Global Head Coach, on this fun 120 second run. Each and every run you do is an opportunity to move forward. So, get ready to run yourself somewhere two minutes better.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A relaxed and fun 2-minute easy run.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/two-minute-run.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Bennett",
					body: "<p>Chris Bennett is the Nike Running Global Head Coach. Coach Bennett is an NRC pioneer that helped build the Nike Run Club from the ground up. He believes that we all have the ability to become better versions of ourselves.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "UP_DOWN",
		properties: {
			activeGoal: 2160.0,
			autodownload: false,
			goal: 2160.0,
			activityType: "SPEED_DURATION",
		},
		landing: {
			title: "Up & Down",
			subtitle: "30 min • Interval Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/b767798f-b294-4e94-8093-e4be875f06fa/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/b767798f-b294-4e94-8093-e4be875f06fa/image.png",
			backgroundColor: "#DFDFDF",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "OFF",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#DFDFDF",
			headerCard: {
				title: "Up & Down",
				subtitle: "30 min • Interval Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/b767798f-b294-4e94-8093-e4be875f06fa/image.png",
				backgroundColor: "#DFDFDF",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Up & Down is a challenging workout that starts fast, requires a steady focus in the middle, and finishes faster. You’ll learn to stay calm and in control while also pushing your limits. Careful pace management will be a key to success in this ladder-style, hard-running interval workout.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>37 minute ladder-style interval run with 5 minute warm up and 5 minute cool down.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Speed Run",
					url: "https://static.nike.com/a/images/w_960,c_limit/2db44eda-f148-4b34-b38a-959a3db47193/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/speed-run/pl.632a597a0256439899ff65edc3f29565",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/4RpqiyPxEHFdpdDuRkgrS5",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach Dan",
					body: "<p>Hone in and get ready to work — that's what Coach Dan is all about. He knows what each and every one of you can tap into, and his sessions will make you stronger and faster at any ability. Coach Dan Fitzgerald is our Boston-based dose of seriousness. He's the founder of Heartbreak.Run, an endurance runner, and surfer who leads thousands of runners from around the world to reach new PRs in the mile through the marathon every year.</p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_1",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 1",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 1",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 1 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_10",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 10",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 10",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 10 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_11",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 11",
			subtitle: "15 Min • Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 11",
				subtitle: "15 Min • Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 11 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_12",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 12",
			subtitle: "15 Min • Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 12",
				subtitle: "15 Min • Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 12 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_2",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 2",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 2",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 2 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_3",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 3",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 3",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 3 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_4",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 4",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 4",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 4 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_5",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 5",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 5",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 5 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
	{
		id: "WEEK_6",
		properties: {
			activeGoal: 900.0,
			autodownload: false,
			goal: 900.0,
			activityType: "DURATION",
			profiles: [],
		},
		landing: {
			title: "Week 6",
			subtitle: "15-min · Recovery Run",
			url: "https://static.nike.com/a/images/ar_1.0,c_crop/w_589/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			featuredUrl:
				"https://static.nike.com/a/images/ar_1.5,c_crop,g_north/w_1179/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
			backgroundColor: "#AA525B",
			titleColor: "#FFFFFF",
		},
		detail: {
			autopause: "DEFAULT",
			audioFeedback: "DEFAULT",
			activityVoiceovers: "ON",
			metricVoiceovers: "OFF",
			accentColor: "#AA525B",
			headerCard: {
				title: "Week 6",
				subtitle: "15-min · Recovery Run",
				url: "https://static.nike.com/a/images/w_1179,h_2556,c_fill/6076b893-5b1c-4b90-ad1d-3fc0f4e0c6ac/image.png",
				backgroundColor: "#AA525B",
				titleColor: "#FFFFFF",
			},
			content: [
				{
					type: "TEXT",
					title: "Overview",
					body: "<p>Start week 6 with Nike Run Coach Diljeet Taylor on this 15-minute easy run. You’ll go over the Half Marathon training for the week ahead so you can plan and make any needed adjustments to your training to win the week.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "TEXT",
					title: "Run Details",
					body: "<p>A comfortable and relaxed 15-min Recovery Run. </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
				{
					type: "MUSIC",
					title: "Nike Run Club",
					url: "https://static.nike.com/a/images/w_960,c_limit/cb00f045-1046-4955-9109-c9732cb2cfed/image.png",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [
						{
							type: "APPLE_MUSIC",
							url: "https://itunes.apple.com/us/playlist/nike-run-club/pl.81fcc5e121924088bc1c8a6ac61516aa",
						},
						{
							type: "SPOTIFY",
							url: "https://open.spotify.com/user/nikerunclub/playlist/1H5JvGH5vahRJKC06OFENH",
						},
					],
				},
				{
					type: "TEXT",
					title: "About Coach",
					body: "<p>Diljeet Taylor is a Nike Run Coach and collegiate and pro coach who has led athletes to multiple NCAA championships and the 2024 Olympics. In her 20 years of coaching, she has and continues to inspire and empower athletes to chase their dreams.  </p>",
					titleColor: "#FFFFFF",
					backgroundColor: "#111111",
					providers: [],
				},
			],
		},
		triggers: [],
	},
];
